### ISSUE TITLE
Make the wave split points in phase

### ISSUE THREAD

**Issue by samreid** [phetsims/greenhouse-effect#10]
From https://github.com/phetsims/greenhouse-effect/issues/3#issuecomment-600985079.  @arouinfar said:

> Could you provide an estimate for how long it would take to make the wave split points in phase?

**Comment by samreid** [comment]
From my prior work on this, I would estimate this would take 2-4 hours for this.  Also, the way it is implemented for the prototype may be different than how it is eventually implemented for the production simulation.

**Comment by kathy-phet** [comment]
OK, can you please go ahead an invest the time to do this for the prototype. Thanks!

**Comment by samreid** [comment]
I manually tuned the phases to put the waves in sync.  It's not perfect because they aren't at the same angle.  If we use something like this for production, we may want to put a "band-aid" stitch between the end of the incoming wave and the beginning of the transmitted/reflected waves.

@arouinfar and @kathy-phet can you please review?

**Comment by arouinfar** [comment]
@samreid I'd say this is good enough for now. The incident wave will end up out-of-phase if k is adjusted, but we can review things at the default k.

![image](https://user-images.githubusercontent.com/8419308/77359600-700d1a80-6d11-11ea-9f5a-ad0b631f96ec.png) ![image](https://user-images.githubusercontent.com/8419308/77359668-8e731600-6d11-11ea-8d0e-fe567337df40.png)
