### ISSUE TITLE
Fix sound file error handling in 1.0 branch

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#100]
A problem was recently found with error handling in sound files, and this problem manifests on certain combinations of MacOS and Safari versions.  The details are in https://github.com/phetsims/tambo/issues/151.  This problem was fixed in a maintenance release, but it turns out that prototype release of sims are not updated as part of that semi-automated process, so the problem will need to be manually fixed on the 1.0 release branch of Greenhouse, since it has only been released as a prototype.

**Comment by Nancy-Salpepi** [comment]
Sorry this issue slipped through the cracks. 
This RC version of the sim as well as the prototype version successfully load using MacOS Catalina + safari 15. The PhET-iO standalone sim and studio version also launch without issue. As expected, there is no sound.
