### ISSUE TITLE
Create and integrate sounds for photon emission and absorption

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#101]
In #36 we worked on creating a "soundscape" for the observation window in the "Waves" screen.  It's time to start working on the sounds for the "Photons" and "Layer Model" screens, and one of the biggest differences between these and the "Waves" screens is that the latter represent light using photons instead of waves.  In today's sound design meeting we decided that it would be good to create some sounds for photon emission and absorption that are consistent with the sounds that we're currently using for waves.

We probably want four sounds, at least to start us off.  They are:
- visible light photon emitted
- visible light photon absorbed
- IR photon emitted
- IR photon absorbed

Assigning to @Ashton-Morris to create the sounds.  Please assign this back to me once we have the sounds, and I'll integrate them into the sim.

**Comment by Ashton-Morris** [comment]
Uploading these now:

- greenhouse-effect-photons-screen-ir-photon-absorbed.mp3
- greenhouse-effect-photons-screen-ir-photon-emitted.mp3
- greenhouse-effect-photons-screen-visible-light-photon-absorbed.mp3
- greenhouse-effect-photons-screen-visible-light-photon-emitted.mp3

**Comment by jbphet** [comment]
I integrated these sounds, and the sound design team reviewed them in the context of an initial prototype version of the Photons screen.  We've decided to wait until there is a bit more realistic version of this screen before we go much further, and at that point we should experiment with just having some of the sounds on at once.

**Comment by jbphet** [comment]
I've published a dev version with only the sounds for re-emission of IR photons from the atmosphere, and we've decided that we generally like this and should move forward with interviews.  Having said that, we want to try out some different sounds for this.  At today's design meeting, we decide to have @Ashton-Morris create a couple alternatives, possibly one or two with a less aggressive attack and may less of a nasal sound.

**Comment by Ashton-Morris** [comment]
I have added three options to try for this.

- re-emission-option-1.mp3
- re-emission-option-2.mp3
- re-emission-option-3.mp3

**Comment by jbphet** [comment]
We have a new sound for photon re-emission from the atmosphere in place, including some variation, and it was presented to the design team last week and it was approved.  Since the previous decision was to only have a sound for atmospheric re-emission, and not for everything else (since it's just too chaotic), the only thing remaining is to clean up the prototype code and finalize the code for the sound that we're going to keep.

**Comment by jbphet** [comment]
This is now basically approved by the design team for the _Photons_ screen.  @Ashton-Morris and I discussed how to start on it for the _Layer Model_ screen, and decided to try the sound that is being used for IR emission from the atmosphere for IR emission from the layers.  Seems logical.  I'll add this and run it by the larger design team.

**Comment by jbphet** [comment]
The sounds for the Layer Model have been added, I'll review with the design team at next meeting.

**Comment by jbphet** [comment]
I'm going to defer this for a while, since I've been asked to focus on things other than the development of this sim for a while.  I'll un-defer when I'm focused on this again.

**Comment by jbphet** [comment]
The sound design has been completed and approved by the design teams.  Closing.
