### ISSUE TITLE
Test some options for viewing one dynamic wave type at a time

### ISSUE THREAD

**Issue by samreid** [phetsims/greenhouse-effect#11]
From https://github.com/phetsims/greenhouse-effect/issues/3#issuecomment-600985079.  @arouinfar said:

Watching visible and IR at the same time can be challenging, and we would like to test some options for viewing one dynamic wave type at a time. One option would be to simply pause the motion of the waves. Another option would be to view it a diffuse beam in the background of the sim, similar to the filtered beam in Color Vision.
<img src="https://user-images.githubusercontent.com/8419308/77031768-3088ac00-6968-11ea-87a8-864a28ca3cf5.png" width=250>

- [ ] For each wave type, add a radio button group to change the view. Options would be:
1. Wave: current dynamic behavior (default)
2. Paused: pauses the motion of the wave
3. Beam: layers a reduced opacity (25%) rectangle over the entire sim background 
4. Hidden: hide the wave

If you have any questions or would like to discuss over Zoom, p

**Comment by samreid** [comment]
Implemented and ready for review.

**Comment by arouinfar** [comment]
@samreid this is looking good in master. If possible, can you layer the wave representations on top of the beam representation?

**Comment by samreid** [comment]
I moved the beams to the back, @arouinfar can you please review?

**Comment by arouinfar** [comment]
Thanks @samreid, closing.
