### ISSUE TITLE
Greenhouse Effect - Publish 1.0 with PhET-iO. Alt-Input. Description. Full Sound

### ISSUE THREAD

**Issue by markgammon** [phetsims/greenhouse-effect#113]
Publish Greenhouse Effect Simulation with PhET-iO, Alt-Input, Description, and Full Sound

- [ ] https://github.com/phetsims/greenhouse-effect/issues/1
- [ ] https://github.com/phetsims/greenhouse-effect/issues/76

**Comment by jbphet** [comment]
I'm going to close this, because it was never assigned to anyone, and thus wasn't kept up to date.  The goals changed, and we published the sim with alt input and sound, but left phet-io and description for later releases.  We will track those efforts in separate issues.
