### ISSUE TITLE
Greenhouse Gas Exploration Controls should come before Observation Window in pdomOrder

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#114]
@jbphet and I will work on this.

**Comment by arouinfar** [comment]
We'd also like to move the "Start Sunlight" button to be the first thing under H2: Play Area. Leaving it in H3: Observation Window will lead to a strange focus order.

**Comment by jbphet** [comment]
Done, at least @jessegreenberg and I think so.  We will review with the team in the next design meeting.

**Comment by jbphet** [comment]
Reviewed with design team and approved, closing.

**Comment by arouinfar** [comment]
@jessegreenberg @jbphet this looks good on the Waves screen, but it should apply to the Photons and Layer Model screens too.

**Comment by jessegreenberg** [comment]
It looks like we haven't set a `pdomOrder` at all for the other screens yet.

**Comment by jessegreenberg** [comment]
I thought about adding the `pdomOrder` but the other screens are missing components, but some UI is missing for those screens and the pdomOrder would be largely duplicated. I wouldn't be surprised if a supertype ScreenView is created to combine common components that are shared between them. I would suggest holding off on this until we start description on the next screens and have all UI components. Does that work for you @arouinfar?

**Comment by arouinfar** [comment]
Yep, sounds good @jessegreenberg. I think we can close this one again.
