### ISSUE TITLE
Equally space waves

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#12]
Extension of #5 

@samreid can you equally space the waves so that they are horizontally distributed throughout the screen? I'd also like to move the clouds to be in the path of the 1st and 3rd visible wave. Here's a very rough sketch. Red = IR, Blue = visible/cloud.
![greenhouse](https://user-images.githubusercontent.com/8419308/77361132-57523400-6d14-11ea-9018-fa48789252d8.jpg)

**Comment by samreid** [comment]
I spaced the waves equally (one spacing for yellow and a different spacing for red--matched manually), please review.

**Comment by arouinfar** [comment]
Thanks @samreid. Looks good in master.
