### ISSUE TITLE
Fix the enumeration usages to use the newly-standardized approach for TypeScript

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#123]
In https://github.com/phetsims/chipper/issues/1106 we established a pattern for how to do enumerations in TypeScript (TS).  This sim was converted to TS before we had a standardized approach, so I glossed over all enumerations by using the `any` type and the `ts-ignore` directive.  I should now go back and fix those up.

**Comment by jessegreenberg** [comment]
OK, EnumerationDeprecated has been removed from this sim. Many ts-ignores have been removed with this issue and with #157. Closing this issue, feel free to take a look at changes @jbphet.

**Comment by jbphet** [comment]
Fixed the `any` usages.  There were fewer than I'd originally thought.  Re-closing.
