### ISSUE TITLE
Add some reflectance for the Waves and Photons screens

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#124]
As of this writing, the ground in the _Waves_ and the _Photons_ screens do not reflect any of the incumbent sunlight.  In the 1/12/2022 design meeting, we collectively decided that this could be a bit misleading to students, especially in the _Photons_ screen, so we should in fact have some light being reflected.  We also decided that, at least for now, we would depict this reflection in the _Photons_ screen but not the _Waves_ screen, since doing it in the _Waves_ screen seems less important and will create more visual complexity that could make things harder to interpret.

We may need to turn up the intensity of the sun to compensate for this if we want the temperatures to be roughly the same.

**Comment by jbphet** [comment]
I came across this table online at https://www.sciencedirect.com/topics/engineering/albedo, and it may be useful for us to reference as we work through this:

![image](https://user-images.githubusercontent.com/3082831/149589522-476e2333-bb74-47a6-9cb9-9205dadd9397.png)

I'll use a value of 0.15 initially, since that's in the middle of the "Green Meadow" value, which is what the view currently looks like.

**Comment by jbphet** [comment]
This has been added, and I'll review the behavior with the design team at the next design meeting.

**Comment by jbphet** [comment]
At today's design meeting, we decided that overall we should model the Earth as a blackbody in the Layers Screen (see https://github.com/phetsims/greenhouse-effect/issues/121 for more on this discussion), that the ground should reflect 20% of incident light on its own, and adding the cloud should increase the overall reflectance to a total of 30%.

**Comment by samreid** [comment]
@jbphet is this issue still ready for review? Should it be brought back to design meeting?  I'm just triaging the unassigned ready for review issues, and saw this one.

**Comment by jbphet** [comment]
Thanks for calling this to my attention @samreid.  This has been implemented for a while and can be closed.
