### ISSUE TITLE
Date concentrations are all described as "high levels of greenhouse gases"

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#127]
Concentration in this sim is modelled by a value form 0 to 1. When the value is 0, concentration is described as "no greenhouse gases". At 1, concentration is described as "max levels of greenhouse gases". The range is then divided evenly into steps along descriptions for "very low", "low", "moderate", "high", and "very high".

A potential issue is that date concentrations are in a small range of the allowable concentration values.
![image](https://user-images.githubusercontent.com/6396244/150375568-f8cb4325-b161-4f83-a84f-dd5452b68b11.png)

Ice age has a concentration value of 0.625 and 2020 has a value 0.75. Both of these fall into the "high levels of greenhouse gases" description. So concentration at every date from ice age to 2020 will be described as high concentration. @Matthew-Moore240 @arouinfar is this OK or is this an issue?

**Comment by arouinfar** [comment]
There aren't any explicit mentions of quantitative greenhouse gas levels at a particular time period and the slider covers a much wider range than the Time Period scene. So in principle, it's acceptable for time periods to fall within the same range. That said, I think there could be more granularity in how we are describing the range. @Matthew-Moore240 and I re-worked the ranges in https://docs.google.com/document/d/1HWVypTlzM5oSUhhcv7gPdx1sSCs0j-xgIF3lbSgzwAQ/edit#heading=h.ey1kiswcb5aq and added 2 new levels: extremely high and extremely low. The size of each chunk also varies a bit. This keeps 1750-2020 in the "high" bin but moves the Ice Age down to "moderate."

The inclusivity and exclusivity of the ranges are a bit weird, but I came up with a method that will ensure that the "extremely high/low" are heard on the normal keyboard step interval.

**Comment by arouinfar** [comment]
Tagging #130

**Comment by jessegreenberg** [comment]
This was done, can you please review @arouinfar?

@jbphet just pinging you in case you want to review the description code. The only tricky part was the "inclusive"/"exclusive" request in the design doc for deciding which description string to use.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! The behavior looks good in master. I'll re-assign to @jbphet so he has a chance to review the code, if desired.

In case it's useful for future comparison, here is what the greenhouse gas concentration values look like when increasing the slider with the default step, starting from None:
1. Extremely low
2. Very low
3. Very low
4. Very low
5. Very low
6. Low
7. Low
8. Low
9. Low
10. Moderate
11. Moderate
12. Moderate
13. High
14. High
15. High
16. Very High
17. Very High
18. Very High
19. Extremely High
20. Max

**Comment by jbphet** [comment]
Code changes look reasonable to me.  Closing.
