### ISSUE TITLE
Update ranges for comparative greenhouse gas concentration descriptions when controlling by date

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#128]
The design doc has these to generate a description like 
>"Greenhouse gas levels {{value from table below}} than {{nineteen fifty}}."

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-634e0716-7fff-6a0d-8af6-e8b02619e5d7"><div dir="ltr" style="margin-left:0pt;" align="left">

Difference in ConcentrationProperty | Increase | Decrease
-- | -- | --
[0, 0.05] | higher | lower
(0.05, 0.15] | much higher | much lower
(0.15, 1] | vastly higher | vastly lower

</div></b>
</body>
</html>

The concentration for 2020 is 0.75 and the concentration for ice age is 0.625. From this range would you like to adjust this table?

**Comment by arouinfar** [comment]
Desired description:
* 2020 is higher than 1950/1750 and vastly higher than Ice Age
* 1950 is lower than 2020, higher than 1750, and much higher than Ice Age
* 1750 is lower than 2020/1950 and much higher than Ice Age
* Ice Age is vastly lower than 2020 and much lower than 1950/1750.

Current Data:
| Time Period | `concentrationProperty` |
| --- | --- | 
| 2020 | 0.75 |
| 1950 | 0.724 |
| 1750 | 0.72 | 
| Ice Age | 0.625 | 


@jessegreenberg here are the updated ranges:
| Difference in ConcentrationProperty | Increase | Decrease |
| -- | -- | -- |
| [0, 0.04] | higher | lower |
| (0.04, 0.1] | much higher | much lower |
| (0.1, 1] | vastly higher | vastly lower |

**Comment by arouinfar** [comment]
Tagging #130

**Comment by jessegreenberg** [comment]
I updated the ranges as described in the last table, back to @arouinfar to review.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg, looks good in master!
