### ISSUE TITLE
Rename GasConcentrationAlerter

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#129]
This alerter has grown to be much more than just for gas concentration, it is responsible for most alerts in the waves screen. It should be renamed accordingly.

**Comment by jessegreenberg** [comment]
I thought about doing this but decided to wait until we start to work on description in the other screens, it isn't clear how components of the current alerter will be reused for other screens yet. We will rename/reorganize when we have time.

**Comment by jbphet** [comment]
Deferring until description becomes a priority again.

**Comment by jbphet** [comment]
The description feature has become a priority again.  Undeferring.

**Comment by jbphet** [comment]
@jessegreenberg are doing this now, and trust that we'll get it done.  Closing.
