### ISSUE TITLE
Review interactive description for the "Waves" screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#130]
@jessegreenberg and I have completed the first round of the description implementation for the Waves screen as specified in the [Interactive Description Design document](https://docs.google.com/document/d/1HWVypTlzM5oSUhhcv7gPdx1sSCs0j-xgIF3lbSgzwAQ/edit).  This would be a good time for the designers to test it, review it, and provide feedback.  I've published a dev version at https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.6/phet/greenhouse-effect_a11y_view.html.  @arouinfar and @Matthew-Moore240 - please try it out and log any change requests in this issue.

**Comment by arouinfar** [comment]
The review of the Waves screen description has been completed, and the resulting issues tagged here have all been addressed (open issues are pending interviews). I think it's time we closed this issue.
