### ISSUE TITLE
"Gasses" should be "Gases"

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#133]
For #130 

The plural of "gas" is "gases", but I found a few instances of "gasses" in the state descriptions:
* "Currently" statement in the Scene Summary
* Greenhouse Gas Concentration slider value
* 2nd bullet under Observation Window

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, this has been fixed throughout including in variables and documentation. I actually thought it was "gasses" 😆
