### ISSUE TITLE
Remove "Surface temperature stabilizing."

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#134]
For #130 

When switching between the Explore Mode radio buttons, there is a context response that says, "Surface temperature stabilizing." Originally, we intended this statement to let users know that the system was equilibrating, not realizing that all of the other context responses would also get triggered. For example, this is what a user hears when switching between modes:

>Now moderate levels of greenhouse gases in atmosphere.
**Surface temperature stabilizing.**
Less infrared radiation redirecting back to surface.
Surface temperature cooling, now 282.1 Kelvin.
Less infrared radiation emitting from surface.
Surface temperature cooling, now 278.8 Kelvin.

The "Surface temperature stabilizing." statement is unnecessary here, so let's get rid of it.

**Comment by jessegreenberg** [comment]
This alert has been removed. I think this was the only usage of this string so I removed it entirely. @arouinfar @Matthew-Moore240 reassigning to you to review or close.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg, looks good in master. Closing.
