### ISSUE TITLE
Add a delay between scene descriptions when date changes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#135]
Discussed today in a design meeting. @arouinfar and @Matthew-Moore240 mentioned that each time a new date radio button is pressed we hear the new scene description and a description of how the concentration changed. If you rapidly cycle through radio buttons with a keyboard you hear a rapid fire spam of this content.

We can use utterance-queue and `Utterance.alertStableDelay` to improve this.

A potential issue with the description was mentioned during meeting - the description uses the previous value in a `link` to generate the description. So if you quickly cycle you will hear how concentration has changed from the last selected button, not how it changed since interaction started. We decided this wasn't an issue to work on yet, but will decide later if in needs to be handled.

**Comment by jessegreenberg** [comment]
Change was made in the above commit. It waits 500 ms before speaking the date change responses in the UtteranceQueue. That value can be modified, but it feels pretty reasonable to me.

@arouinfar @Matthew-Moore240 over to you to try it out.

**Comment by arouinfar** [comment]
@jessegreenberg I think the buffer really helps with the pile-up of responses. I think 500 ms is a reasonable amount of time. Long enough to alleviate the pile-up, but not so long that there's a noticeable lag.

> So if you quickly cycle you will hear how concentration has changed from the last selected button, not how it changed since interaction started. We decided this wasn't an issue to work on yet, but will decide later if in needs to be handled.

Screen reader users can key through the radio buttons without actually changing its value, similar to how they access other state descriptions, so this is unlikely to be an issue.

**Comment by jessegreenberg** [comment]
Reopening. Over slack @Nancy-Salpepi and @arouinfar reported that this is still a problem if you press and hold an arrow key to cycle through the radio buttons. But it is fixed if you quickly tap an arrow key to move through the dates.

The reason is because the browser adds a a small delay when you press and hold an arrow key and that delay is longer than the 500 wait time we added to wait before speaking the related context response. 
![rts2](https://user-images.githubusercontent.com/6396244/184384484-5bc8fe7c-7ae6-45f7-bf64-15a7791419da.gif)

This will be fixed if we increase the 500 ms delay to something longer than the delay before press and hold. However, this delay is a user setting:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/6396244/184385114-28dc5414-f379-4d9f-ad22-c20d50c52c86.png">

So no matter how we change it there is a chance it could always happen if the user sets the delay to a very long value.

But we could double the `alertStableDelay` to 1 second and that will be better for default user settings. Delay would probably not be perceptible to the user because the AT will still read the new name of the radio button as you change radio buttons.

**Comment by jessegreenberg** [comment]
@arouinfar @Matthew-Moore240 can you review this and let me know if you would like to try changing anything?

**Comment by jessegreenberg** [comment]
I found that a delay of 1 second is not enough to fix it on MacOS, but is enough for Windows. Over slack we agreed to try 1.5 second delay, which does work for default macOS settings.

It is just important that the delay be less than `ALERT_DELAY_AFTER_CHANGING_CONCENTRATION` (2 seconds) so that the other alerts related to temperature/IR still come out in the right order. I added an assertion so this doesn't break in the future.

Here is a dev version with this change, @arouinfar @Nancy-Salpepi @Matthew-Moore240 can you please review this change?

https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.13/phet/greenhouse-effect_en_phet.html

**Comment by Nancy-Salpepi** [comment]
@jessegreenberg with VO and in a11y view, I no longer hear/see any scene descriptions for the years in between 2020 and the Ice Age when navigating quickly from one to the other.

**Comment by arouinfar** [comment]
@jessegreenberg increasing the `alertStableDelay` to 1.5 eliminates the transient radio button aria values from being read out in VO, and behavior feels very natural.  I'll use dev.13 in today's interview and see how it goes.

I'll leave this issue open and self-assigned as a reminder to watch how users switch between the radio buttons. Even when quickly skipping through time periods, the comparative greenhouse gas concentration is always relative to the nearest neighbor. For example, switching quickly from 2020 > Ice Age will still queue up the 1750 > Ice Age description:

> Greenhouse gas levels much lower than year seventeen fifty.

**Comment by Nancy-Salpepi** [comment]
@arouinfar and @jessegreenberg I do want to point out that this leads to a delay in the sound. For visual users using keyboard nav, the movements and sounds no longer match (delay when hearing sound after checking checkboxes, moving through radio buttons or pressing reset all). It is really obvious when VO isn't on.

**Comment by Nancy-Salpepi** [comment]
actually it happens with the mouse too.

https://user-images.githubusercontent.com/87318828/184405747-6442ec74-1134-40d9-9478-55c28ed2a8c1.mov

**Comment by Nancy-Salpepi** [comment]
@jessegreenberg after clearing history, sound is no longer delayed!

**Comment by arouinfar** [comment]
During interviews with screen reader users, this was not an issue. Both users (Mobile VO & JAWS) moved the focus between the radio buttons without actually selecting them, so they heard the appropriate comparative statements, so let's close.
