### ISSUE TITLE
Adjust size of keyboard slider step

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#139]
Related to #130 

With the updates to the ranges made in #127, I'd like to also update the keyboard step sizes for the greenhouse gas concentration slider. 

- [x] Standard step: 0.05
- [x] Shift step: 0.01
- [x] Page up/down step: 0.20

**Comment by jessegreenberg** [comment]
This was done as part of #127, over to you to verify @arouinfar.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg, looks good in master.
