### ISSUE TITLE
Update Time Period and Explore Mode help text

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#140]
Related to #130

The primary goal of the Time Period mode is to compare the various time periods, and we'd like to make that clearer in the help text. 

@jessegreenberg @jbphet please make these updates to the help text:
- [x] Time Period RadioButtonGroup: Compare greenhouse gas levels at different time periods.
- [x] Explore Mode RadioButtonGroup: Directly set the concentration or compare time periods.

**Comment by jessegreenberg** [comment]
I just updated these strings. "explore by time period..." also appears in the screen summary, are you trying to replace all of these to compare? Should that be changed too?

![image](https://user-images.githubusercontent.com/6396244/161314446-23ff29f4-26c8-4ddc-bcbf-dd1873222a97.png)

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! I think we can continue to use the "explore" language in the Scene Summary since it's essentially a reference to the Explore Mode RadioButtonGroup. I reviewed the updated help text in master, and the changes look good, so closing.
