### ISSUE TITLE
Remove "in the atomsphere" from some responsive descriptions

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#141]
Related to #130.

For the sake of brevity, there are few places where we can cut out "in the atmosphere" from the responsive descriptions. The atmosphere is referred to elsewhere, and I don't think there is loss of clarity.

Please remove "in the atmosphere" from:
- [x] Greenhouse Gas Concentration slider aria-valuetext
- [x] Context responses when switching between Explore Mode radio buttons: "Now, {{moderate levels of}} greenhouse gases.”

**Comment by jessegreenberg** [comment]
Trying to understand how changing string patterns with this phrase will impact other descriptions...

It appears one place in a pattern that is used in one function called `getConcentrationDescriptionWithValue`. It is used for
- The screen summary.
- The slider `aria-valuetext`
- The description of the observation window.

It appears in a string pattern used in a function called `getCurrentConcentrationLevelsDescription` which is used for 
- The response when the concentration control mode changes

It appears in a string pattern used in a function called `getConcentrationDescriptionWithDate` which is used for the same things as `getConcentrationDescriptoinWithValue`, just including the date.

We want to remove it from explore mode changes and the aria-valuetext but not the observation window or screen summary so we may need to create some new string patterns.

**Comment by jessegreenberg** [comment]
OK done in the above commit. I added an option to the `getConcentrationDescriptionWithValue` function so that we can decide whether or not to include "in atmorsphere" in each place.

@arouinfar back to you to review.

**Comment by arouinfar** [comment]
Thanks for adding the option @jessegreenberg. I took a spin in master and the updated descriptions look good.
