### ISSUE TITLE
Add sonification for the energy balance indicator

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#143]
The energy balance indicator could potentially be sonified.  In the 4/19/2022 design meeting, we decided to try some things, see how they worked out, and decide whether to keep and refine them or abort.

At this point, we're thinking that we will focus on adding sounds to represent the net value and, for now, ignore the separate "In" and "Out" indications.  We can have a core sound that pitches upward when the net arrow points up (energy exiting the atmosphere) and pitches downward when the net arrow points down (energy being retained in the atmosphere).

Ducking may be desired, but we will get to that later.

@Ashton-Morris will come up with a core sound that is harmonious with the existing ones, and then @jbphet will integrate, and we'll see what we think at that point.

**Comment by jbphet** [comment]
I discussed this with @kathy-phet and @arouinfar at the weekly design meeting for this sim, and they are of the mind that we shouldn't spend time implementing sound for this indicator right now, and should revisit later in the implementation process.  They have concerns about having too many layered sounds, even with ducking.  I'll defer this for now and will revive it later.

**Comment by jbphet** [comment]
@emily-phet, @Ashton-Morris, and I discussed this at today's sound design meeting, and @emily-phet suggested that we continue with the sound design for this but have it under the "Extra Sounds" control in the preferences dialog.

**Comment by jbphet** [comment]
@Ashton-Morris - Please provide me with the 'blip' sounds (the ones used in the GHE_Energy_Balance_Mockup_Tempo_Blips.m4v mockup) and I'll integrate them.

**Comment by Ashton-Morris** [comment]
[Here is the file.](https://drive.google.com/file/d/1Mdttzefnr_1g0Temi7jwbfXX55Fur6ab/view?usp=sharing)

- ghe-energy-balance-indicator-blip.mp3

**Comment by jbphet** [comment]
@Ashton-Morris - I changed the name of `ghe-energy-balance-indicator-blip.mp3` to `energyBalanceBlip.mp3` when incorporating it into the code.  This is to let you know so that you can track the source file(s).

- [ ] Duly noted.

**Comment by jbphet** [comment]
I have an initial implementation of this.  We will review it at the next sound design meeting.  Deferring until then.

**Comment by jbphet** [comment]
Reviewed in the 8/2/2022 sound design meetings and decided to make the following changes:
- [ ] Slightly increase the max and min blip frequencies
- [ ] Make the fade infinitely long for now, and possibly remove it entirely if we decide we like this
- [ ] Move it behind the "Extra Sounds" options
- [ ] Add some additional reverb to the sound

**Comment by jbphet** [comment]
The sound design team reviewed the current version in today's meeting, and we like what we've got.  @Ashton-Morris will check the mix, then we should be done.

**Comment by Ashton-Morris** [comment]
@jbphet I think you should turn up the Energy Balance Indicator 10%. Its pretty close to perfect but it needs a small boost.

**Comment by jbphet** [comment]
I've increased the output level.  Please check it out on master.  Remember that you need to turn on "Extra Sounds" from the preferences dialog to turn it on.

**Comment by jbphet** [comment]
Done and approved.  Closing.
