### ISSUE TITLE
stepModel is protected

### ISSUE THREAD

**Issue by zepumph** [phetsims/greenhouse-effect#144]
From https://github.com/phetsims/chipper/issues/1237, but I see 

https://github.com/phetsims/greenhouse-effect/blob/fe4c2a6ad767044d0c71cd0c41c1ce90681a0593/js/common/view/LayersModelTimeControlNode.ts#L25

I ts-ignored until we can figure it out.

**Comment by jbphet** [comment]
I went ahead and made `stepModel` public and added some header documentation that said calling `step` is generally preferred.  My thinking was that the use case where this was being called outside of the class and descendants thereof seemed legit, so making it public is reasonable.  Closing.
