### ISSUE TITLE
Sliders should snap to ticks on Layer Model screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#145]
All sliders on the Layer Model screen should snap to their tick marks as currently defined.

Arrow keys and shift-arrow keys should both move one tick (so there would be no difference between the two).

Page Up and Page Down should go to the major ticks on the first slider.  On the other sliders they should go two ticks.

**Comment by jbphet** [comment]
Done.  Note that we wrote in the comment above (based on what was said in the review meeting) "Page Up and Page Down should go to the major ticks on the first slider".  Strictly speaking, it's not very easy to do this in some cases, such as when the user has positioned the slider on one of the minor ticks.  This is because the options only allow me to specify the amount of the change with no other constraints.  As a result, the implementation was the same in all three cases, which is that the Page Up and Page Down keys move the slider thumb by two ticks.

@arouinfar - Please review the behavior on master.  Feel free to close if it looks correct.

**Comment by arouinfar** [comment]
Thanks @jbphet looks good in master.
