### ISSUE TITLE
Review the thermometer range for the Waves and Photons screens

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#146]
We recently made some changes to the thermometer behavior in the Layer Model screen, decoupling it from the first two screens, since it allows for a much higher temperature range.  In the course of that, there was some discussion about revisiting the first two.  Let's review those and make sure the behavior is what we're after.

**Comment by arouinfar** [comment]
Looks like the first tick mark on the thermometer coincides with 245 K, which is the temp before sunlight is turned on (all good). The thermometer appears to max out around 300 K, but if you remove the cloud the true max is just shy of 310 K. @jbphet let's increase the thermometer max to 310 K.

|Greenhouse Gas Concentration | Cloud | Temp |
| --- | --- | --- |
| Max | Off |  <img height=200 alt="image" src="https://user-images.githubusercontent.com/8419308/168676041-48a2dbcb-1279-413f-b6cc-f597045bc969.png"> |
| Max | On |  <img height=200 alt="image" src="https://user-images.githubusercontent.com/8419308/168676163-49e39ac1-01cc-4b66-817e-83e249494758.png"> |
| None | Off | <img height=200 alt="image" src="https://user-images.githubusercontent.com/8419308/168676505-da38df65-7a13-40dc-8a26-9c7b3be37197.png"> |
| None | On | <img height=200 alt="image" src="https://user-images.githubusercontent.com/8419308/168676956-5c7702bb-351a-427d-b6c5-fe3b0fe5dd4f.png"> |

**Comment by jbphet** [comment]
Done.  @arouinfar - please check on master and close if it looks good.  The value of 310 still ends up with the thermometer almost entirely full, so we could go a little higher if you like.

**Comment by arouinfar** [comment]
Thanks @jbphet. The thermometer appears to max out a bit before it actually does, so let's bump up the max a bit further to 320 K.

**Comment by jbphet** [comment]
I changed the code around a bit so that the max expected temperature is specified in `GreenhouseEffectObservationWindow` and used for setting the range of sound generation, and the thermometer range is specified by an amount above this range.  I tried setting it up so that the max was effectively 320 Kelvin, but that left a lot of white at the top of the thermometer, so I iterated a few times and ended up at an effective value of ~312 Kelvin for the max.  @arouinfar - please have a look and let me know what you think (and feel free to close if you're good with it).

**Comment by arouinfar** [comment]
Thanks @jbphet! The thermometer looks full, but doesn't appear to max out too early.
