### ISSUE TITLE
Updates to temperature units ComboBox descriptions

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#149]
For #130 

Currently, the accessible name of the ComboBox includes its value. This matches the behavior of other described ComboBoxes, such as the Solute ComboBox in Molarity. However, the surface temperature is dynamic, so including it in the accessible name of the ComboBox becomes problematic. If a user focuses on the ComboBox while the surface temperature is changing, there is an avalanche of information as the screen reader interrupts itself to provide the updated value.

Proposed updates:
- [x] Change accessible name (the name read out when the control gets focus) to "Temperature units {{units}}", e.g. "Temperature units {{degrees Fahrenheit}}". 
- [x] Add object response when the selected units change. "Surface temperature {{value units}}.", e.g. "Surface temperature 14.3 degrees Celsius."

Here's a mockup of what the responsive descriptions could look like. Here, the concentration has just been reduced and the surface temperature is in the process of cooling when the user changes the units. In the mockup, the temperature units object response slots into the other "Cooling" responses.

```
Surface temperature cooling, now 287.3 Kelvin. 
Cooling.
Cooling.
Cooling, now 275.2 Kelvin.
Cooling.
Surface temperature 1.3 degrees Celsius.  \\Object response for switching units to degrees Celsius. 
Cooling.
Cooling, now 1.2 degrees Celsius.
Cooling.
Cooling.
Surface temperature stable at 1.0 degrees Celsius.
```

**Comment by jessegreenberg** [comment]
> Add object response when the selected units change. "Surface temperature {{value units}}.", e.g. "Surface temperature 14.3 degrees Celsius."

Discussed with @arouinfar. The AT is going to read a default object response when it receives focus again, which will be the accessible name "Surface temperature {{units}}". We cannot prevent this. So we decided to append the new units value after units Property changes.

**Comment by jbphet** [comment]
Changes implemented.  @arouinfar - please review the behavior on master.

**Comment by arouinfar** [comment]
Thanks @jbphet @jessegreenberg sounds great in VO!
