### ISSUE TITLE
Use “significantly” instead of “vastly” in comparative greenhouse gas concentration descriptions

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#152]
For #130

When switching between 2020 and the Ice Age, we say that the greenhouse gas levels are “vastly lower/higher”. The team prefers describing the difference as  “significantly higher/lower”.

@jessegreenberg @jbphet please swap out “vastly” for “significantly” in comparative greenhouse gas concentration descriptions.

**Comment by jbphet** [comment]
@arouinfar - This has been done on master, please check the behavior and close if it looks good.

**Comment by arouinfar** [comment]
Looks great, thanks!
