### ISSUE TITLE
Update qualitative descriptions of surface temperature for time periods 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#153]
For #130

When the Show Surface Temperature checkbox is on, we a provide qualitative temperature in the equilibrium statement ( “Surface temperature stable and very high.”) and in the bulleted list in the Observation Window (“The surface temperature is very high.”). 

In a recent design meeting we decided to describe the temperatures has “historically” high, low, etc. @jbphet @jessegreenberg please make these changes:

- [x] Ice Age: historically low
- [x] 1750 & 1950: historically moderate
- [x] 2020: historically high

**Comment by jbphet** [comment]
This has been implemented on master.  @arouinfar and/or @Matthew-Moore240 - Please check out the behavior on master and, if it looks good, feel free to close.  If not, please assign it back to me and @jessegreenberg with your feedback.

**Comment by arouinfar** [comment]
The behavior in master looks good @jbphet, thanks
