### ISSUE TITLE
Update ranges for qualitative temperature description

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#154]
For #130 

The descriptions of greenhouse gas concentration was updated in https://github.com/phetsims/greenhouse-effect/issues/127 to include extremely high/low. This change has made the qualitative temperature descriptions a bit out of sync, for example:
"Currently, **Low** levels of greenhouse gases in atmosphere. Earth's surface temperature is **somewhat high**, 271.1 Kelvin. "

I've updated the temperature ranges to avoid obvious mismatches like the example above, but it's purposely not designed to have a 1:1 mapping between greenhouse gas levels and surface temperature at equilibrium. I've also removed the "somewhat low/high" levels, because it creates a large swath of temperatures that seem more moderate than they actually are. 

| Range  (in K) | Temperature |
| --- | --- |
| < 260 |  extremely low |
| [260, 275) | very low |
| [275, 283) | low |
| [283, 288) | moderate |
| [288, 293) | high |
| [293, 301) | very high |
| >= 301 | extremely high |

Here's what this mapping will look like in practice. I'm including this table for future reference, it's not necessary for implementation (use table above for that).

Concentration | Temp (Cloud) | Temp Qual | Temp (No Cloud) | Temp Qual
-- | -- | -- | -- | --
0% = None | 255.4 | extremely low | 264.1 | very low
5% = Extremely low | 257.6 | extremely low | 266.2 | very low
10% = Very low | 259.9 | extremely low | 268.5 | very low
15% = Very low | 262.1 | very low | 270.9 | very low
20% = Very low | 264.4 | very low | 273.2 | very low
25% = Very low | 266.6 | very low | 275.5 | low
30% = Low | 268.8 | very low | 277.8 | low
35% = Low | 271 | very low | 280.1 | low
40% = Low | 273.2 | very low | 282.8 | low
45% = Low | 275.4 | low | 285.1 | moderate
50% = Moderate | 277.5 | low | 287.3 | moderate
55% = Moderate | 279.7 | low | 289.6 | high
60% = Moderate | 281.9 | low | 291.8 | high
65% = High | 284 | moderate | 294 | very high
70% = High | 286.2 | moderate | 296.2 | very high
75% = High | 288.3 | high | 298.5 | very high
80% = Very high | 290.4 | high | 300.7 | very high
85% = Very high | 292.6 | high | 302.9 | extremely high
90% = Very high | 294.7 | very high | 305.1 | extremely high
95% = Extremely high | 296.9 | very high | 307.3 | extremely high
100% = Max | 299 | very high | 309.1 | extremely high

**Comment by jessegreenberg** [comment]
This was done in the above commit, can you please verify this is working correctly @arouinfar?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg. Looks great in master!
