### ISSUE TITLE
Should IR redirected to surface be mapped to greenhouse gas levels?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#156]
Related to #130 

The Observation Window contains these statements:
> * Low levels of greenhouse gases in atmosphere.
> * Infrared waves emit with very low intensity from surface and travel to space. Moderate amount of infrared energy is redirecting back to surface.
> * The surface temperature is very low, 273.8 Kelvin.

The surface temperature (very low) is mapped to the intensity of the IR emitted from the surface (very low). Should we also map the greenhouse gas levels (low) to the amount of IR redirected to the surface (moderate)?

Currently, the amount of IR redirected is divided evenly between 5 levels - very low, low, moderate, high, very high. The greenhouse gas concentration uses these same levels, but adds an extremely low/high, and the ranges are not equally sized.

Tagging @jbphet to get the team's feedback in design meeting.

**Comment by jbphet** [comment]
We reviewed this in the design meeting today, and agree that the same or similar qualitative description should be used for the IR coming back to the surface.  Assigning back to @arouinfar and @Matthew-Moore240 to refine the description before implementation.

**Comment by arouinfar** [comment]
@jbphet I reviewed this with @Matthew-Moore240 and we decided to simply use the same value for both the greenhouse gas levels and the amount of IR redirected to the surface. For example:

> {{Very high}} levels of greenhouse gases in atmosphere.
> {{Very high}} amount of infrared energy is redirecting back to surface.

Back to @jbphet and @jessegreenberg for implementation.

**Comment by jbphet** [comment]
Question: In "Date Mode" for controlling the concentration, should we use this "historically..." language that we use for the greenhouse gas levels too?

**Comment by jbphet** [comment]
I've implemented this using the same 'historical' language as the gas concentrations.  For the most part, it seems good, but in some cases - including the first one that users are likely to encounter - it seems a little odd.  For instance, if you start up the sim, switch to date mode, and leave 1750 selected, it will say this:

> Infrared waves emit with historically low intensity from surface and travel to space. Historically moderate amount of infrared energy is redirecting back to surface.

If I were a user, I think I might find this confusing.  If historically low IR levels are coming from the ground, how can there be historically moderate levels coming from the atmosphere?  Where is the additional energy coming from.  I get what we are saying, which is that due to the moderate levels of greenhouse gases there is a moderate amount of IR coming back, but in context it seems odd.

@arouinfar - Over to you for comment and potential further refinement.

**Comment by arouinfar** [comment]
@Matthew-Moore240 and I discussed this during description meeting.

>> Infrared waves emit with historically low intensity from surface and travel to space. Historically moderate amount of infrared energy is redirecting back to surface.
>
>If I were a user, I think I might find this confusing. If historically low IR levels are coming from the ground, how can there be historically moderate levels coming from the atmosphere? Where is the additional energy coming from?

When looking at a singular statement like this, I agree @jbphet. In general, this statement will always have some disconnect when the surface temperature is not at equilibrium, regardless of the mode. That's because the IR emitting from the ground is tied to the surface temperature (takes time to equilibrate) and the IR redirecting is tied to the greenhouse gas levels (immediate change). However, in this situation, there will be context responses alerting the user to the changing surface temperature. There is also a causal relationship here. Increasing the greenhouse gas concentration sends more IR down to the surface, which in turn warms the surface, which then causes the surface to emit more IR.

 I don't think we need to make any further changes to the description just yet, but I will tag this for interviews.

**Comment by arouinfar** [comment]
Based on the interviews with screen readers,  I think we can close this issue. Users rely heavily on the responsive descriptions for information. They are unlikely to read the Observation Window content while the system is equilibrating since there are lots of context responses describing what is going on.
