### ISSUE TITLE
Update Explore Mode RadioButtonGroup help text

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#159]
For #130 

In a recent design meeting, we discussed the fact that the slider scale graphic is never described in the description. We decided that it didn't need its own heading or detailed description, but we could instead edit the Explore Mode RadioButtonGroup help text to convey the idea that the time periods span just a portion of the range available to the slider mode.

@jbphet @jessegreenberg please update the help text to:
- [ ] Explore a wide range of concentrations from none to lots or zoom in and compare historical time periods.

**Comment by jessegreenberg** [comment]
@jbphet and I made this change, closing but feel free to take a look @arouinfar.
