### ISSUE TITLE
Remove mockups

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#16]
Mockups for the various screens are being added at the moment, and this issue is to remind us to remove them prior to publication.

The "Options..." control that sets the opacity for them should also be removed.

**Comment by samreid** [comment]
It seems this is sim-specific, so I'll update the label accordingly.  Please correct me if necessary.

**Comment by jbphet** [comment]
I decided to undefer this and take care of it because the mockups are not being used much anymore and their presence was interfering with the use of the Scenery "helper".  The mockups have now been removed, closing.
