### ISSUE TITLE
Add Slider Max/Min sound to Greenhouse concentration slider

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/greenhouse-effect#164]
Add default Slider Max/Min sound to Greenhouse concentration slider

@arouinfar - Just FYI on this from design 5/25/22. To help convey meaning that we are at "max" of slider.

**Comment by jbphet** [comment]
This has been implemented and sounds good to me.  I'm going to make an executive decision and say that it doesn't require further review, at least not until the sound design is reviewed as a whole.  Closing.
