### ISSUE TITLE
Do we want to change the wording to "historical time period" and, if so, where?

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#166]
In today's design meeting, it was suggested that we use the term "historical mode" and or "historical time period" to better match some of the wording that we're using in other parts of the description.  @arouinfar will go through the description and let us know where this should be changed.

**Comment by arouinfar** [comment]
Places where time period is mentioned:

* Scene Summary, Play Area section: "It has controls to adjust the greenhouse gas concentration or explore by time period..."
* Scene Summary, Currently section: "Currently, the time period is the year seventeen fifty..."
* Time Period RadioButtonGroup
* Time Period RadioButtonGroup help text: "Compare greenhouse gas levels at different time periods."
* Explore Mode RadioButtonGroup help text: "Explore a wide range of concentrations from none to lots or zoom in and compare historical time periods."
* Explore Mode RadioButtonGroup, "By time period" RadioButton

Including "historical" provides more context, so good to include in help text/scene summary, but it doesn't need to be a part of the radio button names. Let's add "historical" here:
- [ ] Scene Summary, Play Area section: "It has controls to adjust the greenhouse gas concentration or explore by historical time period..."
- [ ] *Time Period RadioButtonGroup help text: "Compare greenhouse gas levels at different historical time periods."

**Comment by jessegreenberg** [comment]
I added 'historical' to the two descriptions you mentioned above, @arouinfar anything else for this issue?
