### ISSUE TITLE
keyboard help dialog is missing

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#169]
For https://github.com/phetsims/qa/issues/811, since we are testing interactive description and keyboard nav in 1.1.0-dev.9, shouldn't there be a keyboard help dialog?

**Comment by jbphet** [comment]
I've added the default keyboard dialog, but I'm now wondering if there needs to be a custom version created, such as we did in https://github.com/phetsims/faradays-law/issues/176.  I'll ask about this in the next design meeting.

**Comment by jbphet** [comment]
Discussed in today's design meeting, things to note:
- The "Basic Actions" should be there (we think it's on by default)
- Add in the slider control section (we think this is an option to the dialog)
- For now, we will use the same dialog for all screens
- We may need to add custom information for the interaction with the flux meter, but this isn't necessary for the upcoming interviews on the "Waves" screen

**Comment by jbphet** [comment]
I've added a specific issue about adding specific keyboard help info for the flux meter, which is the only thing we could think of in the design meeting that might require custom verbiage about how to use it.  See https://github.com/phetsims/greenhouse-effect/issues/180.

**Comment by jbphet** [comment]
I will have QA verify this in the next dev release.

**Comment by jbphet** [comment]
Note to QA: Please close after verifying.

**Comment by Nancy-Salpepi** [comment]
Keyboard dialog is present in version 1.1.0-dev.10 with slider controls and basic actions :)
