### ISSUE TITLE
Temperature sounds linked to surface thermometer checkbox

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#170]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/811, I noticed that the temperature sounds were linked to the Surface Thermometer checkbox. Should they be linked to the Surface Temperature checkbox? 

From slack:
Me:
>Are the temperature sounds purposely linked to the surface thermometer checkbox?

@arouinfar:
>I think it’s meant to map to surface temperature, but I’m surprised that it only applies to the thermometer and not the Show Surface Temperature checkbox (which will provide qualitative descriptions of temperature).

**Steps to reproduce**
1. Press the 'Start Sunlight' button
2. Once the temperature begins to rapidly rise, uncheck the 'Surface Thermometer' checkbox
3. Check the 'Show Surface Temperature' checkbox

**Visuals**

https://user-images.githubusercontent.com/87318828/173429937-4c913f58-1dcf-4b59-8474-e49fe0025bcb.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.9/phet/greenhouse-effect_all_phet.html?screens=1
Version: 1.1.0-dev.9 2022-06-08 20:37:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1371x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jbphet** [comment]
Early in the sound design process I believe we had a separate sound for the "Show Surface Temperature" situation.  It sounded kind of crackly at the higher temperatures, like a fire.  If I recall correctly, we thought it was both a bit confusing when everything was turned on and a little intense on its own, so we dropped it.  I'll bring this up at the next sound design meeting and I'll see if anyone recalls anything different, and what they think about using the surface temperature sound for both situations, i.e. "Surface Thermometer" on and "Show Surface Temperature" on.

**Comment by jbphet** [comment]
This has been implemented.  I'll discuss it with the sound design team.

In parallel with that, @arouinfar - can you please try this out on master and comment on whether you thinks it's a decent way to go?

**Comment by arouinfar** [comment]
Sounds good to me @jbphet

**Comment by jbphet** [comment]
The sound design team was good with it too.  Closing.
