### ISSUE TITLE
How should we handle the vastly different ranges of flux values in the flux meter?

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#171]
I'm currently working on implementing the flux meter, and I'm running into a problem due to the scale of variation between the largest flux values and the nominal ones.  I just tried setting up the maximum flux situation on the Layer Model screen and scaling the arrows in the flux meter to work with it.  It looks like this:

![image](https://user-images.githubusercontent.com/3082831/173461548-2718b0d2-9e37-4704-a382-fab7610c5fe9.png)

This doesn't look too bad, but if we use the same scale on the Photons screen, the nominal case where the user just starts the sunlight and doesn't change anything looks like this:

![image](https://user-images.githubusercontent.com/3082831/173461684-5e173394-e3a2-47ba-8031-be9cc2bd697a.png)

These arrows look a little anemic to me, and I don't think users would ever be able to see subtle things like the differences between the different date settings.

Here are some possible approaches:

- Set a scale that we like for most things and have the arrows go off the charts on the 2nd screen, and get clipped
- Use a different scale on the Photons and the Layer Model screens
- Use a logarithmic scale

I think for now I'll implement the first idea, then kick this question around at the next design meeting and see where to take it from there.

**Comment by jbphet** [comment]
For my reference, the code to calculate the max expected flux in such a way that it is not exceeded by the display looks like this:

```js
    // Calculate the maximum expected flux based on the size of the sensor and some other attributes of the model.  The
    // multiplier used in this calculation was empirically determined and may need to adjust if the model changes.
    const maxExpectedFlux = SunEnergySource.OUTPUT_ENERGY_RATE * 8 *
                            model.fluxSensor.size.width * model.fluxSensor.size.height;
```

The value that this yields is 46729600, which I believe is in watts.

**Comment by jbphet** [comment]
We discussed this in today's design meeting, but haven't come to any conclusions yet.  @arouinfar was thinking that maybe a zoom feature would be useful, but wanted to think on it for a bit.  We will discuss this with @kathy-phet the next time she is available for a design meeting.

**Comment by jessegreenberg** [comment]
Initial commit for zoom bottoms above. Buttons only added on the Layer Model screen. There are three zoom levels. @jbphet Ill leave you assigned to review. Feel free to reassign to me or make changes directly if something needs adjusting, or bring back to design if you think it is ready.

**Comment by jbphet** [comment]
Thanks @jessegreenberg - the initial commits looked good.  I made some pretty significant changes.  I've added reference marks behind the arrows so that the scale is discernable, made the zoom factor exponential rather than linear to accommodate a bigger range, made sure that the max values fit, and added an additional zoom level in each direction.  So back at you for review.

At this point, I think it is in reasonable shape to take to the next design meeting.

**Comment by jbphet** [comment]
Assigning also to @arouinfar in case you'd like to review it at a design meeting while I'm out of town.

**Comment by jessegreenberg** [comment]
Reviewed during design meeting today - 

The team thought the behavior and look is great. People really liked the addition of the tick marks for zoom context.

Some requests from the meeting
- Remove the last zoomed in level, the arrows tend to go way off plot and the next level is good enough.
- Remove the grey backgound rectangles behind the energy arrows. 
- The title font for "Energy Flux" should use GreenhouseEffectConstants.TITLE_FONT.

**Comment by jessegreenberg** [comment]
These items were done in the above commit. @arouinfar can you please confirm, is there anything remaining for this issue?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg. Everything looks good in master, closing.
