### ISSUE TITLE
description for play/pause button incorrect

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#173]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/811 and related to https://github.com/phetsims/greenhouse-effect/issues/158

The description for the play/pause button still mentions stepping forward even though that control was removed for the Waves screen. This was seen in a11y view and when using VO. 

**Steps to reproduce**
1. In a11y view, tab to the play/pause button and read the description under Timing Controls
2. Press the button to pause the sim and read the description again

**Visuals**
<img width="563" alt="Screen Shot 2022-06-14 at 11 44 34 AM" src="https://user-images.githubusercontent.com/87318828/173621975-9b988351-2c79-4b26-9d7d-b2ba19ec4f35.png">
<img width="563" alt="Screen Shot 2022-06-14 at 11 45 31 AM" src="https://user-images.githubusercontent.com/87318828/173622004-e4f16f60-1b2b-4917-9a12-50d9ade5cad3.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.9/phet/greenhouse-effect_all_phet.html?screens=1
Version: 1.1.0-dev.9 2022-06-08 20:37:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1371x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment]
If we want very general help text that lives in scenery-phet, we could do something like:

Pause: Pause sim.
Play: Play sim.  (Resume sounds nicer, but implies the sim started in this state, which isn't universally true.)

If we have the possibility of using sim-specific help text, I would go with something more descriptive. 

Pause: Pause action in observation window.
Play: Resume action in observation window.

In general, I think a sim-specific solution may be preferable. In a sim like Pendulum Lab, the main purpose of the PlayPauseButton is to allow users to set up experiments or collect more accurate data. This is very different than Molecules and Light, where the current help text was developed.

Tagging for design meeting to run these options by the team.

**Comment by jbphet** [comment]
The Greenhouse design team discussed this in the 6/22/2022 design meeting, and @arouinfar is going to work with @terracoda to work out a plan for how this should be generally handled in TimeControlNode.

**Comment by terracoda** [comment]
I agree, there should be 2 options for the help text - one to specifically support the presence of the step forward button.

It was quite tricky figuring out the best structure and best words to support blind users in using the step forward button in the description design of _Molecules and Light_. 

The Timing Control Node is quite flexible and modular, so approaching the description design in the same way makes sense to me. Let me know if you would like me to review anything.

**Comment by jessegreenberg** [comment]
OK thanks Taliesin, Ill proceed with this and Ill be sure I don't break what we went with in molecules and light.

**Comment by jessegreenberg** [comment]
This was done and I like that this simplified TimeControlNode.ts a little.

@arouinfar can you please review and confirm this resolved for greenhouse-effect?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! The help text looks good in master.

**Comment by jessegreenberg** [comment]
Great thanks! I am going to go ahead and close this one.
