### ISSUE TITLE
Should "start sunlight to play" be dynamic?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#174]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/811 with VO and in a11y view:
When reading through the scene summary after interacting with the sim, the statement "Start sunlight to play." does not correctly depict the scene (since that button was already pressed). 

**Visuals**
<img width="1235" alt="Screen Shot 2022-06-14 at 12 45 37 PM" src="https://user-images.githubusercontent.com/87318828/173634931-b12d6ef4-a542-4383-b4d0-030bd24952bb.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.9/phet/greenhouse-effect_all_phet.html?screens=1
Version: 1.1.0-dev.9 2022-06-08 20:37:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1371x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Thanks @arouinfar! 
I went and took a look at Friction. That last sentence is actually dynamic. It can be:
* Grab chemistry book to play
* Continue rubbing chemistry book to generate even more friction
* Reset sim to make more observations

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi! Good to know that there is precedent for a dynamic interaction hint.

**Comment by arouinfar** [comment]
This was not an issue for users during interviews. Screen reader users used the PlayPauseButton quite a bit, and it was clear to them what state the sim was in, so "play" language is fine. Also, users generally rely on the responsive descriptions and do not generally return to the Scene Summary for the latest information.
