### ISSUE TITLE
description of greenhouse gases concentration missing

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#177]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/811

In a11y view, I do not see anything about the levels of greenhouse gases as I move the slider but these responsive descriptions are heard with VoiceOver.

**Steps to reproduce**

1. In a11y view, press Start Sunlight button 
2. Tab to concentration slider and slowly increase or decrease the levels of greenhouse gases--description for greenhouse gases concentration will not appear in the Responsive Descriptions box (but will be uttered with VO).

* I UPDATED this issue after remembering that VO will stop speaking alerts related to slider value after some use. I removed the sections in this issue referring to that. 

**Visuals**

https://user-images.githubusercontent.com/87318828/173842284-ff523ba6-a410-4b02-a58f-c5efc447e20c.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.9/phet/greenhouse-effect_all_phet.html?screens=1
Version: 1.1.0-dev.9 2022-06-08 20:37:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1371x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi - I am wondering if this is what is described in https://github.com/phetsims/qa/blob/master/documentation/accessibility-bugs.md under VoiceOver safari bugs:

> After a bit of use, VoiceOver may stop speaking alerts related to the slider value (aria-valuetext). Tabbing away from the component then returning to it will cause VoiceOver to speak its content again.

@Nancy-Salpepi can you see if the problem goes away if you tab away and then back to the slider?

**Comment by Nancy-Salpepi** [comment]
@jessegreenberg yes I realized (too late) that the VO aspect of this issue was a known bug. When I tab back to the slider I do hear alerts again. 
I left the issue open though because I thought it was odd that those alerts didn't appear in the a11y view at all.

**Comment by jessegreenberg** [comment]
Thanks for clarifying. Good question. The reason it doesn't show up in alerts is because of how screen readers work and is not obvious, sorry. There is special information for sliders called "valuetext" that gets read every time the slider value changes. It appears here in the parallel DOM:

![image](https://user-images.githubusercontent.com/6396244/173926150-1d5013c2-8e5d-4ed0-b1a7-18471f5b6045.png)

The VoiceOver bug is that it stops reading this info for some reason.

**Comment by Nancy-Salpepi** [comment]
Ah ok. I thought everything that was read automatically appeared in the Responsive Descriptions section. Thanks for clarifying @jessegreenberg! 
Closing.
