### ISSUE TITLE
mobile VO reads decimal in temperature differently depending on unit

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#181]
**Test device**
iPad Air II

**Operating System**
iOS 15.5

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/811:
Mobile VO reads the decimal in a temperature value as "dot" for Kelvin and degrees F, but as "point" for degrees Celsius. 
VO reads the decimal in all three temperature units as "point".

**Steps to reproduce**
1. With VO on, switch between temperature units. 

**Visuals**

https://user-images.githubusercontent.com/87318828/174139235-7c9ca3d8-9f38-4cf5-a268-8d77d9eeb1a2.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.9/phet/greenhouse-effect_all_phet.html?screens=1
Version: 1.1.0-dev.9 2022-06-08 20:37:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1371x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi - This is an odd difference. Maybe it doesn't have 'kelvin' in its lexicon to read a unit of value. Anyway, there is not much we can do to change the device's pronunciation of things. In the past we have decided not to change spellings or other things to force the AT to say something a particular way. And the a11y community generally discourages it.

@arouinfar @Matthew-Moore240 assigning to you so you are aware of this problem. Can this be closed or can we mark as `wontfix`?

**Comment by arouinfar** [comment]
Good find @Nancy-Salpepi. 

Thanks for the additional context @jessegreenberg. I am fine with closing this as wontfix.
