### ISSUE TITLE
Mobile VO reads sim title after pressing Start Sunlight button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#182]
**Test device**
iPad Air II

**Operating System**
iOS 15.5

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/811 
After pressing the Start Sunlight Button, mobile VO says the sim title, heading level, and a few other things before saying "sunlight started"

This doesn't occur on my mac with VO. 

**Visuals**

https://user-images.githubusercontent.com/87318828/174157825-7b70c39d-be4f-4caa-b9a3-9afa30ad0bc9.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.9/phet/greenhouse-effect_all_phet.html?screens=1
Version: 1.1.0-dev.9 2022-06-08 20:37:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1371x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
This puts you back at the top. If you start swiping to read the next item, you have to read through the whole description before reaching the controls again.

**Comment by KatieWoe** [comment]
This also seems to occur on other screen readers, such as Jaws, but it is much more noticeable and/or troublesome on Mobile VO due to the comparative limited ability to move focus around.

**Comment by arouinfar** [comment]
For Mobile VO, this sounds like a pretty poor experience. Could we shift focus to H3: Observation Window? That way, screen readers (including Mobile VO) can pick up where they left off. It also won't disturb the focus order of UI elements. Hitting tab should still take users to the Greenhouse Gas Concentration slider.

**Comment by arouinfar** [comment]
Yes, that's what I was thinking @jessegreenberg. I'm not particularly worried about "article, landmark" but it seems like better UX to go to the parent H3 rather than all the way back up to the H1.

**Comment by jessegreenberg** [comment]
OK this is done, I made a new node FocusableHeadingNode to support this.

@arouinfar can you please verify that this is working and the PDOM order around the Observation Window is still looking OK for the waves screen?

**Comment by arouinfar** [comment]
The behavior looks good in master @jessegreenberg, but I think this should go back to QA to verify in Mobile VO in the next testing cycle.

**Comment by jessegreenberg** [comment]
OK sounds good, thanks. Adding the "ready-for-review" label for the next dev test.

**Comment by jbphet** [comment]
Note to QA: Please close after verifying.

**Comment by KatieWoe** [comment]
I was moved up to the url bar in dev.10. This was on an iPadOS 15 device.

**Comment by Nancy-Salpepi** [comment]
For me, in dev.10 with iPadOS 15.5 focus moves to Observation Window Heading Level 3 after pressing Start Sunlight button. I believe that is the intended behavior. 

https://user-images.githubusercontent.com/87318828/179259533-541fff5d-dd64-4ecb-87c9-7e25a89c95f7.mov

**Comment by KatieWoe** [comment]
I tried again today and it worked properly. I'm not sure what changed/what I did wrong the first time around, but this can probably be closed if you agree @jessegreenberg

**Comment by jbphet** [comment]
Since QA seems to have verified it and @KatieWoe said, "...this can probably be closed...", I'm going to go ahead and close it.
