### ISSUE TITLE
Modifications to the initial version of the Flux Meter

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#188]
Discussed with @kathy-phet on 6/29/2022:

- Yes, we should modify the flux sensor to span the bulk of the observation window.  It would be nice if it still looked like a probe, so perhaps a thin rectangle and a tight connection to the meter
- @kathy-phet feels that it is confusing that the flux meter doesn't update when the sim is paused and the sensor moves.  While it would be possible to make the flux meter update in this case (by tracking the flux at lots of levels in the model), it would be easier to make it blank out and then update once the sim is un-paused.  Let's do that for now.

**Comment by jbphet** [comment]
I did the two items listed above, but I'd like to also drag prompt arrows before having the design team check it out.

**Comment by jbphet** [comment]
Reviewed in today's design meeting, action items are:
- Make the cuing arrow colors match the border of the probe
- Move the cuing arrows to the right side of the probe
- Instrument these for phet-io, use geometric-optics and molecule-polarity as references for how to do this well

**Comment by jbphet** [comment]
I have added phet-io control of the cueing arrows for the flux sensor, since this was requested during the last design meeting.  It was recommended that I look at the approaches used in molecule-polarity and geometric-optics, but it turns out that these two sims handle phet-io control of their cueing arrows pretty differently.  I opted for the approach used in geometric-optics, where there is one global value that is used to control the visibility of these arrows on all screens.

@arouinfar - Please review what I've done and see if you're good with it.  It works in phet-io Studio, so you can test it there.  Also, please let me know if you think we should use a more specific name than `cueingArrowsEnabledProperty`, such as `fluxSensorCueingArrowsEnabledProperty`.  The latter just struck me as a little verbose.

If you're good with everything, this issue can be closed.

**Comment by jbphet** [comment]
I am a bit bothered by how close the tick marks are to the text at the top of the meter now that the background rectangles have been removed.  This can be seen in the screenshot below.  I asked about it in the design meeting this week, and we decided that I should create a little more space here.

![image](https://user-images.githubusercontent.com/3082831/189452120-89057947-c736-4d1c-b75e-ff7197d97dbf.png)

**Comment by arouinfar** [comment]
@jbphet made some tweaks and the team reviewed in the 9/14/22 design meeting. In general, we liked the changes but recommended reducing the padding between the Visible/Infrared titles and the grid lines to be more similar to the bottom padding.  Looks like @jbphet may have already made that change, here's what it looks like in master:
<img width="90" alt="image" src="https://user-images.githubusercontent.com/8419308/191336195-2a7cc752-e70f-4a1d-9e1e-c252e75924ce.png">  <img width="90" alt="image" src="https://user-images.githubusercontent.com/8419308/191336482-da772e19-6c87-442c-b645-28da5aeaf638.png">

I think it looks good, so deferring to @jbphet to decide whether we should close or review in design meeting with the full team.

**Comment by jbphet** [comment]
We looked at this in the last design meeting, and the team agreed that the spacing now looks good.  I think this can be safely closed now.
