### ISSUE TITLE
Energy Balance header should be below the description list in the observation window

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#190]
Pics for reference:

Current energy balance showing:

![image](https://user-images.githubusercontent.com/3082831/177626503-a096f05d-608d-4bdf-90b2-e6f289d52b80.png)

Current without:

![image](https://user-images.githubusercontent.com/3082831/177626622-e31b1f70-3942-4768-85c2-1db3e2b1362a.png)

The energy balance information, which is an H4, should be below the description list .

**Comment by arouinfar** [comment]
Looks good in master, thanks @jessegreenberg!
