### ISSUE TITLE
Alerts, Energy Balance section and other bullets may not be read in Mobile VO

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#195]
**Test device**
IPad
**Operating System**
iPadOS 15
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/qa/issues/819.
After starting the sunlight, I noticed that swiping through reading, or reading from the top, would skip some bullet points in the scene description (mostly the temperature reading) and skip reading out the energy balance of the sim. I also often did not hear any of the alerts reading out new temperatures as the surface temp changed. The Energy balance seemed to be related when the checkbox was checked. I'm not sure why I was getting no alerts, and the lack of temperature bullet point seemed consistent.
**Steps to reproduce**
1. Turn on mobile VO
2. Before starting sunlight, turn on energy balance
3. Start sunlight
4. Try to read the energy balance

Also note that the alerts don't seem to read and if you read through the description, some bullets such as temperature are missing from the initial description. I heard alerts at first, but they stopped and I wasn't able to determine why or get them back no matter what I tried.

**Visuals**

https://user-images.githubusercontent.com/41024075/179560149-47db8c9c-03b5-4fb6-b396-32aa8331db92.MOV

**Comment by arouinfar** [comment]
This sounds fairly serious, but unlikely to have any impact on the interviews with the consultants since they won't be using MobileVO.

**Comment by jessegreenberg** [comment]
This is the same as https://github.com/phetsims/friction/issues/292 and https://github.com/phetsims/john-travoltage/issues/449. Ill try to identify what is causing it and see if it can be fixed.
