### ISSUE TITLE
`tandem` can be passed via both param and options in several places.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#196]
Noticed during cleanup "TypeScript sprint"....

In greenhouse-effect, there are a number of places when a constructor allows you to pass a `tandem` as both a required constructor parameter and as an option.  For example, in ConcentrationModel.ts:

```typescript
public constructor( tandem: Tandem, options?: LayersModelOptions )
```

The `tandem` parameter is unnecessary and undesirable here. PhET typically passes tandems via options. But more importantly, `LayersModelOptions` includes tandem -- it's not being omitted anywhere. 

For example, there's no TypeScript error when I provide tandem twice to AtmosphereLayer, like this in LayersModel.ts:

```diff
      const atmosphereLayer = new AtmosphereLayer(
        distanceBetweenAtmosphereLayers * ( index + 1 ),
        atmosphereLayersTandem.createTandem( `layer${index}` ),
        {
+         tandem: atmosphereLayersTandem.createTandem( `layer${index}` ),
          initiallyActive: options.atmosphereLayersInitiallyActive,
          initialEnergyAbsorptionProportion: options.initialAtmosphereLayerAbsorptionProportion
        }
      );
``` 

If the goal is to make `tandem` required, the preferred pattern is to use `PickRequired` to add it to your options type. I'd probably start with this change in GreenhouseEffectModel.ts

```diff
- export type GreenhouseEffectModelOptions = SelfOptions & PhetioObjectOptions;
+ export type GreenhouseEffectModelOptions = SelfOptions & PhetioObjectOptions & PickRequired<PhetioObjectOptions, 'tandem'>;
```

Search for `tandem: Tandem,` and you'll find the 5 places that are relevant to this issue.

**Comment by jbphet** [comment]
I think I've addressed all instances of this particular problem, so I'll close it.  Note that there is still a lot of other phet-io work being done under other issues that will probably improve and refine tandem usage over time.
