### ISSUE TITLE
Consider consolidating the controls related to surface temperature on the "Waves" screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#197]
In #170, we decided to make the ambient temperature sound be on when either the "Surface Thermometer" or the "Show Surface Temperature" checkboxes are checked.  So far, the designers are all in agreement that this seems reasonable, but during the sound design meeting @emily-phet suggested that we might want to group these two controls into a panel with a title to make it a bit more obvious that they are closely related.  After some discussion, we came up with something like this (apologies for the ASCII art, it was just a quick way to convey this):

```
 -- Surface Temperature ------------------
|   _                                     |
|  |_| Thermometer                        |
|   _                                     |
|  |_| Glow                               |
 -----------------------------------------
```

The design group discussed this in today's meeting, and concluded that we should log this suggestion as a GitHub issue and see if we notice anyone during interviews having trouble understanding how closely linked these two items are.  If so, we should consider this change to the UI.

We noted during the meeting that this would cause some inconsistency with the other screens, since they don't have the "Glow" option, but that doesn't entirely preclude it from being implemented.

Assigning to @arouinfar, who will keep this in mind during interviews.

**Comment by arouinfar** [comment]
During the student interview, compatibility testing, and screen reader interviews, there didn't seem to be any issue with the association of these two checkboxes. I do not recommend making any changes at this time, especially given the consistency issues we would run into across screens, closing.
