### ISSUE TITLE
Further updates to Explore Mode RadioButtonGroup Responsive Descriptions

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#199]
When switching between the Explore Mode radio buttons, the concentrationProperty changes and the model is no longer in equilibrium. This triggers a ton of responsive descriptions (IR redirected/emitted, energy balance) that seem out of place. 

Switching between the Explore Modes is not an act of experimentation, and the goal should be inform users that they are switching modes and that the surface temperature is equilibrating. @Matthew-Moore240 and I re-wrote the responsive descriptions, and the full details are provided in the [Waves Screen description doc](https://docs.google.com/document/d/1TBfGvk48HH9SzZeWMaf2YUo2SmsD1nzstbdmCdpzK5A/edit#heading=h.wskyxxq1e01) (linked to appropriate section).

**Comment by jessegreenberg** [comment]
Just trying to list the changes from what is currently in place, as I understand from the design doc
- [ ] A change to the way time period is described when changing control mode. This was covered in #200 
- [ ] "Cloud added to sky" alert needs to come after the "Time period is ..." description.
    -  The order is correct when switching from date -> slider but incorrect when switching from slider -> date.
- [ ] Remove all alerts about concentration when control mode changes.
- [ ] After a 2 second delay, we should hear "Surface temperature stabilizing." This should REPLACE the "infrared radiation redirecting/emitting" alerts.

**Comment by arouinfar** [comment]
@jessegreenberg this summary looks good overall. 

> The order is correct when switching from date -> slider but incorrect when switching from slider -> date.

The order seems to be incorrect in both directions.

Selecting "By time period"
<img width="437" alt="image" src="https://user-images.githubusercontent.com/8419308/183953804-fb53d989-6fb1-4c09-aa6d-c1d1e3f88ffa.png">

Selecting "By concentration"
<img width="365" alt="image" src="https://user-images.githubusercontent.com/8419308/183953932-ab4bb257-40df-4912-8694-505d169b1e74.png">

**Comment by jessegreenberg** [comment]
We got all but the last checkbox implemented today. We would like to check in about the two second delay during design meeting today.

**Comment by jbphet** [comment]
Discussed in the 8/10/2022 design meeting, here are the next steps that we've decided upon:

- [ ] Fix the problem where some of the timed alerts come out when the sim is paused
- [ ] Suppress the alerts about changes to IR and energy balance when switching between concentration control modes
- [ ]  Reset the `timeSinceLastAlert` when switching concentration control modes so that the behavior is predictable and we have a time interval before any time-based alerts occur
- [ ] Make it so that the first alert about the surface temperature that occurs after switching concentration control modes is "Surface temperature stabilizing".

@arouinfar will update the spec to reflect the changes and @jessegreenberg and @jbphet will implement these changes in the code.

**Comment by jessegreenberg** [comment]
OK this is done, and @jbphet and I reviewed the changes and made some code improvements. @arouinfar @Matthew-Moore240 can you please verify things are working as you would expect? We are also going to proceed with a dev test soon.

**Comment by arouinfar** [comment]
@jessegreenberg @jbphet this all looks great! I tested in VO/Safari and reviewed the a11y view.

**Comment by Nancy-Salpepi** [comment]
The first three items in https://github.com/phetsims/greenhouse-effect/issues/199#issuecomment-1210885875 look good in version 1.1.0-dev.11 with VO on mac and in a11y view.

**Comment by jessegreenberg** [comment]
Excellent, I think https://github.com/phetsims/greenhouse-effect/issues/199#issuecomment-1211379427 and https://github.com/phetsims/greenhouse-effect/issues/199#issuecomment-1212164829 are the sufficient review for this issue. Closing.
