### ISSUE TITLE
When concentration = none, IR redirected should be "No" not "Less"

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#201]
When the concentrationProperty changes we state:
* {{More/Less}} infrared radiation redirecting back to surface.
* {{More/Less}} infrared radiation emitting from surface.

However, the first statement is incorrect if the greenhouse gas concentration is zero. In the absence of greenhouse gases, we should be saying:
* {{No}} infrared radiation redirecting back to surface.
* {{Less}} infrared radiation emitting from surface.

The current behavior is buggy, so this would be good to fix before interviews.

**Comment by jessegreenberg** [comment]
Potential change made above, @arouinfar @Matthew-Moore240 can you please confirm?

**Comment by arouinfar** [comment]
Looks good, thanks @jessegreenberg!
