### ISSUE TITLE
Minor grammatical changes

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#202]
When updating the description doc, I noticed two small grammatical issues. These requests are not a priority for interviews.

- [x] Equilibrium temperature statement: remove the comma between the qualitative and quantitative temperatures. 
  * Example from master: Surface temperature stable and historically moderate, at 13.6 degrees Celsius.
  * Desired statement: Surface temperature stable and historically moderate at 13.6 degrees Celsius.
- [x] Cloud checkbox responsive descriptions: for consistency, use -ing verbs and change reflected/reaches > reflecting/reaching.
  * Example from master 1: Cloud {{added to}} sky. {{Some sunlight **reflected** back to space.}}  
  *  Desired statement 1: Cloud {{added to}} sky. {{Some sunlight **reflecting** back to space.}}  
  * Example from master 2: Cloud {{removed from}} sky. {{All sunlight **reaches** surface.}}
  * Desired statement 2: Cloud {{removed from}} sky. {{All sunlight **reaching** surface.}}

**Comment by jbphet** [comment]
These changes have been made, please verify them on master or on the dev version that I plan to put out within the hour.

**Comment by arouinfar** [comment]
Thanks @jbphet, this all looks good.
