### ISSUE TITLE
Add Interactive Highlights to the sim

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#205]
In one of the recent accessibility tests, feedback indicated that hover styles are not sufficient for accessibility with combinations of zoom. We think interactive highlights would greatly help with this. Lets enable it and see if it helps!

**Comment by jessegreenberg** [comment]
Interactive Highlights have been enabled in this sim, and they can be enabled in the Preferences dialog. @arouinfar can you please review and confirm the feature is working as expected?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! The interactive highlights look great in master.

**Comment by jbphet** [comment]
Closing based on @arouinfar's feedback.
