### ISSUE TITLE
Increase size of greenhouse gas concentration slider thumb

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#206]
During recent accessibility testing, some users reported issues with the size of the slider thumb.

Dragon NaturallySpeaking with Chrome
> Even on the most detailed setting of MouseGrid, I was not able to activate the slider so I would definitely recommend increasing the area to click to make this easier for someone to click on.

OS Magnification with Chrome
> "Greenhouse gas concentration" slider control button is small for me even with higher magnification. I would prefer a little bit larger button.

The slider thumb does look a bit small. Its current dimensions are (20, 10). Let's increase that to (26, 13).
<img width="250" alt="image" src="https://user-images.githubusercontent.com/8419308/188973367-ae9366f6-d505-40f5-807d-ee1f8ee2297c.png"> <img width="250" alt="image" src="https://user-images.githubusercontent.com/8419308/188973296-0fb2a0b7-b06b-4b57-b351-dd782cdd446a.png">

**Comment by jbphet** [comment]
Done.

@arouinfar - Based on the comments that motivated this change, should we also consider enlarging the slider thumbs on the Layer Model screen (which hasn't had any accessibility testing yet)?

**Comment by arouinfar** [comment]
Excellent point, @jbphet. I'd forgotten about the sliders on the Layer Model screen. Let's apply the change to all slider thumbs.

**Comment by jbphet** [comment]
@arouinfar - This is now done on master.  Please have a look and close this if it looks decent.  Please note that I had to make the slider tickmarks larger on the Layer Model screen sliders so that the larger thumb wouldn't obscure them.

**Comment by jbphet** [comment]
We reviewed the larger thumbs and related changes in today's design meeting, and the group was good with it.  Closing.
