### ISSUE TITLE
Absorbing Layers NumberPicker is too small

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#207]
Self-assigning to suggest an alternative size.

**Comment by arouinfar** [comment]
Here's a mockup of some alternative sizes:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/8419308/191339895-c5057a16-1744-44f3-85ff-dd711e094f37.png">

**Comment by jbphet** [comment]
The design team just took a took at this, and decided that we should go with 30%.

**Comment by jbphet** [comment]
Done.  @arouinfar - Would you like to check it on master and see if it's what we're after?

**Comment by arouinfar** [comment]
Thanks @jbphet! The changes look great.

Here's a before and after (also includes the changes in #206)
<img width="266" alt="image" src="https://user-images.githubusercontent.com/8419308/192005117-b727c395-1c19-40d0-a44b-a664c556f04f.png"> <img width="269" alt="image" src="https://user-images.githubusercontent.com/8419308/192005056-188bd542-c3d8-4bd5-83bc-e2500889cbcc.png">
