### ISSUE TITLE
Make Celsius the default unit

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#208]
Celsius is a more naturally understood unit than Kelvin, and in recent interviews, users made a point to switch the units to *C before exploring.  In today's design meeting we decided to proceed with using Celsius as the default unit for all screens.

Kelvin was the default unit because it is necessary when using the equation related to blackbody radiation and radiative balance. However, there are other primary learning goals that aren't tied to Kelvin, so the interpretability of the temperature is also important.

We considered swapping the order of the radio buttons and ListBox items to C > K > F, but we like keeping C in proximity to both K and F, so we are sticking with K > C > F.

@jbphet please update the default units to Celsius.

**Comment by jbphet** [comment]
Done, closing.
