### ISSUE TITLE
Should dates be translatable?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#21]
@jbphet and I were working on the concentration control panel and were wondering if dates needed to be translatable. They are numerical values, but maybe there are different representations for dates in other languages. "Ice Age" will definitely need to be translatable.

![image](https://user-images.githubusercontent.com/6396244/114747349-be2afc80-9d1e-11eb-8d8f-4a89fdddbf8b.png)

@arouinfar what do you think?

**Comment by arouinfar** [comment]
I wouldn't make the numeric dates translatable. Very few countries use a non-Gregorian calendar, and there isn't necessarily a 1:1 mapping of years. For example, the year 2020 lines up with 1398-1399 in the Iranian calendar (new year starts on the vernal equinox).

**Comment by jessegreenberg** [comment]
Thanks, I added a comment to that effect and they are not translatable.
