### ISSUE TITLE
Update help text for Show Surface Temperature checkbox

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#211]
During a screen reader interview, one participant interpreted the help text, "Surface glows to indicate temperature." as being only applicable to visual users. We originally chose to reference the surface glow because students may hear their classmates or teachers reference the glow.  However, there are other representations in the simulation we chose not to describe the appearance of, such as the Energy Balance.

Let's update the help text to: 
Describe temperature on a scale.

**Comment by jbphet** [comment]
Done, closing.
