### ISSUE TITLE
Rename "Explore Mode" to "Experiment Mode"

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#212]
Based on the screen reader interviews, we want to improve the experience of switching between the two experimentation modes and provide better scaffolding around the experience.

@Matthew-Moore240 and I discussed, and decided to make these changes:
- [x] Rename "Explore Mode" to "Experiment Mode"
- [x] Update the Play Area paragraph in the Scene Summary. Changes were made to 2nd and 3rd sentences:
     > The Play Area is an observation window showing a scene extending from the surface of the Earth to outer space. Experiment with the greenhouse gas concentration or explore and compare historical time periods. It also has controls to add a cloud and measure the energy balance.
- [x] Update the Experiment Mode RadioButtonGroup help text -- replace "and compare" with "to compare"
     > Explore a wide range of concentrations from none to lots or zoom in to compare historical time periods.

**Comment by jbphet** [comment]
I've made the changes described above.  Because I thought it made sense, I also change the string key `exploreModeHelpText` to `experimentModeHelpText`.  The wording for that one is "Explore a wide range of concentrations from none to lots or zoom in and compare historical time periods."  Are you okay with that wording or does it need an update as well?

**Comment by arouinfar** [comment]
Thanks @jbphet, good catch on the string key. Everything looks good in master.

>  The wording for that one is "Explore a wide range of concentrations from none to lots or zoom in and compare historical time periods." Are you okay with that wording or does it need an update as well?

We decided to leave this one "explore", so no edits needed there.
