### ISSUE TITLE
Balance volume levels for the sounds

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#218]
One of the steps in the sound design process is to balance the sounds once all - or at least most - of them are in place.  We've reached the point where it is time to do this.

I've published a dev version that we can use as a baseline, see https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.15/phet/greenhouse-effect_en_phet.html.

@Ashton-Morris and I discussed this over Zoom, and he is going to reivew the dev version and write up recommendations about how to adjust the volume levels in this issue, then assign it back to me.

**Comment by Ashton-Morris** [comment]
I have some suggestions. 

- Start sunlight can be turned down 10% 
- Energy balance net could be turned up 15% 
- Energy Flux IR (Up Red)  can be turned down 20% 

@jbphet  I think the **photon levels** compared to what the temperature sounds are sound pretty good to me, but you have used it for more time and mentioned them feeling too loud after a time. Would you like to turn them down to your preferred level and I’ll listen to it after?

**Comment by Ashton-Morris** [comment]
@jbphet I think it sounds good!

**Comment by jbphet** [comment]
This has been reviewed by several members of the team and approved.  Closing.
