### ISSUE TITLE
Concentration readout for time periods should be accurate

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#219]
Looks like 2020 data appears, but 1950, 1750, and Ice Age data needs to be added. This should be done before publishing a prototype in #220. Self-assigning to confirm data.

<img width="273" alt="image" src="https://user-images.githubusercontent.com/8419308/196786412-979c325d-8915-43aa-b259-905c91825c1c.png">

**Comment by arouinfar** [comment]
@jbphet I added the data for the greenhouse gas concentrations to the [design doc](https://docs.google.com/document/d/1rsAHW3hP58FaXbRctqI_ovuvL6CKbCVGlh8Cf3ralpw/edit#heading=h.ofraczijzo4w). Over to you to update the readouts for each time period.

**Comment by jbphet** [comment]
I've added in the data that @arouinfar supplied, and we reviewed it in the context of the sim in this week's design meeting, and here are the follow ups:

- [ ] The position of the data shouldn't shift when going to different dates (there is currently a big jump for the Ice Age date due to the narrow string for H2O). @jbphet will follow up on this.
- [ ] Can we just get rid of the H2O indication?  We have a number of questions and concerns about it.  @jbphet will take it out for now, and @arouinfar will follow up with some research to make sure we're good with this

**Comment by jbphet** [comment]
@arouinfar - The relative humidity portion has been removed.  I'm assigning this to you for follow-up on whether we're good to go with that change.

**Comment by jbphet** [comment]
In a recent design meeting, it was brought up that using decimal values of ppm, as we do now, is unusual.  It is more common to use ppb.  Should we do that here?  If we do, should we have a little info dialog like we do in other sims (e.g. Fourier).

Screenshot of current indicator:

![image](https://user-images.githubusercontent.com/3082831/204900574-00c12913-6d43-45f7-83e9-d42c0f60e9e2.png)

**Comment by jbphet** [comment]
@arouinfar said during today's design meeting to go ahead with ppb for the upcoming prototype release.  We won't worry about having an info dialog for now and will follow up on whether it's needed for the full release later.

**Comment by jbphet** [comment]
I've changed the designated compounds to use ppb.  Unassigning myself, @arouinfar can follow up on whether we want to add an info dialog.

**Comment by arouinfar** [comment]
Thanks @jbphet. The readout looks good in master.

Mark provided this source to explain water vapor's relationship to the greenhouse effect:
https://climate.nasa.gov/ask-nasa-climate/3143/steamy-relationships-how-atmospheric-water-vapor-amplifies-earths-greenhouse-effect/

We decided to remove the humidity readout for a few reasons:
* Water vapor is the most abundant greenhouse gas in the atmosphere (likely the reason it was included in Java), but it is not the driver of climate change. As the global temperature rises, the atmosphere is able to hold more water vapor, so displaying the same relative humidity at all time periods is odd.
* In Java, we listed the water vapor as 70% relative humidity. This number seems arbitrary. Humidity widely varies across locations and seasons. Global average humidity data isn't tracked in the same way as other greenhouse gases, for example, https://www.co2levels.org/

I've added a note to the Teacher Tips issue, so we can close this issue.

**Comment by Nancy-Salpepi** [comment]
@arouinfar I know this issue is closed, but I would like to vote for an info button in the full release. In my experience, HS students tend to look at numbers and not units (although they should). They just think biggest number = highest concentration (which is incorrect in this case).

**Comment by jbphet** [comment]
Reopening based on what @Nancy-Salpepi said in the comment just above.  @arouinfar - does her comment change your thinking on this, or do you still feel like the teacher tips update will cover it?

**Comment by pixelzoom** [comment]
The open questions is whether an Info dialog is needed here. @arouinfar?
