### ISSUE TITLE
Add help text

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#22]
In a review meeting today, the design team discussed adding help text to the sim.  Some of this text is specified in the description design doc at https://docs.google.com/document/d/1HWVypTlzM5oSUhhcv7gPdx1sSCs0j-xgIF3lbSgzwAQ/edit?usp=sharing, but some of it isn't there yet.  At first the thinking was that we should add the parts that have been defined thus far, but then @jessegreenberg pointed out that the `helpText` part of the PDOM API wasn't yet fully functional.

This issue is to remind us to add the help text once the API to do so is fully supported.  The blocking issue - the one under which the API should be completed - is https://github.com/phetsims/scenery/issues/867.

**Comment by jessegreenberg** [comment]
I discussed this with @zepumph - While there is still some work to be done in https://github.com/phetsims/scenery/issues/867, `helpText` is generally in good shape to be used in greenhouse-effect. During a meeting 4/28/21 @jbphet and I tried it out for a usage in the sim and it is working well. So we are ready to keep adding helpText in this sim, removing `deferred` label.

**Comment by jbphet** [comment]
I think this issue can safely be closed.  @jessegreenberg and I have been using the API to add the help text, and it is working fine.  Closing.
