### ISSUE TITLE
Use `_private` in state schemas to prevent internal information from appearing in phet-io

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#226]
In https://github.com/phetsims/tandem/issues/282#issuecomment-1324244418 @pixelzoom noted that the `_private` keyword and the functionality that goes with it is not being used in Greenhouse Effect.  I asked about how to use it, and @samreid said:

> Does Greenhouse PhET-iO state data have values that are more of an "implementation detail" than a "user-facing feature"? If so, those values should be nested under _private.

Because I don't have much insight into how we anticipate that phet-io customers will use state information like this, it's hard for me to make an informed decision on what should be considered an "implementation detail" versus a "user-facing feature".  To me, almost all of it seems like implementation details but, again, I don't know what we expect customers to do with this.

@arouinfar - How should we approach this?  Can you offer any general guidance that would help?  Should we set up a meeting between you and me?  Do you want to review a dev release in Studio and give me specifics on what should be hidden and what should be available?

**Comment by jbphet** [comment]
I discussed this with @zepumph today, and the `_private` keyword is no longer used.  Instead, the recommendation is to use underscores in front of elements in the state, e.g:

```js

      stateSchema: {
        sunWaveSource: EMWaveSource.EMWaveSourceIO,
        groundWaveSource: EMWaveSource.EMWaveSourceIO,
        _cloudReflectedWavesMap: MapIO( ReferenceIO( Wave.WaveIO ), ReferenceIO( Wave.WaveIO ) ),
        _glacierReflectedWavesMap: MapIO( ReferenceIO( Wave.WaveIO ), ReferenceIO( Wave.WaveIO ) ),
        ...LayersModel.STATE_SCHEMA
      }

```

To address this issue, I should go through the existing state schemas and add underscores for the things that I think phet-io users will not need to access, and keep this in mind for all newly defined state schemas.

**Comment by jbphet** [comment]
I discussed this with @samreid, and he and I went through the Natural Selection sim to get ideas of the precedents for what should be hidden using underscores.  I then tried to apply that heuristic to underscoring certain fields in the state schemas in this sim.

@arouinfar - Please take a look at the commit above and the studio tree and let me know if you have any objections to what I've chosen to hide from Studio using the underscores.  Also, feel free to suggest other items if you feel something should be underscored that currently is not.

**Comment by arouinfar** [comment]
The changes look good to me @jbphet. I didn't notice anything else that needs underscoring, so I'll close this issue.
