### ISSUE TITLE
Energy Balance indicator can't show full range on the Layer Model screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#228]
In the current implementation, a situation can be created where a bunch of energy was trapped below the layers, then the layers are either removed or have their absorbance quickly reduced, and there will be a surge of energy leaving the atmosphere to exceeds the range of the energy balance indicator.  Screenshot below.  I'm okay with this, since it's a temporary condition, but I should I should check in with the design team about it.

![image](https://user-images.githubusercontent.com/3082831/206018741-66e93e5f-ea43-4972-a0bb-8083621eb68f.png)

@arouinfar - What do think - do we need to address this, or can it be left as is?

**Comment by jbphet** [comment]
I suppose at the very least we should clip the indicators below the labels, as we do with the flux meter.

**Comment by jbphet** [comment]
This is implemented, screenshot below.  @arouinfar - please review the version on master and close this issue if it looks good to you.

![image](https://user-images.githubusercontent.com/3082831/207975229-6f96599e-0404-4908-adfc-22910d396555.png)

**Comment by arouinfar** [comment]
Looks good in master, thanks @jbphet.
