### ISSUE TITLE
Review the sound design (design team)

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#229]
In #222, the a11y team did a review of the sound design.  The suggestions from that review have been folded in, so it's time to have the rest of the design team review it.  Please test the sim, pay attention to the sounds that are produced, and log any bugs, concerns, or suggestions in this issue.  A dev version for this purpose can be found at  https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.17/phet/greenhouse-effect_en_phet.html.

**Comment by arouinfar** [comment]
@jbphet the sim is sounding great! The only thing that feels a bit off to me is the Surface Albedo slider. If I deliberately move the thumb tick-by-tick, the sound sometimes fails to play for one or two ticks. It doesn't happen at any one particular tick mark, but I consistently observe a missing sound at least once along the path. I didn't notice this happening on the other two sliders on the Layer Model screen.

**Comment by arouinfar** [comment]
Some interview participants had an issue with the volume of the temperature soundscape being too loud and interfering with their ability to clearly hear the screen reader. I tested in VO, and the sound balancing seems much better now. I can clearly hear the temperature sound while using the screen reader, but the screen reader itself is still prominent.

**Comment by jbphet** [comment]
@arouinfar - I've implemented what I believe to be a fix for the sound generation problem in the albedo slider.  Please test it out on master and, if the behavior now seems correct and you don't feel like there is anything else to address on the sound design, feel free to close this issue.
