### ISSUE TITLE
Concentrate photon reflection from are where glacier resides during ice age

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#235]
On the Waves screen, when the glacier is present, the visible wave reflects from there.  On the Photons screen, the photons reflect evenly off the surface in every setting, including the ice age.  In my opinion this looks odd.  I think I should add code to preferentially reflect photons from the glacier when is is present.

**Comment by jbphet** [comment]
This is now implemented on master.  @arouinfar - Please have a look and close if it looks good to you.

**Comment by arouinfar** [comment]
This looks great @jbphet! Thanks, closing.
