### ISSUE TITLE
Width of wave coming from atmosphere layer can be greater that what is going in

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#236]
While doing some testing prior to prototype publication (see #220), I noticed that it's pretty easy to create a situation where the intensity of the wave that is coming out of an atmosphere layer is greater than the intensity of the wave that is intersecting with that layer.  While there could be some situations where this would make sense, like when the atmosphere previously had a lot of energy and is now cooling off, that's not what was going on when I was seeing this.

Here is a screenshot.  One wave is coming from the ground at the lower left and another is coming from that atmosphere where the first one intersects with a layer.  The width of the emitted wave at its origin is significantly bigger than the width of the incoming wave.

![image](https://user-images.githubusercontent.com/3082831/209000095-f1b6e299-7052-438b-99ab-ae4bb7d217b7.png)

I suspect this is somehow related to the work done for wave intensity propagation in https://github.com/phetsims/greenhouse-effect/issues/84.

**Comment by jbphet** [comment]
A fix for this is now implemented on master.  I feel like the new behavior is significantly better, because it's much easier to see how more greenhouse gases in the atmosphere "shave off" more of the IR as it moves through the atmosphere.

@arouinfar - Can you take a look and make sure you're good with this change?  High priority on this, since I'm hoping to publish a prototype RC tomorrow.

**Comment by arouinfar** [comment]
@jbphet looks good in master.

The worst I can do is this, but it occurs very briefly after a large spike in greenhouse gas concentration. I don't think I would have noticed unless I was looking for it.
<img width="184" alt="image" src="https://user-images.githubusercontent.com/8419308/209054655-16f28ebb-ecc5-4a81-87fe-104176729001.png">
