### ISSUE TITLE
Sound from Waves screen heard on other screens

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#238]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 13.0.1

**Browser**
safari 16.1

**Problem description**
For https://github.com/phetsims/qa/issues/871, if the Waves Screen is playing, I can hear a humming sound when I switch to the other 2 screens. 

**Steps to reproduce**
1. On the Waves Screen, press Start Sunlight button
2. Wait until the sunlight hits the surface and then switch to either the Photons or Layer Model screen

**Visuals**

https://user-images.githubusercontent.com/87318828/211035430-491a7bd9-c427-425d-9dc4-0c94cc64854c.MOV

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
Language: en-US
Window: 1399x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
This issue is specific to the Waves screen. If I start on a different screen and then switch over, I don't hear any sound.

**Comment by amanda-phet** [comment]
I think I isolated it to the "greenhouse gas concentration" sound on the Waves screen, if that helps.

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi @amanda-phet.

@jbphet the sound for the redirected IR is leaking through to other screens. As @amanda-phet points out, it's easiest to hear if you maximize the greenhouse gas concentration. This would be good to fix for the prototype.

**Comment by jbphet** [comment]
I fixed this by associating the main view node with the loop for this sound.  This change was also pushed to the 1.1 branch.

**Comment by Nancy-Salpepi** [comment]
This looks fixed in rc.2. Closing.
