### ISSUE TITLE
In arrow cut off in Energy Graph

### ISSUE THREAD

**Issue by marlitas** [phetsims/greenhouse-effect#240]
**Test device**
Mac

**Operating System**
OS 13.02

**Browser**
Chrome

**Problem description**
https://github.com/phetsims/qa/issues/871
In arrow in Energy Graph is cut off.

**Steps to reproduce**
1. Go to the second screen
2. Start light
3. Open energy graph and look at left side of In arrow.

**Visuals**
![Screenshot 2023-01-06 at 9 08 25 AM](https://user-images.githubusercontent.com/42476338/211062534-5afc671b-7f33-4735-9241-50c7789a619f.png)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1920x944
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by Nancy-Salpepi** [comment]
This is seen on the Waves screen as well

**Comment by marlitas** [comment]
Also seen in Layer Model screen.

**Comment by jbphet** [comment]
This is happening because there is a clipping area around the bar chart, and it is based on the initial size of the bar chart, and the arrowheads extend just a little bit beyond that initial size in the x direction.  I've dilated the clip area to compensate, and it appears to work well.  This fix has been committed on both the master and 1.1 branches.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2. Closing.
