### ISSUE TITLE
Pausing before starting sunlight looks odd

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#241]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/871
You can pause the sim before starting sunlight. When you start the sunlight it makes the starting up sound and slowly brightens, but nothing else happens. This isn't necessarily wrong, but it does look very odd. It may be worth taking a second look at this use case
**Steps to reproduce**
1. Pause the sim in the time control area
2. Press Start Sunlight

**Visuals**
![pausedstart](https://user-images.githubusercontent.com/41024075/211064759-d8190005-abe1-4c9a-a047-8989531e652c.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
Also strange that you can pause and still press the step forward button before the sunlight starts, but nothing happens.

**Comment by jbphet** [comment]
@arouinfar - Here is one suggestion on how to address this: Disable the pause functionality when the sunlight hasn't been started.

You may have other thoughts.  Assigning to you for evaluation.

**Comment by arouinfar** [comment]
Thanks @KatieWoe @marlitas. 

>  Here is one suggestion on how to address this: Disable the pause functionality when the sunlight hasn't been started.

@jbphet that seems like a reasonable change to make, but we should evaluate how this would interact with description. We already have a variety of context responses that inform users of the possible interactions between Start Sunlight and the PlayPauseButton. For example:
* Sunlight started, sim paused. (Pressing Start Sunglight when sim is paused.)
* Sim paused, sunlight not started. (Pressing pause when sunlight hasn't started.)
* Turn on sunlight to play sim. (Pressing play when sunlight hasn't started.)

I am fine leaving this as-is for the prototype and addressing in the next release, but I'll leave it up to @jbphet.

**Comment by samreid** [comment]
@jbphet and I reviewed this behavior, and we both recommend that we wire up the enabled property of the play/pause/step buttons to whether the sunlight is showing.  We believe this will be a better user experience, and should not be difficult to implement.  We will create a side issue about updating the description accordingly.

**Comment by Nancy-Salpepi** [comment]
In rc.2, the  play/pause/step buttons are disabled until the Start Sunlight button is pressed.  Closing.
