### ISSUE TITLE
Keyboard pause or play action different for Mac

### ISSUE THREAD

**Issue by marlitas** [phetsims/greenhouse-effect#243]
**Test device**
Mac

**Operating System**
OS 13.01

**Browser**
Chrome

**Problem description**
https://github.com/phetsims/qa/issues/871
The keyboard command to pause or play action is opt + K for mac, not alt + K

**Visuals**

![Screenshot 2023-01-06 at 9 32 20 AM](https://user-images.githubusercontent.com/42476338/211066961-934128d1-5cf4-44a9-8a84-78f6001806f6.png)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1920x944
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment]
@jessegreenberg was asking about this on Slack a few days ago.  Can you update us?

**Comment by jessegreenberg** [comment]
Sorry, I wasn't able to get to it, but started a new issue here: https://github.com/phetsims/scenery-phet/issues/793.

**Comment by samreid** [comment]
I added a commit in https://github.com/phetsims/scenery-phet/issues/793#issuecomment-1374609735, it is ready for review.

**Comment by arouinfar** [comment]
Thanks, everyone! I think this is a nice change, but not necessary for the prototype. If https://github.com/phetsims/scenery-phet/issues/793 is wrapped up before this sim is ready for next steps, great. Otherwise, we can pick up the change in the next publication cycle.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/scenery-phet/issues/793 was wrapped up if you would like to cherry-pick commits from that issue.

**Comment by jbphet** [comment]
I've moved what I think are the minimal commits to my release branch and its dependencies, so this should now be fixed in 1.1.

**Comment by Nancy-Salpepi** [comment]
On a mac 'alt' has been replaced with 'option' in the keyboard shortcuts dialog. 
(mac also doesn't have `page up`, `page down`, `home` and `end` keys....but mac users should know what to press instead)

Closing.
