### ISSUE TITLE
No remote step forward in keyboard nav

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#244]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/871
The keyboard nav dialog has an option to play/pause the sim with alt + k. However, on the second and third screen there is also a step forward button. In the past there have been corresponding keyboard inputs (alt + l I belive) but that is not the case here. Should such an input be added?

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

The only sim that I know of that uses alt+L is Molecules and Light:
![image](https://user-images.githubusercontent.com/8419308/211114341-3d19fa4d-4b1b-4e4e-a962-025f5a372408.png)

Alt+L is is not a hot key for step forward, rather it steps the sim forward in larger-than-normal amounts. Think of it as the equivalent of pg up/down for sliders.

There is no specific need to step the model in larger steps, so I'll go ahead and close this issue.
