### ISSUE TITLE
Recommend making touch area larger for flux meter

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/greenhouse-effect#245]
<b>Test Device</b>

iPad 

  <b>Operating System</b>

iOS16

  <b>Browser</b>

Safari

  <b>Problem Description</b>

For https://github.com/phetsims/qa/issues/871. I can't confirm using `showPointerAreas` but my guess is the touch area for the flux meter isn't dilated. It sometimes took me a couple tries to grab it, so I recommend making it a little larger (mainly the height could be larger). 

  <b>Steps to Reproduce</b>

Open sim in English
Go to Layer Model screen
Show flux meter
Drag flux meter to a new position

  <b>Visuals</b>

![image](https://user-images.githubusercontent.com/7852916/211070245-3cbcd1a1-0734-4b32-8170-06177461b33b.png)

  <details>
  <summary><b>Troubleshooting Information</b></summary>

  blah

  </details>

Steps to reproduce:

**Comment by arouinfar** [comment]
Thanks for the suggestion @amanda-phet!

@jbphet can you vertically dilate the touch area on the flux meter probe?  Something along the lines of what was done for the slider thumbs would work.

**Comment by jbphet** [comment]
I've added some dilation in the Y direction on both the 1.1 and master branches.  @arouinfar - Does this look good to you?  You can try it out on master if you prefer.

![image](https://user-images.githubusercontent.com/3082831/211421130-887a5aae-2f0d-4ab3-b0fa-b30312fad0fc.png)

**Comment by arouinfar** [comment]
Thanks @jbphet! I tested it out on my phone and the flux meter probe was easy to grab.

**Comment by Nancy-Salpepi** [comment]
On the iPad, in rc.2 the flux meter probe was easy to grab on both the Photons and Layer Model screens. 
Closing.
