### ISSUE TITLE
Overlapping long strings

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#246]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/871
When strings are long they may overlap with other strings or buttons. On the second screen, the two checkboxes on the bottom of the screen will overlap with the pause/play button slightly. On the third screen all the strings on the bottom of the screen overlap or go off screen.

**Steps to reproduce**
1. Use the parameter `?stringTest=long`
2. Observe the second and third screen

**Visuals**
![bigoverlap](https://user-images.githubusercontent.com/41024075/211070764-3217105b-121f-4a8b-b975-be36f3fc908a.png)
![longoverlap](https://user-images.githubusercontent.com/41024075/211070765-7609eccb-be2c-4e9c-90a8-07df46778067.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html?stringTest=long
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by marlitas** [comment]
There is also overlap with the Thermometer checkbox with `stringTest=double`
![Screenshot 2023-01-06 at 10 39 49 AM](https://user-images.githubusercontent.com/42476338/211077955-634e347b-54af-44b8-9da0-535c1c840944.png)

**Comment by Nancy-Salpepi** [comment]
I still see the overlapping reporting by @KatieWoe with stringTest=long in rc.2, but in master, things look good.

**Comment by arouinfar** [comment]
@jbphet sounds like you may have missed https://github.com/phetsims/greenhouse-effect/commit/95fa513e8911410b72c4945579f62cfda054ae63 when cherry-picking.

**Comment by jbphet** [comment]
Good thing we check these issues.  As @arouinfar noted above, I missed moving the fix from the master branch to the 1.1 release branch.  I've done so now.

**Comment by Nancy-Salpepi** [comment]
In rc.3, on the Photons screen the text at the bottom of the concentration panel is cut off slightly on the right side with stingTest=long.

<img width="280" alt="Screenshot 2023-01-30 at 7 57 57 AM" src="https://user-images.githubusercontent.com/87318828/215485167-37078053-d363-4feb-8cf0-950cb9499e7e.png">

**Comment by arouinfar** [comment]
@jbphet looks like this is the only issue that remains. I do not think this is a serious enough issue to send Greenhouse back through QA. If we can verify the change ourselves, great. If not, let's wait until full publication.

This is a case where `stringTest=long` isn't particularly accurate. The only portion of these strings that is actually translatable is the unit, which is rarely translated. I translated "parts per million" into ~40 different locales and most are shorter or similar to English in terms of character count. This was the worst-case scenario:

<img width="204" alt="image" src="https://user-images.githubusercontent.com/8419308/215519983-a280857f-971f-48c3-86f9-f4bcd60a45df.png">

If a translator runs into an issue with the length of the strings, they can instead use the unit's abbreviation.

**Comment by jbphet** [comment]
This last observation about the concentration readout strings has been fixed on master and propagated to the 1.1 branch.  Here is a screenshot from RC.4:

![image](https://user-images.githubusercontent.com/3082831/215914489-81667526-d8cc-4368-9854-7951ea440276.png)

**Comment by arouinfar** [comment]
@jbphet I reviewed in rc.4 and the strings all look appropriately bounded.
