### ISSUE TITLE
Focus highlight outside dev bounds

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/greenhouse-effect#247]
<b>Test Device</b>

iPad 

  <b>Operating System</b>

iOS16

  <b>Browser</b>

Safari

  <b>Problem Description</b>

For https://github.com/phetsims/qa/issues/871. This probably doesn't need to change, but I noticed this when using the iPad with focus highlights turned on and confirmed here using `dev`. The focus highlight extends beyond the width of the iPad. 

  <b>Steps to Reproduce</b>

Turn on focus highlights
Go to Layer Model screen
Touch the temperature units

  <b>Visuals</b>

![image](https://user-images.githubusercontent.com/7852916/211070615-a36e10b4-faf5-4a8f-becf-aa4d8379f3fa.png)

  <details>
  <summary><b>Troubleshooting Information</b></summary>

  blah

  </details>

Steps to reproduce:

**Comment by jbphet** [comment]
Good eye.  I reviewed this with @samreid and @arouinfar and we decided to simply move the collection of controls a bit to the right, so I'll do that.

**Comment by jbphet** [comment]
I just tested this and it is no longer a problem.  I believe it was fixed by some work that was done to make the spacing between screen elements and the dev bounds more consistent, see https://github.com/phetsims/greenhouse-effect/commit/4874259a851fb99cf1b91ee16e214d0554490b15.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2
Closing
