### ISSUE TITLE
Flux Meter overlaps Energy Balance / Flux Meter checkbox panel

### ISSUE THREAD

**Issue by marlitas** [phetsims/greenhouse-effect#248]
**Test device**
Mac

**Operating System**
OS 13.01

**Browser**
Chrome

**Problem description**
https://github.com/phetsims/qa/issues/871
The flux meter bar stroke overlaps with the Energy Balance/ Flux Meter panel when StringTest=double, and the meter is dragged all the way down. This does not happen with the other string test types.

**Steps to reproduce**
1. Open the photon screen with query parameter `stringTest=double`
2. Start sunlight
3. Turn on Flux Meter
4. Drag meter all the way down

**Visuals**
![Screenshot 2023-01-06 at 9 57 21 AM](https://user-images.githubusercontent.com/42476338/211071272-d088ebf3-d5bb-4722-af1d-90489533300d.png)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬:‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html?stringTest=double
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1920x944
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by jbphet** [comment]
I've adjusted the range over which the flux sensor can be moved to handle this.

**Comment by Nancy-Salpepi** [comment]
In rc.2, it looks like there is still a slight overlap. 
The overlap is much easier to see in the Layers Screen
<img width="456" alt="Screenshot 2023-01-22 at 8 35 11 AM" src="https://user-images.githubusercontent.com/87318828/213918802-be0a37ff-fb27-4815-863e-961922d9e8ea.png">

**Comment by arouinfar** [comment]
Good eye @Nancy-Salpepi.

I don't think we should move the sensor much further up because the data is more dynamic close to the surface. I'm okay with leaving this as-is, but I'll leave the final decision up to you @jbphet.

**Comment by jbphet** [comment]
This seems pretty minor, and since @arouinfar says we shouldn't move the sensor up much, let's just leave it as is.  Closing.
