### ISSUE TITLE
Flux Meter stroke extends past dark overlay before sunlight starts

### ISSUE THREAD

**Issue by marlitas** [phetsims/greenhouse-effect#250]
**Test device**
Mac

**Operating System**
OS 13.01

**Browser**
Chrome

**Problem description**
https://github.com/phetsims/qa/issues/871
Flux Meter orange stroke extends past dark overlay before sunlight has started.

**Steps to reproduce**
1. Open Layer Model screen
2. Turn on flux meter
3. Drag all the way up

**Visuals**
![Screenshot 2023-01-06 at 10 17 48 AM](https://user-images.githubusercontent.com/42476338/211074290-d4ecce55-cbf2-47d4-8f69-d5e2c150004a.png)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html?
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1920x944
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by Nancy-Salpepi** [comment]
This looks fixed in rc.2. Closing

<img width="577" alt="Screenshot 2023-01-22 at 8 27 11 AM" src="https://user-images.githubusercontent.com/87318828/213918305-365ee489-7a0c-404d-9ee4-00292921dc12.png">

**Comment by Nancy-Salpepi** [comment]
Noticed that the interactive highlight for the flux meter extends past the observation window. Is that OK?
<img width="606" alt="Screenshot 2023-01-23 at 8 28 45 AM" src="https://user-images.githubusercontent.com/87318828/214051517-d2c8800e-294e-4d5d-a811-b0b985cea1f0.png">

**Comment by arouinfar** [comment]
Thanks for checking @Nancy-Salpepi. The probe moves behind the Energy Balance panel, but focus/interactive highlights are always layered on top, which creates situations like this:
![Screen Shot 2023-01-23 at 3 17 29 PM](https://user-images.githubusercontent.com/8419308/214162603-b51481ef-35a6-4eba-a975-83a48ba6a3dd.png)

I think the Z-order of the probe is correct. It should not interfere with reading the Energy Balance data, so it goes behind the panel. However, the probe is rather large so most of it remains unobscured. This looks a little weird when it has focus, but I think that's okay.
