### ISSUE TITLE
Surface temperature layer doesn't exactly match artwork below

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#251]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macoS 13.0.1

**Browser**
safari 16.1

**Problem description**
For https://github.com/phetsims/qa/issues/871, the surface temperature layer doesn't exactly match the scene below--leaving lighter areas in a few places where the surface and sky meet. 

**Visuals**
<img width="858" alt="Screenshot 2023-01-06 at 1 22 44 PM" src="https://user-images.githubusercontent.com/87318828/211075310-0a799e8d-6161-49d3-9ae0-ba6a48337684.png">

<img width="858" alt="Screenshot 2023-01-06 at 1 22 07 PM" src="https://user-images.githubusercontent.com/87318828/211075339-ec945e48-bffb-4fb9-a426-438ccdf96a48.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html?
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
Language: en-US
Window: 1399x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jbphet** [comment]
I'm impressed that you noticed this!  @samreid, @arouinfar, and I just reviewed this, and we feel that it doesn't compromise the pedagogy at all, so if it can be fixed quickly it is worth it, otherwise it should be left as is.

**Comment by jbphet** [comment]
I've updated this such that the green from the background never peeks through.  This was, I think, the most noticeable issue.  However, this has caused the edge of the orange glow to be a little above the horizon in a couple of places.  These are generally less noticeable because they are often behind buildings and such.

@arouinfar - I've done as much as I can reasonably do on this.  From here we can either decide that it is acceptable or we could have @mariahmaephet modify the artwork.  I'll leave that up to you.

**Comment by arouinfar** [comment]
> However, this has caused the edge of the orange glow to be a little above the horizon in a couple of places. These are generally less noticeable because they are often behind buildings and such.

I agree. I reviewed with @jbphet and we decided that this version is preferable. In order to match things perfectly, we'd need to work with the graphic artist to update the assets. However, we don't think this cost would be worth the benefit.

**Comment by Nancy-Salpepi** [comment]
It looks much better in rc.2
There are still a couple of spots where I can see the lighter color in the Ice Age scene, not sure if they are worth the time. 

<img width="397" alt="Screenshot 2023-01-20 at 3 19 01 PM" src="https://user-images.githubusercontent.com/87318828/213798684-7e8c5a5b-824e-4b3a-9335-b5cf71a3722f.png">

<img width="397" alt="Screenshot 2023-01-20 at 3 26 32 PM" src="https://user-images.githubusercontent.com/87318828/213799454-ac1ed0c1-56c4-46a2-a40c-40f1c72d5bd5.png">


Feel free to close if you don't think it is worth fixing.

**Comment by arouinfar** [comment]
> Feel free to close if you don't think it is worth fixing.

I don't think it's worth fixing because getting a 100% perfect match requires updating the artwork. I do, however, appreciate your attention to detail @Nancy-Salpepi!
