### ISSUE TITLE
Screenshots missing photons

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#255]
**Test device**
MacBook Air (m1 chip) and Dell

**Operating System**
MacOS 13.1 and Win10

**Browser**
safari and FF

**Problem description**
For https://github.com/phetsims/qa/issues/871, the photons don't appear in screenshots 

**Visuals**
<img width="531" alt="Screenshot 2023-01-06 at 5 03 49 PM" src="https://user-images.githubusercontent.com/87318828/211107797-434647fb-ed13-40b6-a53b-01028d34bf7d.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
Language: en-US
Window: 1216x617
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
I was able to reproduce the problem on my MacBook Air M1 on Chrome.

**Comment by samreid** [comment]
We just need to pass in the canvasBounds like so:

<details>

```diff

Subject: [PATCH] Ignore invisible nodes in move forward/backward, see https://github.com/phetsims/sun/issues/814
---
Index: js/common/PhotonSprites.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/PhotonSprites.ts b/js/common/PhotonSprites.ts
--- a/js/common/PhotonSprites.ts	(revision c0fd52d298c3a6c9503247c2b107e1ee6490a740)
+++ b/js/common/PhotonSprites.ts	(date 1673477063918)
@@ -25,6 +25,7 @@
 import Range from '../../../dot/js/Range.js';
 import LayersModel from './model/LayersModel.js';
 import greenhouseEffect from '../greenhouseEffect.js';
+import Bounds2 from '../../../dot/js/Bounds2.js';
 
 // constants
 const TARGET_PHOTON_IMAGE_WIDTH = 17; // empirically determined to match the design
@@ -62,7 +63,8 @@
       sprites: [ visiblePhotonSprite, infraredPhotonSprite ],
       spriteInstances: spriteInstances,
       renderer: 'webgl',
-      pickable: false
+      pickable: false,
+      canvasBounds: new Bounds2( 0, 0, 500, 500 )
     } );
 
     // Calculate the scale that will be used to render the photon images.

```

</details>

Maybe @jbphet can help specify that dimension.

**Comment by samreid** [comment]
I used the same strategy for specifying the canvasBounds as used in WaveLandscapeObservationWindow and it appears to work well. I also tested by eroding it by 10px and it behaved as expected, so it seems well-fitted to the window.  Next I will commit it to the release branch as @jbphet has been doing for other issues.

**Comment by samreid** [comment]
OK I also pushed to the 1.1 branch.  @jbphet will you please review?

**Comment by jbphet** [comment]
Looks great, thanks @samreid!  I'll have QA verify this in the next round of testing.

**Comment by Nancy-Salpepi** [comment]
I see photons with mac + chrome/safari!
Closing.
