### ISSUE TITLE
Inconsistent outline around temperature values in combobox

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#256]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 13.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/871:
With interactive highlights off, when I move the mouse over the temperature units options in the combobox, I see a gray outline. The size around Kelvin is different from the others. 

<img width="190" alt="Screenshot 2023-01-07 at 8 19 23 AM" src="https://user-images.githubusercontent.com/87318828/211152697-37aee686-1cd1-47a0-9eab-f26fa85a7d03.png">

<img width="190" alt="Screenshot 2023-01-07 at 8 20 23 AM" src="https://user-images.githubusercontent.com/87318828/211152742-12af6e22-9d45-47c2-9622-c4bda0cd93fe.png">

Also I wasn't sure if that was the intended design or if it should be highlighted like this:

<img width="173" alt="Screenshot 2023-01-07 at 8 21 38 AM" src="https://user-images.githubusercontent.com/87318828/211152807-36f66e1c-9d62-49ef-93a5-6a1e0ff18253.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
Language: en-US
Window: 1216x617
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
The same inconsistency is seen when clicking on the arrow to expand the combobox. 

<img width="131" alt="Screenshot 2023-01-07 at 8 43 37 AM" src="https://user-images.githubusercontent.com/87318828/211153796-6f995d1d-1357-45fe-84dc-4fabb444c9e6.png">
<img width="120" alt="Screenshot 2023-01-07 at 8 44 07 AM" src="https://user-images.githubusercontent.com/87318828/211153820-24e80bc9-7b19-4828-83bb-978c6f0273c6.png">

**Comment by arouinfar** [comment]
Nice find @Nancy-Salpepi.

@jbphet is a nice pixel polish, but I don't think it's necessary for the prototype.

**Comment by jbphet** [comment]
I have added a fix on both master and the 1.1 branch.

**Comment by zepumph** [comment]
We have a good working solution for the branch, but after discussion with @jbphet, it would be better to use the nodes, once created, and set dynamically the min width of the number displays. I'll work on doing that for master, since I blocked that commit originally over in https://github.com/phetsims/sun/issues/797.

**Comment by zepumph** [comment]
Ok. I think this is what @jbphet decided on. I like it much more! Good work team. Thanks all.

over to @jbphet

**Comment by jbphet** [comment]
Looks good to me.  I enhanced the docs a bit, and tested out the behavior, and I think we're good to go.

I'm not going to propagate this to the 1.1 branch, since it would be a fair amount of work to update the dependences, and there would be no change to the behavior.  I'll have QA verify the behavior in the next RC.

**Comment by Nancy-Salpepi** [comment]
The gray outline is now the same for all temperature units. 
Closing.
