### ISSUE TITLE
Timing Controls section in dialog doesn't change in string tests

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#257]
**Test device**
Dell and Mac

**Operating System**
Win10/macOS 13.1

**Browser**
FireFox and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/871, for all string tests, the Timing Controls title and "pause or play action" in Keyboard Shortcuts dialog don't change. 

**Visuals**

<img width="423" alt="Screenshot 2023-01-09 at 9 00 06 AM" src="https://user-images.githubusercontent.com/87318828/211325540-1568fcd3-ca97-4963-8a01-899bc8857e27.png">
<img width="484" alt="Screenshot 2023-01-09 at 9 01 50 AM" src="https://user-images.githubusercontent.com/87318828/211325735-1038a818-cdf0-4cc5-bf04-3ca73a9e4a31.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬:‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html?stringTest=double
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1475x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jbphet** [comment]
@arouinfar - This is a common code issue, and I need to work with @jessegreenberg to potentially fix it.  I'm assuming that I should wait to hear from him before proceeding with the next prototype RC, please let me know if you disagree.

**Comment by jessegreenberg** [comment]
OK, commit to make these translatable done above.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! Let's incorporate these changes into the prototype @jbphet.

**Comment by jbphet** [comment]
I've incorporated the changes into the 1.1 release branch.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2. 
Closing.
