### ISSUE TITLE
Focus order of concentration box

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#258]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/871
The keyboard focus for Greenhouse Gas Concentration box on both the first and second screen have you focus first on the slider/time periods, then the scene change. This seems a bit backwards to me. It would make more sense to select a scene then make changes to it, rather than double back once you choose the scene.

**Visuals**
![focusorder](https://user-images.githubusercontent.com/41024075/211366498-42a156c6-00bc-445b-b467-712717ec4897.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.1.0-rc.1 2022-12-23 00:15:29 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks for the suggestion @KatieWoe. I agree that it can be a little awkward to shift+tab back to concentration control after switching experiment modes.

However, the focus order was selected to match the intended user flow. We want people to explore the greenhouse gas concentration slider before switching to the time period mode. If the experiment mode radio buttons came first, people would interact with those first, essentially skipping to the time period mode before exploring the slider.
