### ISSUE TITLE
Hook up EnergyBalancePanel to the model

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#26]
In https://github.com/phetsims/greenhouse-effect/commit/e3bd34c66a246d2f5b93c1f45ad9aff8c5bc73d5 the EnergyBalancePanel was added, but it currently uses Properties that are not part of the model. This issue is to hook it up once the data is made available . Assigning to @jbphet to do this as he works on the model, or reassign to me when it is ready.

**Comment by jbphet** [comment]
This is hooked up and working.  We should review its behavior at the next design meeting and, if the designers approve, this issue can be closed.

**Comment by jbphet** [comment]
The behavior of the panel was reviewed during the 6/22/2021 design meeting for this sim, and the designers thought it looked good.  Closing.
