### ISSUE TITLE
Update QA credits for the 1.1 prototype release

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#260]
@KatieWoe - I'm close to rolling a new RC for the prototype release.  Who should be added added to the QA credits?  Feel free to message me via Slack or use Github handles if you want to avoid full names in this issue.

The current credits list you and @Nancy-Salpepi.

**Comment by jbphet** [comment]
@KatieWoe messaged me with the needed info over Slack, and I've incorporated it into master and the 1.1 branch.

**Comment by jbphet** [comment]
These two have now been added to both the master and 1.1 branches.

**Comment by Nancy-Salpepi** [comment]
Credits have been updated in rc.3. Closing.
