### ISSUE TITLE
IR Waves look odd when level of Greenhouse gases decreases quickly

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#263]
**Test device**
iPad 9th generation and MacBook

**Operating System**
iPadOS16.2 and macOS 13.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/885, on the Waves Screen I noticed that when I decrease the concentrations levels by large increments, the coloring in IR waves looks odd (sort of clumpy).
I do not see this in the published prototype. 

**Steps to reproduce**
1. On the waves screen, press the Start Sunlight button
2. Wait a couple of seconds, then move the concentration slider all the way to 'none.'

**Visuals**

https://user-images.githubusercontent.com/87318828/214150939-0e41e275-af3e-4513-83d2-b863dd1cff8c.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.2/phet/greenhouse-effect_all_phet.html
Version: 1.1.0-rc.2 2023-01-18 00:39:07 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1275x781
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment]
We use both stroke weight and opacity to communicate the intensity of the radiation. The varying thickness was added to address https://github.com/phetsims/greenhouse-effect/issues/84. We considered moving to a constant opacity, but we lose a lot of the dynamic range that way. Ultimately, the design team decided that the artifacts created by overlapping opacities were an acceptable trade-off.
