### ISSUE TITLE
Maltese translation seems incorrect for compounds

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#266]
The Maltese translations (locale=mt) for methane and nitrous oxide seems to be messed up.  Here is what they look like in the recently published 1.1 version:

![image](https://user-images.githubusercontent.com/3082831/216172213-9a38c63c-9ac3-42cb-8cc5-bdbd98418649.png)

For reference, here is what it looks like in the English version:

![image](https://user-images.githubusercontent.com/3082831/216172919-5c1d4216-6e82-4b77-bfff-a8afd11ecacc.png)

@oliver-phet - These strings were present in the translation interface but didn't show up in the sim, so the translator wouldn't have been able to see them in context, but they are visible in the sim now that the 1.1 version has been published.  What's your opinion - should I just fix them up, or should we email the translator?  There is an outside chance that they use different chemical formulas than we do, but that seems very unlikely to me.

**Comment by oliver-phet** [comment]
I'd just fix them, seems like an accident.

**Comment by jbphet** [comment]
I fixed the strings file and had the sim rebuilt.  I just checked it at https://phet.colorado.edu/sims/html/greenhouse-effect/latest/greenhouse-effect_mt.html and it looks good.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/3082831/216694176-c134c1a3-5244-426e-b5dc-35a55bcba6de.png)

Closing.
