### ISSUE TITLE
Let translators know that they should re-do existing translations for 1.1 release

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#267]
@oliver-phet - I just published the 1.1 prototype version of this sim, and it adds two new screens.  There are quite a number of translations that already exist, and they are now only partially translated.  Can you let the translators know that they need to redo these if they want them to be complete?

Please let me know if you'd like a list of the existing translations for a more targeted email.

**Comment by oliver-phet** [comment]
Email sent via 'Send Simulation Notification to Trusted Translators' website feature (_all_ PhET trusted translators emailed).
