### ISSUE TITLE
Assets missing for the sounds on the first three screens

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#276]
The asset files for the sounds on the first three screens (i.e. the uncompressed .wav files) are not in the `assets` directory.  They should be added.  Here are the MP3 files for which there is no corresponding WAV file:

- [x] emissionOfInfraredPhotonFromAtmosphere
- [x] energyBalanceBlip
- [x] irFluxDownA
- [x] irFluxDownB
- [x] irFluxUp
- [x] layerModelBaseSliderSound
- [x] oneAbsorbingLayer
- [x] sliderMovement
- [x] startSunlightChord
- [x] temperatureBaseAmbience4Octaves
- [x] threeAbsorbingLayers
- [x] twoAbsorbingLayers
- [x] wavesIrReemissionLoop
- [x] wavesIrReemissionStartingSound

**Comment by jbphet** [comment]
I just looked through the Google Drive directory for the .wav versions of these files, and it appears that some may be there and some may not, and it is a little hard to match them up by name.  @Ashton-Morris - Can you provide these `.wav` files?  If so, you could commit them directly to the `assets` directory in the repo (with names that match the list above) or, if you're not comfortable with that, you could put them in a separate Google Drive directory with names matching those shown above and I'll commit them.  You can download and listen to the MP3 versions of the files from https://github.com/phetsims/greenhouse-effect/tree/master/sounds if that would help.

**Comment by Ashton-Morris** [comment]
JB I have committed this files. Once you verify that they are correctly in the assets folder, feel free to close.

- emissionOfInfraredPhotonFromAtmosphere.wav
- energyBalanceBlip.wav
- irFluxDownA.wav
- irFluxDownB.wav
- irFluxUp.wav
- layerModelBaseSliderSound.wav
- oneAbsorbingLayer.wav
- sliderMovement.wav
- startSunlightChord.wav
- temperatureBaseAmbience4Octaves.wav
- threeAbsorbingLayers.wav
- twoAbsorbingLayers.wav
- wavesIrReemissionLoop.wav
- wavesIrReemissionStartingSound.wav

**Comment by jbphet** [comment]
Looks great - thanks @Ashton-Morris.  Closing.
