### ISSUE TITLE
Review Studio tree

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#278]
@jbphet @arouinfar and @pixelzoom are having at meeting on 5/15/2023 to review the Studio tree.

I'll do some review in advance, and post my notes here.

**Comment by pixelzoom** [comment]
I reviewed the Studio tree.  Here's my feedback, broken into categories.

# Model

- [ ] Should there be more grouping of related things under `waveScreen.model`?

- [ ] phetioDocumentation for more model Properties would be useful.

- [ ] What purpose is `model.cloud` serving?

- [ ] Should `model.cloudEnabledProperty` be moved to `model.cloud.enabledProperty`?

- [ ] `dateProperty` enum values are difficult to grok. Suggested change:
* SEVENTEEN_FIFTY => YEAR_1750
* NINETEEN_FIFTY => YEAR_1950
* TWENTY_TWENTY => YEAR_2020

- [ ] Tell me about the 12 layers (`layer0` - `layer11`) under `model.atmosphereLayers`. This might be something to include in phetioDocumentation and/or examples.md.

- [ ] `model.manuallyControlledConcentrationProperty`: Don't you usually refer to a Property like this as "userControlled"?

- [ ] `model.surfaceTemperatureKelvinProperty`: Do you need PhET-iO-only Properties for C and F? I'm guessing that they already exist as DerivedProperties and just need to be instrumented.

- [ ] `model.waveAtmosphereInteractions` looks like an ObservableArray, and may have this problem: https://github.com/phetsims/axon/issues/437. Do you really want to instrument `elementCreatedEmitter` and `elementDisposedEmitter`?

# View

- [ ] Elements that are of type Panel (or look like a Panel) typically have tandem suffix "Panel". And the prefix is typically the title of the panel. This makes it easy to search for a panel based on its visible title. For example:
* `photonsScreen.view.concentrationControlPanel` => `concentrationPanel`
* `layerModelScreen.view.layersControl` => `infraRedPanel`
* `layerModelScreen.view.sunAndReflectionControl`=> `sunlightPanel`

- [ ] `labelText` vs `text`: `energyLegend.infraredLabelText` and `sunlightLabelText` could just be `infraredText` and `sunlightText`.  I see `labelText` for cases that don’t need to be qualified, e.g. `cloudCheckbox.labelText`.  But I also see `startSunlightButton.text`.

- [ ] `concentrationControlPanel.concentrationSlider.slider`: instrument “Lots” and “None” text?

- [ ] What purpose is `dateControl` serving? It’s not a PhetioObject, and it has 1 child, `dateControl.dateRadioButtonGroup`.

- [ ] Text on `dateControl.dateRadioButtonGroup.*RadioButton` in not instrumented.

- [ ] Do you really want to instrument `dateControl.dateRadioButtonGroup.visibleProperty`, or `concentrationSlider.slider.visibleProperty`? Hiding either of these results in a very odd UI.

- [ ] `concentrationControlPanel.controlRadioButtonGroup` name is vague. By convention, it's name should be `concentrationControlModeRadioButtonGroup`, because the associated Property is of type `ConcentrationControlMode`.

- [ ] Do you really want to instrument `observationWindow.visibleProperty`?

- [ ] Explain the name `observationWindow.instrumentVisibilityControls`. Should this be `somethingCheckboxGroup`? I don't see `VerticalCheckboxGroup` used in InstrumentVisibilityControls.ts, which should be used for a consistent PhET-iO instrumentation.

- [ ] `fluxMeterNode` does not instrument the 3 text nodes (Energy Flux, Sunlight, Infrared) that appear in the meter.

- [ ] Is `fluxMeterNode.zoomButtonGroup` relevant for the Photos screen? I first encountered it here, and it was confusing that `fluxMeterNode.zoomButtonGroup.visibleProperty` did nothing.  If it's not relevant, it should not be instrumented for the Photons screen.

- [ ] The panel titled "Energy Balance" does not appear to be instrumented. I couldn't not find it under observationWindow, and I searched for energyBalancePanel.  The text that appears in this panel should also probably be instrumented.

- [ ] Titles for `solarIntensitySlider` and `surfaceAlbedoSlider` are not instrumented.

- [ ] Tick mark "Our Sun" for solarIntensitySlider is not instrumented. Maybe that's OK.

- [ ] Rename `absorbanceSlider` to `infraredAbsorbanceSlider`, to match their titles. Also instrument their titles, as `absorbanceSlider.titleText` and `infraredAbsorbanceSlider.titleText`.

- [ ] Rename `numberOfLayersPicker to absorbingLayersPicker`, to match its label. Instrument its label, `absorbingLayersPicker.labelText`.

# Usability

- [ ] For "date control" mode in the Concentraton panel, move the CO2/CH4/N2O info above the radio button group. It's related to the selected date, and it's currently too disconnected (lacks proximity) from selected date. Making this connection is more important than keeping the radio buttons in a fixed position in the control panel.

**Comment by pixelzoom** [comment]
This one was already addressed by @jbphet in [63edf1b8ee5b003793129d835688cc56586e0bca](https://github.com/phetsims/greenhouse-effect/commit/63edf1b8ee5b003793129d835688cc56586e0bca), but not checked off. 

>  - [ ] I don't see `fluxMeterNode.visibleProperty`. I expected it to be a linked element to `fluxMeterVisibleProperty`.

**Comment by pixelzoom** [comment]
Some of the items in the checklist above are design decisions. I've broken them out into separate issues, assigned to @arouinfar.  I checked them off in the above checklist, with no _Design issue..._

**Comment by pixelzoom** [comment]
Done in the above commit:

> - [ ] `concentrationControlPanel.controlRadioButtonGroup` name is vague. By convention, it's name should be `concentrationControlModeRadioButtonGroup`, because the associated Property is of type `ConcentrationControlMode`.

**Comment by pixelzoom** [comment]
This item has already been addressed by @jbphet in https://github.com/phetsims/greenhouse-effect/commit/cbc61cc712ae7abec134db47018ae4ce8fa3943c, so I'll check it off.

>  - [ ] Explain the name `observationWindow.instrumentVisibilityControls`. Should this be `visibilityCheckboxGroup`? I don't see VerticalCheckboxGroup used in InstrumentVisibilityControls.ts, which should be used for a consistent PhET-iO instrumentation.

**Comment by pixelzoom** [comment]
All issues in the above checklist have either been addressed, or moved to their own issues.  This issue can be closed after @jbphet reviews my comments and commits above, starting with https://github.com/phetsims/greenhouse-effect/issues/278#issuecomment-1583359571.

**Comment by jbphet** [comment]
Review complete, closing.
