### ISSUE TITLE
Consider converting to default layoutBounds before PhET-iO publication

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#279]
This sim currently uses non-default `layoutBounds`.  In MicroScreenView.js:

```ts
      layoutBounds: new Bounds2( 0, 0, 768, 504 ),
```

Per https://github.com/phetsims/phet-io/issues/1939...  `layoutBounds` should not be changed for published PhET-iO sims because doing so may disrupt client customizations. So evaluate whether to change `layoutBounds` before publishing a PhET-iO version. 

If you decide not to change layoutBounds, document why in MicroScreenView.js, and refer to this issue.

**Comment by jbphet** [comment]
The MicroScreenView is actually already published as the Molecules and Light sim, which is also already published as phet-io, see https://phet-io.colorado.edu/sims/molecules-and-light/1.3/wrappers/index/.  @pixelzoom and I discussed this and since it's published, the bounds should not be changed.
