### ISSUE TITLE
Add sound for Greenhouse Gas Concentration slider

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#28]
@Ashton-Morris has mocked up some sounds for the concentration slider, so it's time to start making some prototypes that we can run by the larger design groups.  @Ashton-Morris - please get the sounds to me and I'll start putting them in.

**Comment by Ashton-Morris** [comment]
[I have added the sounds here.](https://drive.google.com/drive/folders/19bEE-mjkSfpZBq5C6TtlKjP4yJa5zr3C?usp=sharing)

From out conversation the implementation was suggested as follows: attach a sound clip to each "bin" on the slider - 001 being the bottom and 011 being the top. Test with some rules indicating that it can only play the last two bins crossed or to fade out other concentration slider sounds based on recency. That way that if the slider is being dragged up and down in a rapid motion it doesn't play too many sounds and only plays the important ones. 

- greenhouse-gas-concentration-slider-001.mp3
- greenhouse-gas-concentration-slider-002.mp3
- greenhouse-gas-concentration-slider-003.mp3
- greenhouse-gas-concentration-slider-004.mp3
- greenhouse-gas-concentration-slider-005.mp3
- greenhouse-gas-concentration-slider-006.mp3
- greenhouse-gas-concentration-slider-007.mp3
- greenhouse-gas-concentration-slider-008.mp3
- greenhouse-gas-concentration-slider-009.mp3
- greenhouse-gas-concentration-slider-010.mp3
- greenhouse-gas-concentration-slider-011.mp3

**Comment by jbphet** [comment]
Reviewed in today's sound design meeting:
- It seems pretty good in context, so we'll share it with the full design group
- We should try to figure out a way to get a sound to play on every key movement, and at the moment there is only a sound on every other shift-up-arrow or shift-down-arrow key (which are the finest keyboard movements possible)
- It seems a bit loud - see if the volume can be reduced

**Comment by jbphet** [comment]
@Ashton-Morris - I need to get two things from you to continue with this:
1. We need one additional sound.  Here's why: There should be a sound for each bin, which is the space between a given pair of tick marks, and one each for the min a max.  Since there are 11 total tick marks including the end points, that's 10 bins, and thus we need 12 sounds.
2. Have 12 `.mp3` files to the sim increases its size by quite a bit, so I'd like to try using a single sound and generating the overall effect programmatically by varying the number of sounds played and their pitch.  Can you please provide a single sound that I could use as the basis for this?  It should probably be pitched somewhere in the middle of the range of the `.mp3` files that have been provided thus far.

**Comment by jbphet** [comment]
This was discussed in the 5/19/2021 design meeting and it was basically approved with the list of sounds above.  The next step - after getting the additional sound from @Ashton-Morris and integrating it - is to try to replicate the sound programmatically to reduce the costs in terms of sim size and load time.

**Comment by jbphet** [comment]
We reviewed the programmatic version in today's sound design and we decided it was close, but @Ashton-Morris would like to try one or more different "basis sounds" to see if we like it better.

**Comment by Ashton-Morris** [comment]
[I have some more basis sounds to try out.](https://drive.google.com/drive/folders/19bEE-mjkSfpZBq5C6TtlKjP4yJa5zr3C?usp=sharing)

- greenhouse-gas-concentration-slider-octave-up.mp3
- greenhouse-gas-concentration-slider-octave-down.mp3
- greenhouse-gas-concentration-slider-sine-woop.mp3
- greenhouse-gas-concentration-slider-pop.mp3
- greenhouse-gas-concentration-bell.mp3 (which is imitating precipitate in Molarity)

**Comment by jbphet** [comment]
We reviewed these sounds in today's sound design meeting and decided to go with greenhouse-gas-concentration-slider-octave-down.  I'll remove the sounds that we've ruled out and will work with @Ashton-Morris to finalize the asset files.

**Comment by jbphet** [comment]
The agreed-upon sound has been integrated and the other alternatives removed.

@Ashton-Morris - two things:
- [ ] I need the .wav version of the final sound for the assets directory
- [ ] Please note in your records that I've changed the file name from `greenhouse-gas-concentration-slider-octave-down` to `slider-movement`.

**Comment by Ashton-Morris** [comment]
- [slider-movement.wav](https://drive.google.com/file/d/19GqEmA5rInjAiWqkESbx8McZSy7c6bdh/view?usp=sharing)

**Comment by jbphet** [comment]
The initial sound generator has been added.  Closing.  Any further work on this will be done under other GitHub issues, such as the one that will come along eventually for the final sound design review.
