### ISSUE TITLE
Review grouping of model elements in Studio tree

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#281]
In https://github.com/phetsims/greenhouse-effect/issues/278, @pixelzoom recommended reviewing the structure of the studio tree with respect to grouping in the model.  He said:

> Should there be more grouping of related things under `waveScreen.model`, `photonsScreen.model`, and `layeredModelScreen.model`

I'm breaking this out into a separate issue for follow-up on this suggestion.

**Comment by arouinfar** [comment]
@jbphet I've come up with the model groupings for each screen. I've outlined the full model for the Waves Screen. The Photons and Layer Model screens will share the same groupings where applicable, e.g. no `model.waves` on the latter screens.

Please let me know if you have any questions or if anything looks off to you. I'm happy to collaborate.

**Waves Screen**
```
  isPlayingProperty
  timeSpeedProperty
+ atmosphereLayers
- cloud
    cloudEnabledInManualConcentrationModeProperty 
    cloudEnabledProperty (currently linked, so nest instead)
- concentration
    concentrationControlModeProperty 
    concentrationProperty 
    dateProperty 
    manuallyControlledConcentrationProperty 
- energyBalance
    inRadiativeBalanceProperty 
    netInflowOfEnergyProperty 
    energyBalanceVisibleProperty 
    *outgoingEnergyRateProperty ->Link to outerSpace.incomingUpwardMovingEnergyRateTracker.energyRateProperty
    *incomingEnergyRateProperty ->Link to sunEnergySource.outputEnergyRateTracker.energyRateProperty 
+ groundLayer
+ outerSpace
+ sunEnergySource
- surfaceTemperature
    temperatureUnitsProperty 
    surfaceTemperatureVisibleProperty 
    surfaceThermometerVisibleProperty 
    surfaceTemperature*Property 
- waves
    groundWaveSource 
    sunWaveSource 
    waveAtmosphereInteractions 
    waveGroup 
```
**Photons Screen**
* Same general structure as Waves screen, only additional change would be to nest `fluxMeterVisibleProperty` under `model.fluxMeter`

**Layer Model Screen**
* Same general structure as Photons screen, but would like to nest `numberOfAtmosphereLayers` under `model.atmosphereLayers`.

**Comment by pixelzoom** [comment]
The desired tree structure is nicely specified above. Best case, it will be matter of adding intermediate tandems to provide grouping/structure.  Worst case it will be restructuring code to do things that can't be accomplished via intermediate tandems.

**Comment by pixelzoom** [comment]
@jbphet and I discussed this, and did a little of it together in the above commit.  @jbphet gets the idea, so I'm going do the rest.

**Comment by pixelzoom** [comment]
@arouinfar ready for review.  The only difference from what you specified in https://github.com/phetsims/greenhouse-effect/issues/281#issuecomment-1572866428 is that 

`greenhouseEffect.layerModelScreen.model.atmosphereLayers.numberOfAtmosphereLayersProperty` 

is actually

`greenhouseEffect.layerModelScreen.model.atmosphereLayers.numberOfActiveAtmosphereLayersProperty`.

The tandem name was incorrect in the code, and has been changed to match the actual Property name.

**Comment by pixelzoom** [comment]
> If I run into any weirdness with photons and layers, leave it alone and discuss with @jbphet. It's probably related to https://github.com/phetsims/greenhouse-effect/issues/284.

@jbphet FYI, I did not run into this.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! This is a really nice upgrade, everything looks great in Studio, closing.
