### ISSUE TITLE
Uninstrument color profile

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#282]
Related to #278 

Colors are generally instrumented on an opt-in basis, usually related to some pedagogical purpose. Everything in the color profile has been instrumented, but I recommend that we uninstrument it all.

![image](https://github.com/phetsims/greenhouse-effect/assets/8419308/de4dd71b-108a-4acc-b6ed-c17dd066b8f0)

Changing the sunlight and infrared colors is problematic. These colors represent the waves, but the photons are images, so colors could get out of sync. The rest of the colors are related to background/panel colors and the active stroke around the radio buttons, which I don't think are worth exposing.

**Comment by pixelzoom** [comment]
Done in the above commit.  `global.view.colors` no longer exists. @jbphet FYI.  @arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! Looks good in master, closing.
