### ISSUE TITLE
`sunEnergySource.proportionateOutputRateProperty` is only useful on Layer Model screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#283]
Related to #278 

`sunEnergySource.proportionateOutputRateProperty` changes the solar intensity. This property is necessary for the Layer Model screen, but it can create problematic situations on the Waves and Photons screens, which were not designed to support variable solar intensity.

I see two options for the Waves and Photons screens:
1. Make this property read-only. This keeps the `sunEnergySource` tree structure the same on all screens, but prevents users from changing solar intensity inappropriately. 
2. Uninsturment this property. The data itself is not particularly useful on the Waves and Photons screens.

Another thing to be mindful of is the `phetioFeatured` behavior. While I haven't done the full review yet, I know this property should be featured since it powers a UI control (Solar Intensity slider). I don't think it's worthwhile to specify different `phetioFeatured` behavior on different screens, so if we go with option (1) this property will be visible in the featured tree on the Waves and Photons screens.

@jbphet if these options are equivalent in terms of implementation, I would prefer option (2). However, I wouldn't be surprised if it's more nuanced than that, so feel free to go with whichever option makes more sense to you.

**Comment by arouinfar** [comment]
Looks good in master, thanks @pixelzoom!

**Comment by jbphet** [comment]
Works for me.  Closing.
