### ISSUE TITLE
Implement hierarchical state handling in the Photons and Layer Model screens

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#284]
I met with @zepumph yesterday and he filled me in on the latest and greatest ways for implementing state handling in hierarchical models.  We have done it (mostly) for the `WavesModel`, and I now need to use the same patterns for `PhotonsModel` and `LayerModelModel`.

**Comment by jbphet** [comment]
The parent issue for this is https://github.com/phetsims/greenhouse-effect/issues/274, and [this comment](https://github.com/phetsims/greenhouse-effect/issues/274#issuecomment-1569051037) is particularly relevant.

**Comment by zepumph** [comment]
- [ ] I would like to investigate why ConcentrationModelIO needs to have an empty stateSchema, that seems buggy to me.

**Comment by zepumph** [comment]
Ahha! @samreid and I found that the bug was my fault. Thanks for your patience, and we removed that unnecessary stateSchema.

**Comment by jbphet** [comment]
A fair amount of work on general state in the sim was done under https://github.com/phetsims/greenhouse-effect/issues/274, so there was some overlap between the two issues.

@zepumph and I just worked on some final refinements of state in the sim, and we think we are done, so I'll close this.
