### ISSUE TITLE
Instrument PatternStringProperty and DerivedProperty for strings that need to be autoselectable in Studio.

### ISSUE THREAD

**Issue by zepumph** [phetsims/greenhouse-effect#285]
From https://github.com/phetsims/phet-io/issues/1942, I passed some tandems through but mostly `Tandem.OPT_OUT`s, please review this sim's instrumentation of PatternStringProperties in correlation to this sims' phet-io priorities.  In general all PatternStringProperties should be instrumented unless they are just symbols or patterns that aren't for i18n purposes.

**Comment by pixelzoom** [comment]
I see 9 instances of PatternStringProperty that need to be instrumented. They currently have `tandem: Tandem.OPT_OUT`.

I see only 2 instances of DerivedStringProperty that need to be instrumented:

AtmosphereLayerNode: `units: new DerivedProperty(`
ThermometerAndReadout: `const unitsStringProperty = new DerivedProperty(`

So this should be relatively straightforward.

**Comment by pixelzoom** [comment]
There are some new developments over in https://github.com/phetsims/phet-io/issues/1943#issuecomment-1585124164 that may change how this is accomplished.  So @jbphet let's discuss before working on this issue.

**Comment by pixelzoom** [comment]
I work on the PatternStringProperty instances.

**Comment by pixelzoom** [comment]
All PatternStringProperty instances have been addressed in the above commits. For tick labels like "50%", I documented that we will not instrument them.

**Comment by zepumph** [comment]
Can you please note how this behavior compares to instrumenting every Text node. Do we prefer this Property-centric instrumentation strategy to Text instrumenting? Can you also speak to if you feel like it is over-instrumenting and or too time consuming. I believe this will help us for the discussion we will have at PhET-iO meeting on Thursday.

**Comment by pixelzoom** [comment]
In the above commit, I used DerivedStringProperty for the 2 instances of DerivedProperty that correspond to strings shown in the UI.   The elements added to the Studio tree are:

* `atmosphereLayer*.unitsStringProperty`
* `surfaceThermometer.unitsStringProperty`

There were no "global" derived strings, so no need to put any elements under `greenhouseEffect.general.model.strings.greenhouseEffect.derivedStrings`.

@arouinfar please review the Studio tree.

**Comment by arouinfar** [comment]
Thanks @pixelzoom the `unitsStringProperty` looks great in Studio. 

This seemed similar to the way we're displaying units on the Waves and Photons screens, so I reviewed the temperature comboBox and found `surfaceThermometer.comboBox.items.*Item.valuePatternStringProperty` which also looks good to me. Closing.
