### ISSUE TITLE
Uninstrument Text and RichText

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#286]
Because this sim has not been previously published for PhET-iO, uninstrument Text and RichNodes.

~~And the way forward per https://github.com/phetsims/phet-io/issues/1942 is to instrument PatternStringPropery and DerivedProperty<string>, so strings that are visible in the UI can be autoselected in Studio.~~

**Comment by pixelzoom** [comment]
> And the way forward per https://github.com/phetsims/phet-io/issues/1942 is to instrument PatternStringPropery and DerivedProperty, so strings that are visible in the UI can be autoselected in Studio.

I see that this is being handled in https://github.com/phetsims/greenhouse-effect/issues/285. So I'll modify this issue accordingly.

**Comment by pixelzoom** [comment]
There were no instrumented RichText in this sim.  And most of the Text were not instrumented - a small number of them were uninstrumented in the above commit.  

@jbphet take a peek, feel free to close.

**Comment by pixelzoom** [comment]
There were no instrumented RichText in this sim.  And most of the Text were not instrumented - a small number of them were uninstrumented in the above commit.  

@jbphet take a peek, feel free to close.

**Comment by jbphet** [comment]
Looks good to me - thanks @pixelzoom!  Closing.
