### ISSUE TITLE
Uninstrument visibleProperty where it is not useful.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#287]
From https://github.com/phetsims/greenhouse-effect/issues/278:

>  - [ ] Do you really want to instrument `dateControl.dateRadioButtonGroup.visibleProperty` and `concentrationSlider.slider.visibleProperty`? Hiding either of these results in a very odd UI.

> - [ ] Do you really want to instrument `observationWindow.visibleProperty`? Does hiding it result in a useful sim?

**Comment by pixelzoom** [comment]
If @arouinfar approves uninstrumenting these visibleProperty elements, I'll be happy to handle it.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I remember discussing these with @jbphet at some point, and we agreed to uninstrument `concentrationSlider.slider.visibleProperty` and `observationWindow.visibleProperty`. Looks like he already uninstrumented them, but probably forgot to check them off in the other issue. I also made a note in #280 to discuss the concentration slider in examples.md.

Changing`dateControl.dateRadioButtonGroup.visibleProperty` isn't disruptive in the same way that `concentrationSlider.slider.visibleProperty` was. Hiding the radio button group looks like this:
<img width="109" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/553d6a4e-8e4d-482c-a36d-806b75d9a63f">

It's perhaps a bit strange, but it's not broken. The graphic indicates the greenhouse gas concentration at the currently selected (albeit hidden) time period. I don't think we need to uninstriment this particular `visibleProperty`.
