### ISSUE TITLE
Relocate `cueingArrowsEnabledProperty` in the Studio tree

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#289]
I see `greenhouseEffect.global.view.options.cueingArrowsEnabledProperty` in the Studio tree.

"Options" no longer exists, and has been replaced by "Preferences". And there is prescedence in other sims for having preferences that do not appear in the Preferences dialog.   For example in Geometric Optics, we have the exact same Property located at `geometricOptics.global.model.preferences.cueingArrowsEnabledProperty`

So I recommend moving `greenhouseEffect.global.model.preferences.cueingArrowsEnabledProperty`.

@jbphet FYI. @arouinfar do you agree?

**Comment by pixelzoom** [comment]
@jbphet This is a relatively self-contained task. So if @arouinfar approves, feel free to delegate this to me.

**Comment by arouinfar** [comment]
Good catch @pixelzoom. Yes, please make this change.

**Comment by pixelzoom** [comment]
Done in the above commits. Studio tree is shown below. @arouinfar please review, close if OK.

<img width="339" alt="screenshot_2594" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/0d3bb0bf-9b1c-4507-ba15-7be5b832e14f">
