### ISSUE TITLE
i18n for the temperature readouts

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#29]
While making the thermometer I wasn't sure how to best support i18n for the temperature value, units, and degrees readout. What I have right now are the following:

```js
  "temperature.units.kelvin": {
    "value": "K"
  },
  "temperature.units.celcius": {
    "value": "C"
  },
  "temperature.units.fahrenheit": {
    "value": "F"
  },
  "temperature.units.valueKelvinPattern": {
    "value": "{{value}} {{units}}"
  },
  "temperature.units.valueDegreesUnitsPattern": {
    "value": "{{value}} {{degrees}}{{units}}"
  }
```

The temperature unit can be translated. The order of {{value}} and "K" can be translated when displaying temperature in kelvin. The order of "{{value}} {{degrees}{{units}}" supports order of those things for temperature in celcius and fahrenheit. The symbol for degrees cannot be translated.

@arouinfar can you please check this and comment if this is correct?

**Comment by arouinfar** [comment]
@jessegreenberg this looks a bit more complicated than necessary. I would include the degrees symbol within `temperature.units.celcius` and `temperature.units.fahrenheit` which would eliminate the need for the valueDegreesUnitsPattern.

Perhaps states-of-matter would be a useful reference here? I am pretty sure we included the degrees symbol in the unit itself.

**Comment by jessegreenberg** [comment]
Done in the above commit.
