### ISSUE TITLE
Uninstrument `fluxMeterNode.zoomButtonGroup` for Photons screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#292]
From https://github.com/phetsims/greenhouse-effect/issues/278#issuecomment-1548266037:

> - [ ]  Is `fluxMeterNode.zoomButtonGroup` relevant for the Photons screen? I first encountered it here, and it was confusing that `fluxMeterNode.zoomButtonGroup.visibleProperty` did nothing. If it's not relevant, it should not be instrumented for the Photons screen.

@arouinfar should we uninstrument `greenhouseEffect.photonsScreen.view.observationWindow.fluxMeterNode.zoomButtonGroup`?

**Comment by pixelzoom** [comment]
In FluxMeterNode.ts, I found this:

```ts
    // zoom buttons conditionally added to the view, but always created because I think that is required for PhET-iO
    const contentChildren: Node[] = [ titleText, fluxArrows ];
    options.includeZoomButtons && contentChildren.push( zoomButtons );
```

It is not the case that zoomButtons must always be created in this case.  So in the above commits, they are now conditionally created. And they therefore no longer appear in the Studio tree for the Photons screen.

@jbphet please review, close if OK.

**Comment by jbphet** [comment]
This may be something for a separate issue, but while reviewing this I found that the element `greenhouseEffect.photonsScreen.view.observationWindow.fluxMeterNode.zoomFactorProperty` is visible and settable on the "Photons" screens even though the zoom buttons aren't included on the flux meter on that screen.  That doesn't seem quite right.  @arouinfar - How should we handle this?  Should I make it read-only on this screen?

**Comment by arouinfar** [comment]
> This may be something for a separate issue, but while reviewing this I found that the element `greenhouseEffect.photonsScreen.view.observationWindow.fluxMeterNode.zoomFactorProperty` is visible and settable on the "Photons" screens even though the zoom buttons aren't included on the flux meter on that screen. @arouinfar - How should we handle this? Should I make it read-only on this screen?

I also noticed this and debated creating an issue, but decided against it since the `zoomFactorProperty` is functional. If it's straightforward to make it read-only on the Photons screen, let's do it. It's not worth significant effort, though.

**Comment by jbphet** [comment]
It was straightforward so I went ahead and did it.  I think that's it for this issue, closing.
