### ISSUE TITLE
TODO comments do not link to a GitHub issue

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#294]
There are quite a few `TODO` comments in this sim that do not link to a GitHub issue.  

Make this change in package.json:

```
-      "todo-should-have-issue": "off"
```

... then address the errors.

**Comment by jbphet** [comment]
All TODOs with out issues have either been addressed, removed (if obsolete), or had an issue added.  I've also turned on the lint rule.  Closing.
