### ISSUE TITLE
`instrumentVisibilityPanel` needs an appropriate `maxWidth`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#295]
I reviewed dynamic locale for #293 and generally everything looked good. The only exception is the `instrumentVisibilityPanel` that contains the Energy Balance and Flux Meter checkboxes. There doesn't a appear to be a `maxWidth` limiting the panel's expansion and it can escape off-screen

<img width="990" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/b9b48263-828f-4bfc-b544-6b71f969797a">

A more appropriate `maxWidth` would be something similar to this:
<img width="986" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/1619e026-3286-4bd9-a00e-f486d58ff7dd">

Co-assigning @pixelzoom since this issue seems fairly general.

**Comment by pixelzoom** [comment]
Done in the above commit. I used `maxWidth: 300`, shown in the screenshot below.

@arouinfar please close if this looks acceptable.

<img width="1117" alt="screenshot_2596" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/9cb103c3-bf45-471d-981c-9041d3a17681">

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good!
