### ISSUE TITLE
`surfaceThermometer.visibleProperty` should be a link to `surfaceThermometerVisibleProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#296]
For #293

The surface thermometer appears when `surfaceThermometerCheckbox` is checked (`surfaceThermometerVisibleProperty` is `true`). 
<img width="145" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/045e2d58-d26e-4f9c-acac-956a1d112858">

The surface thermometer is instrumented in the view under `view.observationWindow.surfaceThermometer`. 

<img width="245" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/7d55a555-48e0-40cc-955c-653b71cbb09b">

On the Waves and Photons screens, the thermometer can be hidden with `view.observationWindow.surfaceThermometer.visibleProperty` while the checkbox remains checked, which is problematic. 

However, this is handled correctly on the Layer Model screen which links to `surfaceThermometerVisibleProperty`. We should do the same on the Waves and Photons screens.
<img width="213" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/b708cdb5-bc10-4a81-ba4e-125e05b94d64">

Co-assigning @pixelzoom since this seems more general.

**Comment by pixelzoom** [comment]
I'll take this one.

**Comment by pixelzoom** [comment]
Fixed in the above commit. @arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good in master, closing.
