### ISSUE TITLE
Clients should be able to hide the cloud checkbox

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#297]
For #293 

Currently `view.cloudCheckbox` doesn't have an instrumented `visibleProperty`. This is likely because the model controls the visibility of the checkbox based on the value of `concentrationControlModeProperty`.

When exploring 'BY_DATE' the cloud is always enabled and the Cloud checkbox is hidden. This is done to ensure that the surface temperature matches the average surface temperature for the given date. (The cloud is used to model albedo.)

However, when in 'BY_VALUE' mode, the cloud can be turned on or off with a checkbox. Clients should have the ability to hide this checkbox if they want to.

**Comment by pixelzoom** [comment]
Another way that this has been addressed is by adding a Property to enable/disable the feature, and including that Property in the derivation of visibility.  For example, Calculus Grapher has `predictPreferenceEnabledProperty` which hides the "Predict" feature in all screens. This pattern is useful when you want to hide all occurrences of the feature.  Greenhouse actually has 2 instances of `cloudCheckbox`, so this pattern might be more desirable? If we use the wrapper pattern described above, the instructional designer would need to hide `cloudCheckbox` separately for each screen.

I'll discuss with @arouinfar ...

**Comment by pixelzoom** [comment]
Also wondering if we should instrument `cloudCheckbox.visibleProperty`, so that we can see that it's derived from the mode:

E.g. in PhotonsScreenView.ts:

```ts
    const cloudCheckbox = new CloudCheckbox(
      model.cloudEnabledInManualConcentrationModeProperty,
      model.sunEnergySource.isShiningProperty,
      {
        visibleProperty: new DerivedProperty(
          [ model.concentrationControlModeProperty ],
          mode => mode === ConcentrationControlMode.BY_VALUE
        ),
        tandem: tandem.createTandem( 'cloudCheckbox' )
      }
    );
```

**Comment by pixelzoom** [comment]
Also wondering if we should instrument `cloudCheckbox.visibleProperty`, so that we can see that it's derived from the mode:

E.g. in CloudCheckbox.ts, the change would be:

```diff
      visibleProperty: new DerivedProperty( [ concentrationControlModeProperty ],
        mode => mode === ConcentrationControlMode.BY_VALUE, {
+         tandem: tandem.createTandem( 'visibleProperty' ),
+         phetioValueType: BooleanIO
        } ),
```

**Comment by pixelzoom** [comment]
@arouinfar and I worked on this together.  Since we want this to be controllable per screen, we used a variation of the preferences-Property approach described in https://github.com/phetsims/greenhouse-effect/issues/297#issuecomment-1589628961.  We added a PhET-iO Property to CloudCheckbox:

```ts
    // This is a PhET-iO only Property, provided so that the instructional designer can totally hide the 'Cloud'
    // checkbox, regardless of ConcentrationControlMode. See https://github.com/phetsims/greenhouse-effect/issues/297
    const showCloudCheckboxProperty = new BooleanProperty( true, {
      tandem: tandem.createTandem( 'showCloudCheckboxProperty' ),
      phetioFeatured: true,
      phetioDocumentation: 'The sim controls cloudCheckbox.visibleProperty. Set this to false to permanently hide the Cloud checkbox.'
    } );
```

... and we added that to the derivation of `cloudCheckbox.visibleProperty`:

```ts
      // This checkbox is only shown in 'by value' mode, where the concentration is controlled manually.
      // Clouds are always enabled in 'by date' mode. showCloudCheckboxProperty can be used to permanently
      // hide the checkbox, regardless of mode.
      visibleProperty: new DerivedProperty( [ concentrationControlModeProperty, showCloudCheckboxProperty ],
        ( mode, showCloudCheckbox ) => ( mode === ConcentrationControlMode.BY_VALUE ) && showCloudCheckbox, {
          tandem: tandem.createTandem( 'visibleProperty' ),
          phetioValueType: BooleanIO
        } ),
```

**Comment by pixelzoom** [comment]
Since @arouinfar and I worked on this together, we'll consider this "reviewed", and close. 

@jbphet if you have questions about this, ping me.
