### ISSUE TITLE
Inconsistent terminology for concentration control modes

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#298]
For #293 

This RadioButtonGroup switches between two modes: one where the user directly adjusts the greenhouse gas concentration with a slider and one where the user indirectly sets the greenhouse gas concentration by selecting a date.
<img width="213" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/b4be10ed-7488-4e0a-b741-655e26b7d5c4">

In the Studio tree this RadioButtonGroup is the `concentrationControlModeRadioButtonGroup` and it is controlled  by the `concentrationControlModeProperty` whose  values are `BY_VALUE` and `BY_DATE`.

However, if you look at the names of the radio buttons, they are called `byConcentrationRadioButton` and `byTimePeriodRadioButton`. These are the accessible names of the radio buttons, but it does not map well to `BY_VALUE` and `BY_DATE`. 

Is it possible to rename the radio buttons `byValueRadioButton` and `byDateRadioButton`? 

There are other places in the tree where the tandem name and accessible name are different (such as the name of this very radio button group, whose accessible name is "Experiment Mode") so it doesn't seem like they need to have a 1:1 correspondence.

**Comment by pixelzoom** [comment]
Done in the above commit, see Studio tree below.  @arouinfar please review, close if OK.


<img width="401" alt="screenshot_2598" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/bff283ce-3d73-49b4-ad8c-3a5b5f88d21e">

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good in master.
