### ISSUE TITLE
Add clouds to greenhouse waves prototype

### ISSUE THREAD

**Issue by samreid** [phetsims/greenhouse-effect#3]
Requests from meeting with @kathy-phet and @arouinfar:

* Cloud node reflection slider 0-100%
* Slider for reflection angle.
* Could make it reflect off the surface too
* Number of Red Waves
* Reflection Balance
* The red waves going back to the ground are less transparent.

![image](https://user-images.githubusercontent.com/679486/75734265-b8a65a80-5cb4-11ea-866a-562ddd1cf8bd.png)

![image](https://user-images.githubusercontent.com/679486/75734275-be03a500-5cb4-11ea-994d-4057f44167db.png)

Show animating out of the cloud?
KP: For prototype, steady state is OK

One cloud per wave? 
KP: Just a couple of clouds.  1-3 for the prototype.

What if 2 waves hit one cloud?
KP: Whatever is easier.

Does the cloud immediately reflect, or change how it looks when it absorbs light?
KP: Stay the same for prototype and real sim

Maybe show two light waves reflecting off?

What questions are you trying to answer?
KP: Trying to get a sense of what it feels like.  Maybe overwhelming when too many waves?

OK for this to be prototype-only code?
KP: Yes, it will be re-developed after we have the design.

Create a GitHub repo?
IR Waves coming off teh ground but longer wavelength, and reddish color
Some IR would come from the ground and split and some returns to the ground, but part continues

SR: Do the wave points have to match exactly?
KP: We do not have to have the continuity for the prototype but would need it for the real thing.

Do we ever show red waves and yellow waves at the same time?  Are they different scenes?
KP: We will need to show them at the same time.  You could maybe an option yellow/red/both, etc.

Could show the waves as "opaquer" or "stronger" to represent hotter earth.  That would be a good variable to control, the initial transparency.
KP: Maybe opacity or line width

Will we eventually want to depict correspondence between this model and photon model?
KP: No, the models would be completely different.

What are the learning goals?
KP: More greenhouse gases => more splits.  Or the reflection going back down is of higher intensity.  More goes back down.
KP: White things like clouds reflect a portion. 
KP: For the 2nds screen.
	KP: Hotter ground => more IR comes off.  Initial red or line width... Somehow brighter
	KP: Greenhouse gases redirect some back to the earth's surface
	KP: Amount exiting top of atmosphere doesn't change.  Amount of opacity going out of top of the screen is always the same.

**Comment by arouinfar** [comment]
> Could show the waves as "opaquer" or "stronger" to represent hotter earth. That would be a good variable to control, the initial transparency.
KP: Maybe opacity or line width

@samreid for the "Initial Red Intensity" controls, we'll want NumberControls for stroke weight and opacity.

**Comment by samreid** [comment]
Notes from today's design meeting:

Sun rays Accordion box
* Amplitude of sun
* K of sun
* omega of sun
* Get rid of resolution control
* stroke of sun
* transmitted opacity
* transmitted line width
* reflected opacity
* reflected line width
* incoming opacity
* incoming line width

Same for red, then for reflected red.

Instead of reflecting off cloud. 
Choose split point, a high one, a low one.

We kind of need more red lines.  Make at least 5
They all have a split point at different heights.

Slow is good

**Comment by samreid** [comment]
I added the changes from the preceding comment and published https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.0-dev.4/phet/greenhouse-effect_en_phet.html

Some notes:
1. I slowed down the waves a bit
2. I wasn't sure about the angles.  I put incoming and emanating rays at 0 degrees.  The "angle" control is only wired up for "red"
3. I like how the leftmost red "incident" and "reflected" waves are in phase.  It's by luck in this case, but if we use a visualization like this in the final sim, it would be nice to match phases.

@kathy-phet and @arouinfar can you please review?  Please open new issues for any recommendations.

**Comment by arouinfar** [comment]
Thanks @samreid! The waves demo has been very helpful. We reviewed dev.4 in design meeting, and have decided to continue pursuing the wave representation. There are few changes we would like to see made to help us further the design. 

- [ ] ComboBoxes are too tall and get hidden by the navbar unless the window aspect ratio is made narrower. Could probably prevent this if slider thumbs are all made ~50% smaller.
- [ ] Reduce the number of waves to 3 visible & 4 IR.
- [ ] Return the propagation of the waves. Visible enters from the top of the screen. Once it hits the ground, the IR propagates up.
- [ ] Change angle of IR coming out of the ground to something like this 
<img src="https://user-images.githubusercontent.com/8419308/77031392-1dc1a780-6967-11ea-813b-b7bd5bb75e28.png" width=100>

- [ ] Add ResetAllButton to the grass.
- [ ] Add checkbox to hide clouds (could go in the grass)
- [ ] Could you provide an estimate for how long it would take to make the wave split points in phase?

Watching visible and IR at the same time can be challenging, and we would like to test some options for viewing one dynamic wave type at a time. One option would be to simply pause the motion of the waves. Another option would be to view it a diffuse beam in the background of the sim, similar to the filtered beam in Color Vision.
<img src="https://user-images.githubusercontent.com/8419308/77031768-3088ac00-6968-11ea-87a8-864a28ca3cf5.png" width=250>

- [ ] For each wave type, add a radio button group to change the view. Options would be:
1. Wave: current dynamic behavior (default)
2. Paused: pauses the motion of the wave
3. Beam: layers a reduced opacity (25%) rectangle over the entire sim background 
4. Hidden: hide the wave

If you have any questions or would like to discuss over Zoom, please let me know!

**Comment by samreid** [comment]
I moved the requests to separate issues.  @arouinfar anything else for this issue?

**Comment by arouinfar** [comment]
Thanks @samreid. Let's close this issue.
