### ISSUE TITLE
Layout of the surface temperature thermometer

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#30]
I recently added the surface temperature thermometer and had a question about the layout. The here is what I have on master:
![image](https://user-images.githubusercontent.com/6396244/118036877-1dd6f080-b33b-11eb-99e4-8961c6727e52.png)

The mockup has it a bit further down on the window frame:
![image](https://user-images.githubusercontent.com/6396244/118036939-2deed000-b33b-11eb-9178-bc4a29a0d243.png)

I moved it up so that there is enough space within the Observation Window to display the open ComboBox. But when the ComboBox is closed, it looks a little strange.

@arouinfar what do you think about this layout? Is it OK as is? Or maybe the ComboBox should open up over the thermometer so that it can be closer to the bottom of the window frame?

**Comment by arouinfar** [comment]
@jessegreenberg I think the thermometer is a bit too far up. It's important that the entire bulb is in contact with the ground, and it's also nice to be in proximity to the other temperature checkboxes underneath it. I think it'd be fine if the ComboBox exits the Observation Window when opening. Alternatively, it could be open upward instead. 

If there's an issue with the behavior when the observation window is grayed out ("Start Sunlight" button visible), I'd be fine with making the InputEnabledProperty of the ComboBox (and any other UI components inside the observation window) false until sunlight is started. There isn't a pedagogical reason to interact with those components before sunlight is started, anyway.

**Comment by jessegreenberg** [comment]
OK sounds good. When moved down I found it a little too busy to have the ComboBox open over the Checkbox text below the ObservationWindow so I made it open upward. @arouinfar what do you think, can you please review behavior on master?

**Comment by arouinfar** [comment]
Looks good in master @jessegreenberg.

**Comment by jessegreenberg** [comment]
Thanks! Closing.
