### ISSUE TITLE
`wireMeterAttachmentPositionProperty` should be read-only (or uninstrumented)

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#303]
For #293 

Here's what `model.fluxMeter` currently looks like:

<img width="729" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/8185664a-ed25-4b1b-af00-1cf61c4d75bd">

It contains `wireMeterAttachmentPositionProperty` and `wireSensorAttachmentPositionProperty` which are the end coordinates of the wire that runs between the flux meter body and probe. These seem like irrelevant implementation details. But assuming they're necessary for state and can't be uninstrumented, we should make `wireMeterAttachmentPositionProperty` read-only. Otherwise, you can create situations like this:

<img width="271" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/a792d7d8-3a54-4e29-91f0-273c04f66da2">

**Comment by pixelzoom** [comment]
I'll take this. @jbphet suggested that I should evaluate whether this even needs to be instrumented.

**Comment by pixelzoom** [comment]
Done in the above commit, see screenshot below.  @arouinfar please verify, close if OK.

<img width="673" alt="screenshot_2620" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/522c4a7a-6093-4839-b269-a25c4cfaabdb">

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom.
