### ISSUE TITLE
Unfeature `concentrationControlModeRadioButtonGroup.*RadioButton.enabledProperty`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#308]
Requested in https://github.com/phetsims/greenhouse-effect/issues/300#issuecomment-1597373083.

Fixing a bug in RectangularRadioButton is a prerequisite to this issue, see https://github.com/phetsims/sun/issues/847.

**Comment by pixelzoom** [comment]
@arouinfar This is ready for your review. Close if OK.

**Comment by arouinfar** [comment]
Looks good in master, thanks @pixelzoom

**Comment by arouinfar** [comment]
Tagging #293 since this is a related change.
