### ISSUE TITLE
Use 1-indexing for atmosphere layers

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#309]
For #293 

In https://github.com/phetsims/tandem/issues/226 we decided to use 1-indexing for PhetioGroup going forward. 

We are using 0-indexing for the atmosphere layers. Should we use 1-indexing instead? I know these aren't a PhetioGroup, but if we follow the spirit of https://github.com/phetsims/tandem/issues/226, we should probably change things here too.

<img width="235" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/c274f499-0965-4bd6-86a0-eb154fc900d1">
<img width="209" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/a243cf1a-25a1-4a72-a81e-a6f57268e8ce">
 
 Another reason to move to 1-indexing is that it would be easier to coordinate between the layers in the tree and in the view. Currently, the first layer added to the atmosphere is Layer0, the 2nd layer is Layer1, etc. 
<img width="615" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/aabc8e9c-b411-4945-8801-c771287db93d">

That said, I may be comparing apples to oranges here. If there are good reasons to stick with 0-indexing, that's fine with me. I think 1-indexing is a bit more user-friendly in this case, but it's arguably only a small improvement.

**Comment by jbphet** [comment]
It's an easy change, so I went ahead and did it.  @arouinfar - please review and close if you're good with it.

**Comment by arouinfar** [comment]
Great, thanks @jbphet. Looks good in master, closing.
