### ISSUE TITLE
Add the flux meter

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#31]
The Photons and Model screens both have a Flux Meter that looks like this.

![image](https://user-images.githubusercontent.com/6396244/118037750-427f9800-b33c-11eb-95b4-054c7bf7efb9.png)

Adding it in this issue.

**Comment by jessegreenberg** [comment]
Initial commit made above. Still needs
- Make the sensor draggable.
- Impelement sensor behavior so that it detects flux of photons
- Add the WireNode that visually connects the sensor and the meter display.

**Comment by jessegreenberg** [comment]
Actually, @arouinfar is the sensor draggable, or is it locked in place? Does it need to be draggable? Making it fixed in place could be a way to significantly simplify accessibility work so just thought I would check.

**Comment by arouinfar** [comment]
@jessegreenberg the sensor is draggable because it is important for users to be able to sample at any altitude. Also note that while the sensor has a fixed visual width, it would be actually be sensing along a line that spans the entire width of the observation window.

**Comment by jessegreenberg** [comment]
I see, thanks @arouinfar. I see a comment in the design document that says "Probe doesn’t need to move left/right", is that still correct? Are there other requirements for this tool?

> Also note that while the sensor has a fixed visual width, it would be actually be sensing along a line that spans the entire width of the observation window.

Good to know, thank you! How does the arrow display work? There is a note that says "For a similar representation, refer to the Particle Flow Rate arrows in the Diffusion simulation". Should it be exactly like that and should I refer to code in that sim? Or are there any differences? In Diffusion is the arrow length showing "flux per unit time", what is making the arrow shrink in size when the barrier is initially removed?

**Comment by jessegreenberg** [comment]
Discussed during a meeting today - 
The sensor only needs to be dragged vertically, it will be locked in place horizontally in the center of the ObservationWindow.
The arrow representations won't behave exactly like Diffusion. It will depend how we implement the model. If we have a "Layers" approach, we might have the flux in/out at each layer and hen interpolate between each layer at the position of the sensor and represent those values.

**Comment by jessegreenberg** [comment]
I don't actually think there is more I can do here until the model is more fleshed out. We need the layers in place to interpolate between them. The basics of the UI are added and ready for further integration with the model so I think this can be closed.
