### ISSUE TITLE
Hiding controls in `sunlightPanel` and `infraredPanel` leaves the titles behind

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#311]
For #293 

On the Layer Model screen, hiding the contents of the Sunlight and Infrared panels leaves the titles behind:

<img width="181" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/972d5640-86d2-4348-9c10-9e0bf8427e69"> 

For example, setting `layerModelScreen.view.sunlightPanel.solarIntensitySlider.visibleProperty` to `false` leaves behind the "Solar Intensity" string.

Here's what the tree currently looks like:
<img width="248" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/22e2883d-8782-4d6a-8899-f2a6cf099997">  <img width="214" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/7b043cd7-9e40-4e8a-89b8-26eb5a649852">

I often see sliders as children of a control, such as the `planetControlNode` in Gravity and Orbits. 
<img width="190" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/31416cf6-deeb-4f8c-a3e5-993fdefacb01"> <img width="182" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/6d5e5d0a-3d0f-4b8b-864a-978b0451b36e">

Should we follow this pattern for the sliders and number picker in these panels? If so, the parent control should have a featured `visibleProperty` and we should unfeature the child `visibleProperty`.

**Comment by pixelzoom** [comment]
@arouinfar Yes, that's a good idea.  I won't be able to give this any attention until 7/5 at the earliest.

**Comment by pixelzoom** [comment]
SunlightPanel and InfraredPanel were a bit of a mess.  There was no encapsulation of the individual controls, and code for some of the controls was actaully interleaved.  So I factored out classes for each control:  SolarIntensityControl, SurfaceAlbedoControl, AbsorbingLayersControl, and InfraredAbsorbanceControl.   This is an implementation pattern that works well for PhET-iO, and provides superior encapsualtion for each control.

The Studio tree for the 2 panels is shown in the screenshots below.

@arouinfar please review in Studio, let me know if you have additional change requests.

@jbphet please review code changes, let me know if you have questions about this pattern.

Last person to review please close this issue.

<img width="259" alt="screenshot_2652" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/cc0cc2b0-cd19-4ed8-a8cd-d4042ec80bad">
<img width="272" alt="screenshot_2651" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/e56affa1-f197-42f2-b6c5-32b645b8fab8">

**Comment by pixelzoom** [comment]
> ... Can you please make these elements `phetioFeatured: true`? ...

Done. @arouinfar please review.

**Comment by jbphet** [comment]
Changes look very good, seems like a nice structure that works way better for phet-io.

One question for @arouinfar before closing: Do we just not worry about the fact that users can create useless empty panels?  Here's what I mean:

![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/c517f3fe-22a7-48f0-b7fb-0f9438941604)

**Comment by arouinfar** [comment]
> Do we just not worry about the fact that users can create useless empty panels?

With dynamic layout, panels automatically hide themselves when all children are hidden. My guess is that the autohide isn't working because the (uninstrumented) text is still visible. I don't really find the autohide behavior to be essential, though. If clients want to hide the panel, they should hide the panel.
