### ISSUE TITLE
Add `inputEnabledProperty` to `fluxSensor`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#312]
For #293 

The flux sensor is a movable probe. Clients may want to collect data at a particular altitude, so it would benefit from an `inputEnabledProperty`. 

- [x] Instrument `fluxSensor` in the view as a child of `view.observationWindow.fluxMeterNode` (if this is not possible, under `observationWindow` is also fine).
- [x] Instrument `fluxSensor.inputEnabledProperty`. This should automatically be `phetioFeatured: true` but if not, please feature it.
- [x] Add link to `model.fluxSensor` to the `fluxSensor` view element
- [x] Feature `model.fluxSensor` and `fluxSensor` view element so the link above is visible in the Featured tree
- [x] If `inputEnabledProperty` is `false`, hide the cueing arrows.

**Comment by pixelzoom** [comment]
In the above commits, I did the easy stuff -- the first 4 checklist items that @arouinfar specificed in https://github.com/phetsims/greenhouse-effect/issues/312#issue-1772013417.

@arouinfar please note that the view element will be named `fluxSensorNode`, not `fluxSensor`.

Onward to the more complicated part, which is:
> - [ ] If `inputEnabledProperty` is `false`, hide the cueing arrows.

**Comment by pixelzoom** [comment]
I believe that all requests are done. @arouinfar please review in master, close if OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, this all looks great! Closing.
