### ISSUE TITLE
`altitudeProperty` should have a finite range

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#313]
For #293 

Currently, `fluxSensor.altitudeProperty` has an infinite range, meaning its value can exceed the bounds visible in the simulation. Can we limit its range to match the bounds we set in the sim (750-49300 m)?

**Comment by pixelzoom** [comment]
@arouinfar please review in Studio.

@jbphet please review the code changes.

Last one to review, please close the issue.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good in master.

**Comment by jbphet** [comment]
Looks reasonable to me.  Closing.
