### ISSUE TITLE
Feature `fluxMeterNode`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#314]
For #293 

In https://github.com/phetsims/studio/issues/303 and https://github.com/phetsims/studio/issues/309 we made changes to the way LinkedElements appear in the Featured tree. LinkedElements will only appear in the Featured tree if their parent and target element are featured. As a result most common code components (such as checkbox) are featured in common code. 

In light of these changes, I took another pass through the tree to see if any LinkedElements with featured targets were being omitted from the Featured tree. The only one I identified is `fluxMeterNode` which has contains a link back to its `visibleProperty`. Here's what it currently looks like in the tree for All and Featured elements:
<img width="222" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/5e74b943-dca5-4193-9fac-184ebd614433"> <img width="206" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/8d2bed15-caa5-41d5-8676-0709e24bc53a">

@jbphet please feature `view.observationWindow.fluxMeterNode`.

**Comment by pixelzoom** [comment]
Done in the above commit. @arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
Looks good, thanks!
