### ISSUE TITLE
Change requests for temperatureUnitsSelector element

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#318]
This came up in a discussion with @arouinfar.  I volunteered to create the GitHub issue and will do the work.

The Layer Model screen has this control:

<img width="144" alt="screenshot_2653" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/bb4d5a29-a5b1-428d-88ed-a0a8c277d733">

Relevant part of the Studio tree:

<img width="326" alt="screenshot_2654" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/b6a41b44-2be2-454e-8920-f3a362f50925">

Change requests:

- [x] rename `temperatureUnitsSelector` to `temperatureUnitsControl`, to be consistent with naming convention in https://github.com/phetsims/greenhouse-effect/issues/311
- [x] feature  `temperatureUnitsControl.visibleProperty`
- [x] uninstrument `temperatureUnitsRadioButtonGroup.visibileProperty`

**Comment by pixelzoom** [comment]
Ready for review by `temperatureUnitsControl` by @arouinfar. Note that I did not feature `temperatureUnitsControl` because we did not feature the `*Control` elements added in #311.    Let me know if there are additional changes needed, feel free to close if OK.

**Comment by pixelzoom** [comment]
We have a similar case in the Preferences dialog:

<img width="114" alt="screenshot_2656" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/36e2fe0f-52cb-443a-9b7b-8e8abc449b22">

<img width="349" alt="screenshot_2655" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/3ff56948-caa5-4119-ada8-4a26a1c0a7f8">

**Comment by pixelzoom** [comment]
@arouinfar reaady for review.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. These changes all look great. The `temperatureUnitsSelector` appeared in examples.md, so I updated it to `temperatureUnitsControl` in the above commit. Closing.
