### ISSUE TITLE
Review options types

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#320]
There are many places where options types include fields that are not needed, or even downright dangerous.   In this issue, I'll narrow some of the options types, in preparation for code review.

**Comment by pixelzoom** [comment]
I think I addressed most of the issues here.  @jbphet please review, close if OK.

**Comment by jbphet** [comment]
The changes look good to me.  I had some questions about why @pixelzoom preferred `PickRequired` over `WithRequired` in many places, so he and I talked over Zoom, and I understand it and am on board.  Closing.
