### ISSUE TITLE
Inconsistent naming related to "Show Surface Temperature" checkbox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#323]
There's some inconsistency in the naming associated with this checkbox, and it's unfortunately exposed by PhET-iO:

<img width="214" alt="screenshot_2657" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/e2326d1d-b6b3-4445-b69e-01b0c2896788">

It is currently implemented in class `SurfaceTemperatureCheckbox`, with string `showSurfaceTemperatureStringProperty`, and tandem name `surfaceTemperatureCheckbox`.  So the "Show" bit is sometimes there, sometimes not there.

Options:

(1) Do nothing.

(2) Rename class `SurfaceTemperatureCheckbox` to `ShowSurfaceTemperatureCheckbox`, and tandem `surfaceTemperatureCheckbox` to `showSurfaceTemperatureCheckbox`

(3) Rename `showSurfaceTemperatureStringProperty` to `surfaceTemperatureStringProperty`, change its key to "surfaceTemperature", and change its value to "Surface Temperature".  (This string is not used in Molecules and Light, but might have been used in Greenhouse Effect prototype.)

@arouinfar what would you like to do?

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I vote for option (2). Naming this control has been tricky. I would prefer to keep it "Show Surface Temperature" in the sim, and update the class and tandem names to match.

**Comment by pixelzoom** [comment]
I discovered that there are 2 classes named SurfaceTemperatureCheckbox in greenhouse-effect:

* common/view/SurfaceTemperatureCheckbox.ts
* waves/view/SurfaceTemperatureCheckbox.ts

So the first thing to do here is investigate why there are 2 implementations.

**Comment by pixelzoom** [comment]
@arouinfar please review, close if OK.

<img width="303" alt="screenshot_2661" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/cb20386e-e8b6-47aa-8476-0892a277528e">

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom.
