### ISSUE TITLE
Performance testing and sign-off

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#328]
As part of the code review process for the release of the phet-io version of this sim, performance should be reviewed and approved by the designer(s).

**Comment by jbphet** [comment]
@KatieWoe and I just discussed how best to approach doing a performance test for this sim, and here's what we are currently thinking:
- @KatieWoe feels like collecting data for this is a reasonable task for QA
- I would like to collect a combination of both quantitative and subjective information on this, so I'll identify what I believe to be the worst case computational and rendering situation for each of the three screens and QA will profile them and also provide a subjective assessment
- I'll build a dev version and link it in this issue
- I'll add a table for the data, and QA can edit it as they collect the information
- I'll fill out the first row of the table with the information from my machine

**Comment by jbphet** [comment]
Worst cases for each of the three screens:
- "Waves" screen - Max greenhouse gas level, all the checkboxes checked, allow it to run for at least 30 seconds.  Screenshot: 
![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/80a3f6a3-0fdd-4852-b913-e49c2aeb11bd)
- "Photons" screen - Max greenhouse gas level, all the checkboxes checked,  let it run at least 30 seconds.  Screenshot: 
![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/40055d73-a1db-4f6c-99e8-821868370624)
- "Layer Mode" screen - All checkboxes checked, max solar intensity, min surface albedo, max layers, max IR absorbance, let it run at least 30 seconds: 
![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/83e55669-0688-48d5-98e7-5525bb0bf13e)

**Comment by jbphet** [comment]
The dev version has been built and can be found at https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.0-dev.1/phet/greenhouse-effect_all_phet.html.

**Comment by jbphet** [comment]
The table for collecting the performance data is below.  Here are some notes:
- Use the query parameter `profiler` to get the performance info to show up on the screen, and use the FPS value on the far left.  It will look something like this: 
![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/ef4fc72c-0bbc-49d9-a6f4-9a4f0bbb7e4b)
- WC stands for "Worst Case", meaning the cases described above
- In the headings, I shortened "Layer Model" to "Layers" for the 3rd screen
- For the "Usable" heading, use only "yes", "no", or "marginal".  This is the tester's subjective assessment.
- The first row is from my development machine.

**Comment by jbphet** [comment]
| Device  | Browser | Waves WC FPS |  Waves WC Usable? |  Photons WC FPS |  Photons WC Usable? | Layers WC FPS | Layers WC Usable? |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: 
| @jbphet's Dell Precision | Chrome | 60  | yes  | 60  | yes  | 60  | yes  |
| Device X  | ? | ? | ?  | ?  | ?  | ?  | ?  |

**Comment by jbphet** [comment]
Assigning to @KatieWoe and @Nancy-Salpepi for the next steps.

**Comment by Nancy-Salpepi** [comment]
| Device  | Browser | Waves WC FPS |  Waves WC Usable? |  Photons WC FPS |  Photons WC Usable? | Layers WC FPS | Layers WC Usable? |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: 
| @jbphet's Dell Precision | Chrome | 60  | yes  | 60  | yes  | 60  | yes  |
| macbook air  | safari | 60 | yes  | 60  | yes  | 60 | yes  |
| 2003 mac desktop  | safari | 60 | yes | 60  | yes | 60  | yes  |
| iPad (9th gen)  | safari | 30 | yes  | 30  | yes  | 30  | yes  |


* I waited 30 seconds and then took an average of the first 5 numbers for FPS.

**Comment by KatieWoe** [comment]
| Device  | Browser | Waves WC FPS |  Waves WC Usable? |  Photons WC FPS |  Photons WC Usable? | Layers WC FPS | Layers WC Usable? |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: 
| @jbphet's Dell Precision | Chrome | 60  | yes  | 60  | yes  | 60  | yes  |
| Samsung Win 11  | Firefox | ? | ?  | ?  | ?  | ?  | ?  |

**Comment by KatieWoe** [comment]
Between @Nancy-Salpepi and I, I think think this is enough data. @jbphet back to you

**Comment by jbphet** [comment]
Thanks QA team!

Based on the data above, it looks like QA found the worst case situations for each of the three screens usable on all test devices.  @arouinfar - as the designer, I think it is up to you to ultimately sign off on this, though you're welcome to bring in @kathy-phet if you like.

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi @KatieWoe! 

Performance is generally looking good, with lower-performing devices still being acceptable. I'm happy to close @jbphet.
