### ISSUE TITLE
Review pointer areas

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#329]
The pointer areas should be reviewed as part of the code review effort.

**Comment by jbphet** [comment]
I thought we had done this already when we published the prototype, but when I went through the sim it looked like most of the touch areas were at their default values.  I ended up expanding a number of them with the intent of making the sim easier to use on touch-based devices.

@arouinfar - Please review, and let me know what changes you'd like to see.  If it's good as is, feel free to close.  You can compare to the published version if you want to see how things have changed.

**Comment by arouinfar** [comment]
Thanks @jbphet. I reviewed on master, and everything looks good. Closing.
