### ISSUE TITLE
Should query parameter `defaultTemperatureUnits` be public?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#332]
For code review https://github.com/phetsims/greenhouse-effect/issues/331 ...

> - [ ]  Query parameters that are public-facing should be identified using `public: true` in the schema.

Should query parameter `defaultTemperatureUnits` be `public: true`?  It has a control in the Preferences dialog.

**Comment by arouinfar** [comment]
Yes, it should be public.
