### ISSUE TITLE
IE workaround in PhotonEmissionSoundGenerator.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#333]
For code review https://github.com/phetsims/greenhouse-effect/issues/331 ... 
> - [ ] IE is no longer supported. With that in mind remove IE-specific workarounds

I see these 2 workarounds in PhotonEmissionSoundGenerator.ts:

```ts
    // Note - can't use initialization constructor for Map due to lack of support in IE.
    const photonInitialEmissionSoundPlayers = new Map();
...
    // Note - can't use initialization constructor for Map due to lack of support in IE.
    const photonEmissionFromMoleculeSoundPlayers = new Map();
```

I think it's fine the way it is, but wanted to point it out in case @jbphet wants to initialize the Map when it's instantiated.

**Comment by jbphet** [comment]
Workaround removed, and the code now uses the `Map` constructor to set initial values.  Closing.
