### ISSUE TITLE
Unnecessary coupling

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#339]
For code review https://github.com/phetsims/greenhouse-effect/issues/331 ...

> - [ ]  Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions). ...

This sim is generally good about not having unnecessary coupling.   But here are a few places to improve.

---

- [x] ObservationWindowPDOMNode is provided with the entire `model: LayersModel`. But all that is needed is `model.sunEnergySource.isShiningProperty`. 

- [x] ThermometerAndReadout is provided with the entire `model: LayersModel`.  But it really should be limited to temperature-related aspects of the model.  Two ways to do that: (1) pass only the 5 Properties needed to the constructor, or (2) group the temperature-related Properties in the model, and pass only that group to the constructor.

- [x] ShowSurfaceTemperatureCheckbox is provided the entire `model: ConcentrationModel` but requires only 3 Properties. It would be better to pass those 3 Properties as constructor parameters.

- [x] WavesCanvasNode is provided the entire `model: WavesModel` when all it needs is `model.waveGroup`.

- [x] Does RadiationDescriber needed  `model: LayersModel`? I don't see it used anywhere.  But I'm not at all familiar with how describers work.

**Comment by jbphet** [comment]
I've addressed the items listed above, and it seems like an improvement to the code.  Closing.
