### ISSUE TITLE
Uninstrument Text and RichText

### ISSUE THREAD

**Issue by zepumph** [phetsims/greenhouse-effect#341]
In https://github.com/phetsims/phet-io/issues/1952#issuecomment-1664495275 we decided that we generally don't want to instrument Text nodes, and instead just want to focus on the stringProperties, especially if they are derived or pattern. 

- [x] Let's double check that sim code isn't instrumenting Texts unless there is a reason (like hiding the Text).
- [x] Let's also look for common code UI that needs to be generally updated to support this new PhET-iO instrumented decision. (For example Natural Selection dealt with NumberDisplay and OopsDialog)

**Comment by arouinfar** [comment]
@jbphet please uninstrument these elements:

- [ ] `view.observationWindow.startSunlightButton.text`
- [ ] `view.observationWindow.surfaceThermometer.comboBox.items` is a container for text-related elements and can be uninstrumented

I identified NumberDisplay and TimeControlNode as the common code elements that need to be addressed. NumberDisplay will be handled in https://github.com/phetsims/scenery-phet/issues/812. I will open a separate issue for TimeControlNode. @jbphet these issues do no block dev testing of Greenhouse Effect, but should be addressed before RC.
* `layerModelScreen.view.observationWindow.atmosphereLayer*.temperatureReadout.valueText` 
* `layerModelScreen.view.observationWindow.surfaceThermometer.temperatureReadout.valueText` 
* `timeControlNode.speedRadioButtonGroup.*RadioButton.labelText`

**Comment by arouinfar** [comment]
> NumberDisplay will be handled in https://github.com/phetsims/scenery-phet/issues/812

Actually, @jbphet I think we can uninstrument the NumberDisplays used on the Layer Model screen instead.

**Comment by jbphet** [comment]
I've done some of these, but have questions on some.  I'll request some time with @arouinfar, and I think we'll be able to finalize this pretty quickly.

Worthy of note: I'm not doing anything in the GE code to instrument `view.observationWindow.startSunlightButton.text`, it's happening in `TextPushButton.ts`.

**Comment by jbphet** [comment]
Before these requests can be fully addressed, we need to have resolutions to the following common code issue, and they need to be included the the RC branch:

- [ ] https://github.com/phetsims/scenery-phet/issues/813
- [ ] https://github.com/phetsims/sun/issues/850

**Comment by jbphet** [comment]
@arouinfar - Can you check whether we've addressed all of these?  I've looked it over some and I think we have gotten rid of most if not all of the instrumented text, but you know more about it than I.

**Comment by arouinfar** [comment]
@jbphet I reviewed on master, and things are looking great. I couldn't find any extraneous instrumentation of Text/RichText, closing.
