### ISSUE TITLE
CT: Uncaught Error: Assertion failed: Designed API changes detected...

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#342]
Yesterday, with help from @zepumph, I add the `phetioDesigned` flag to the top level tandem of this sim and added the `"compareDesignedAPIChanges": true` flag to the `package.json` file.  This is part of the phet-io development process, and essentially says that the phet-io API for the sim has been finalized and should thus be checked for potentially unintentional changes.

Now, CT is failing with an error due to this check.  I thought it might be a quick fix, but after a little investigation it looks like it might not be, so I'm logging an issue.

Error output:

<details>

```
greenhouse-effect : phet-io-api-compatibility : unbuilt
http://128.138.93.172//continuous-testing/ct-snapshots/1691170432943/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1691170432943%22%2C%22timestamp%22%3A1691171377248%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

greenhouseEffect.layerModelScreen.model.fluxMeter.wireMeterAttachmentPositionProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"x":29278.91156462585,"y":43469.38775510205}}
actual:
{"value":{"x":29170.06802721088,"y":43469.38775510205},"validValues":null,"units":null}

greenhouseEffect.photonsScreen.model.fluxMeter.wireMeterAttachmentPositionProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"x":29278.91156462585,"y":43469.38775510205}}
actual:
{"value":{"x":29170.06802721088,"y":43469.38775510205},"validValues":null,"units":null}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1691170432943/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:371:22)
[URL] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1691170432943%2Fgreenhouse-effect%2Fgreenhouse-effect_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1691170432943%22%2C%22timestamp%22%3A1691171377248%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1691170432943%2Fgreenhouse-effect%2Fgreenhouse-effect_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1691170432943%22%2C%22timestamp%22%3A1691171377248%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1691170432943/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1691170432943%22%2C%22timestamp%22%3A1691171377248%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
[CONSOLE] enabling assert
[CONSOLE] Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

greenhouseEffect.layerModelScreen.model.fluxMeter.wireMeterAttachmentPositionProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"x":29278.91156462585,"y":43469.38775510205}}
actual:
{"value":{"x":29170.06802721088,"y":43469.38775510205},"validValues":null,"units":null}

greenhouseEffect.photonsScreen.model.fluxMeter.wireMeterAttachmentPositionProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"x":29278.91156462585,"y":43469.38775510205}}
actual:
{"value":{"x":29170.06802721088,"y":43469.38775510205},"validValues":null,"units":null}

[PAGE ERROR] Error: Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

greenhouseEffect.layerModelScreen.model.fluxMeter.wireMeterAttachmentPositionProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"x":29278.91156462585,"y":43469.38775510205}}
actual:
{"value":{"x":29170.06802721088,"y":43469.38775510205},"validValues":null,"units":null}

greenhouseEffect.photonsScreen.model.fluxMeter.wireMeterAttachmentPositionProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"x":29278.91156462585,"y":43469.38775510205}}
actual:
{"value":{"x":29170.06802721088,"y":43469.38775510205},"validValues":null,"units":null}

at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1691170432943/assert/js/assert.js:28:13)
at XMLHttpRequest.<anonymous> (http://128.138.93.172//continuous-testing/ct-snapshots/1691170432943/chipper/dist/js/phet-io/js/phetioEngine.js:303:23)
[CONSOLE] continuous-test-load
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 8/4/2023, 11:33:52 AM
```

</details>

**Comment by jbphet** [comment]
Slack dialog with @zepumph on this:

> @jbphet (11:39 AM)
> You around?  CT is failing due to the changes you helped me make yesterday, but I can't reproduce it locally, and could use some help sorting it out.
> 
> @zepumph (11:43 AM)
> I see it! I have a meeting in just a few that I really need to prep for, but this has happened a few times before and we have punted. Basically it is about cross browser rounding errors (10th decimal place kinda stuff). https://github.com/phetsims/phet-io/issues/1951
> 
> @jbphet (11:46 AM)
> Okay, interesting.  When you say "punted" I'm not sure what that means or now to address it, and I just scanned the issue and don't see that info there either.  I'm not okay with "punted" meaning the GE will be red in CT from now on, so I'm not sure where to go from here.  It sounds like you're busy at the moment, shall I put something on the calendar for later in the day, or is there a quicker solution?
> 
> @zepumph (11:54 AM)
> There is a quick solution but I hate it, and NS has been red for a few weeks now (since I added safari browser testing to CT). because I'm stubborn. Do you have an issue and I will try to make a quick solution happen this afternoon.

**Comment by jbphet** [comment]
Assigning to @zepumph based on his request above.

**Comment by zepumph** [comment]
Upon a bit more research, This stateful Property is being set here:

https://github.com/phetsims/greenhouse-effect/blob/b3365020fa4013b7d82ea5364a1105d8d3cce8cb/js/common/view/GreenhouseEffectObservationWindow.ts#L303-L306

The initial state committed in the reference API has its x position as: 
`29278.91156462585`
but when failing, the x position is 
`29170.06802721088`


I'm not really sure if this is as related to https://github.com/phetsims/phet-io/issues/1951 as I originally thought, though it could be part of the problem. 


With this patch, I was able to confirm that locally, puppeteer doesn't fail this test, but when I run the same puppeteer link on sparky we do get the same CT error.


```diff
Subject: [PATCH] patch
---
Index: js/local/puppeteerHelpCT.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/local/puppeteerHelpCT.js b/js/local/puppeteerHelpCT.js
--- a/js/local/puppeteerHelpCT.js	(revision 3e009fa197e91304c345405ad40e4260ba8a366c)
+++ b/js/local/puppeteerHelpCT.js	(date 1691180446069)
@@ -16,7 +16,7 @@
   assert( process.argv[ 2 ], 'usage: node puppeteerHelpCT {{SOME_IDENTIFIER_HERE}}' );
   while ( true ) { // eslint-disable-line no-constant-condition
 
-    await puppeteerLoad( `https://sparky.colorado.edu/continuous-testing/aqua/html/continuous-loop.html?id=localPuppeteer${process.argv[ 2 ]}`, {
+    await puppeteerLoad( 'http://localhost:8080/greenhouse-effect/greenhouse-effect_en.html?brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*&keyboardLocaleSwitcher&ea&debugger', {
       waitAfterLoad: 100000,
       logConsoleOutput: true,
       logNavigation: true,
```

Both my machine and Sparky are all using the same puppeteer version.

**Comment by jbphet** [comment]
Well, this does seem to have cleared up the CT error, but I concur that it's a pretty "hacky and horrible" solution.  I'm trying to get this sim into dev and then RC testing, so I'd like a recommendation from the phet-io team as to whether it is okay to publish a sim - including the phet-io version - with this workaround in place, or whether we should invest time in a more sustainable solution.

I just checked the shared calendar, and it looks like @zepumph is out this week.  @samreid - what do you recommend here?

**Comment by jbphet** [comment]
Thanks @samreid.  Based on this information I'm going to close this issue, since https://github.com/phetsims/phet-io/issues/1951 is open and sounds like the issue under which a more robust solution will eventually be explored.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by jbphet** [comment]
Well okay then.  I guess I'll leave this open an unassigned since the ["hacky and horrible workaround"](https://github.com/phetsims/chipper/commit/8cbfdbd1f0a8faa67ec693d9da8f8f9683f3cf30) the removes this error from CT includes a TODO that references this issue.

**Comment by jbphet** [comment]
I updated the comment that references this issue to point to the more general issue https://github.com/phetsims/phet-io/issues/1951.  I did this because I found it confusing to have a CT issue open long after the original problem had been resolved.  I'm going to go ahead and close this one.
