### ISSUE TITLE
PhET-iO id for hiding temperature radio buttons incorrect in examples.md

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#350]
For https://github.com/phetsims/qa/issues/970

In the examples doc under **Control Temperature Units** >> **Layer Model Screen** the PhET-iO id to hide the temperature radio buttons is listed as: 
`greenhouseEffect.layerModelScreen.view.temperatureUnitsControl.temperatureUnitsRadioButtonGroup.visibleProperty`
but in the studio tree, the buttons are hidden using:
`greenhouseEffect.layerModelScreen.view.temperatureUnitsControl.visibleProperty`

**Comment by arouinfar** [comment]
Good catch @Nancy-Salpepi! I fixed it in the above commit, closing.

 This is another example where https://github.com/phetsims/phet-io-sim-specific/issues/21 would be helpful.
