### ISSUE TITLE
Odd font for Celsius and Fahrenheit with Win10 + Chrome

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#354]
For https://github.com/phetsims/qa/issues/970, the font for Celsius and Fahrenheit is different than Kelvin in Win + chrome. 
I don't see this with mac + chrome/safari or win + FF. 

Win10 + Chrome:
 
![units1](https://github.com/phetsims/greenhouse-effect/assets/87318828/b9b56376-5e9e-4e57-9d84-74621c1eea8d)
![units2](https://github.com/phetsims/greenhouse-effect/assets/87318828/65e90765-bd22-4c76-b8d2-2c30f3c886bd)

Mac + Chrome:
<img width="265" alt="Screenshot 2023-08-16 at 5 23 49 PM" src="https://github.com/phetsims/greenhouse-effect/assets/87318828/ce31c177-6741-43c3-b7b8-eded6676475a">

**Comment by jbphet** [comment]
I believe this is due to the fact that I'm using single unicode characters for "degrees Celsius" and "degrees Fahrenheit".  I could change this to be two separate characters, since I just checked and there is a separate character for degrees.  It may not look quite as compact, but will be more consistent.

**Comment by jbphet** [comment]
I went ahead and changed this on the main branch, and I can see the difference on my machine.  Below are some screenshots.

Before:

![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/6f7d7673-7524-4e1e-b2c7-f24b43bf02aa)

![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/52a7a60e-3e9c-447b-8802-5fceff08dbd6)

After:

![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/a4b4fa66-19e1-4e37-8d98-b9993f528bb3)

![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/25391918-1e3d-43ee-964f-d979b12d6065)

**Comment by jbphet** [comment]
I just reviewed this with @arouinfar over Zoom, and she and I agree that this seems like an improvement.  I'll need to change it in the previously submitted translation files too.

**Comment by jbphet** [comment]
This has been fixed for all existing translations as of this moment.

- [ ] Note to self: Check for single-char versions of these units in translations just before publishing, since some could sneak in between now and then.

**Comment by jbphet** [comment]
QA - Feel free to close once verified.

**Comment by KatieWoe** [comment]
Things looked good on Win 11 Chrome and Firefox. Will reopen if anything shows up in other platforms.
