### ISSUE TITLE
Add "Toggle Checkboxes" to Keyboard Shortcuts Dialog

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#355]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/973, the Keyboard Shortcuts Dialog should have  "Toggle checkboxes" included in it. 
This is a currently a manual step that needs to be taken by the developer (see Slack conversion below).

**From Slack:**
Amy Rouinfar
[@jessegreenberg](https://phetsims.slack.com/team/U6ELY17N3) is options.withCheckboxContent something a sim dev needs to be in charge of? Or is an automatic thing handled by common code? (edited) 

Jesse Greenberg
It is a manual step now, there currently isn't a way to auto detect if the sim is using a checkbox.

Amy Rouinfar
Thanks [@jessegreenberg](https://phetsims.slack.com/team/U6ELY17N3)! 
[@Nancy Salpepi](https://phetsims.slack.com/team/U027AF93XE1) can you include this in the Greenhouse issue, please?

Jesse Greenberg
> Is that something that should always be included for sims that have keyboard nav + checkboxes?

Yes, I believe so!

**Visuals**
Here is what it looks like in Quadrilateral as a result of https://github.com/phetsims/quadrilateral/issues/431:
<img width="468" alt="Screenshot 2023-08-23 at 2 21 32 PM" src="https://github.com/phetsims/greenhouse-effect/assets/87318828/71f3f28e-0e96-4a25-8c50-52278150123c">

**Comment by jbphet** [comment]
Added to main and cherry-picked into the 1.2 branch.  Note that this only appears in the keyboard help dialogs for the sim screens and not for the home screen since there are no checkboxes there.

**Comment by jbphet** [comment]
QA - feel free to close when verified.

**Comment by Nancy-Salpepi** [comment]
"Toggle checkboxes" has been added to rc.2. Closing.
