### ISSUE TITLE
Add instructions to change default temp when limiting options in listBox

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#357]
As we discussed on zoom, when removing a temperature unit from the listBox, it is important to tell instructional designers to make sure that unit is not set as the default in the Preferences Menu. 

 For example, if I set `greenhouseEffect.wavesScreen.view.observationWindow.surfaceThermometer.comboBox.listBox.celsiusItem.visibleProperty` 
to false, but don't change the default units, pressing reset all will result in the ℃ unit being displayed on Reset All.

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi. I updated the examples doc in the above commit.

@jbphet this will need to be cherry-picked into the release branch.

**Comment by jbphet** [comment]
I created the branch, cherry picked the commit, and updated the dependencies.  We should be good to go on this.  I'll have QA validate in the next round of testing.

**Comment by jbphet** [comment]
QA - feel free to close when verified.
