### ISSUE TITLE
New flux meter behavior

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#360]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/973. I noticed a difference in behavior between the published sim and the rc. While neither behavior strikes me as a problem, I wanted to be sure the change was either intentional or acceptable. When moving the Flux Meter rod while the sim is paused the behavior of the graph has changed. In published the old reading would stay up until the sim was played or stepped forward. Now the graph clears until the sim is played or stepped forward. Between the two I think the current behavior is better.
**Steps to reproduce**
1. Go to the second or third screen
2. Start the sim
3. Turn on the flux meter
4. When the graph starts showing results, pause the sim
5. Move the bar for the flux meter
6. Step the sim forward

**Visuals**
Published

https://github.com/phetsims/greenhouse-effect/assets/41024075/ea70119a-27a8-4efb-a6f6-2bc11c187285

RC

https://github.com/phetsims/greenhouse-effect/assets/41024075/feeeea6a-834e-46e4-9326-d17c5aa5793b

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.2.0-rc.1 2023-08-22 22:02:09 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language: en-US
Window: 1536x707
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe! 

> Between the two I think the current behavior is better.

I agree. I think it's preferable to clear the Energy Flux data.

@jbphet I almost closed this issue but decided to leave it open on the off-chance that there's something unintentional going on (albeit with desirable consequences).

**Comment by jbphet** [comment]
Yes, the behavioral change her was intentional, see the second bullet item in https://github.com/phetsims/greenhouse-effect/issues/188.  Closing.
