### ISSUE TITLE
PhET-iO deserialization is broken because of private state

### ISSUE THREAD

**Issue by zepumph** [phetsims/greenhouse-effect#361]
In https://github.com/phetsims/greenhouse-effect/commit/4aa3a7c7026af155e6879868251a3a3400df90f7 many items of state were changed to `_` prefixed, but that broken the state objects since that changed the state object keys directly.

I'll take a look, because either typescript or the state wrapper should have been able to catch this, but instead we only got this from the migration wrapper (after publication).

**Comment by zepumph** [comment]
- [ ] Why doesn't the state wrapper catch this problem? Right now we never get the state out of the sim that is having the state set onto it (hence why we only found this in the migration wrapper).


This patch did NOT work to reproduce the error like the migration wrapper.

<details>

```diff
Subject: [PATCH] temp
---
Index: state/index.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/state/index.html b/state/index.html
--- a/state/index.html	(revision c13f023e02d44d26b65a206f378189937998c3a9)
+++ b/state/index.html	(date 1694196610341)
@@ -191,7 +191,8 @@
 
     // set the state from the source to the destination
     startTime = Date.now();
-    destinationClient.invoke( 'phetioEngine', 'setState', [ state ], () => {
+    destinationClient.invoke( 'phetioEngine', 'setState', [ state ], async () => {
+      await destinationClient.invokeAsync( 'phetioEngine', 'getState' );
       currentlySettingState = false;
       queryParameters.logTiming && console.log( `Setting the state took ${Date.now() - startTime} ms.` );
     } );

**Comment by zepumph** [comment]
This has been published. Ready to close.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
