### ISSUE TITLE
Update context response for Show Surface Temperature checkbox

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#363]
In #211 we removed the reference to the "glow" in the help text of the Show Surface Temperature checkbox due to the interpretation that it only affects the visual representation. However, we overlooked the context response which still refers to "glow".

In the 10/5/23 design meeting, we agreed to re-write the context response. @Matthew-Moore240 and I discussed further and settled on: Surface temperature scale hidden.

Assigning to @jbphet, but deferring until development resumes.

**Comment by jbphet** [comment]
Done, closing.
