### ISSUE TITLE
Update Flux Meter Altitude slider step sizes

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#367]
Currently, it takes 30 key presses at the standard step size to travel the full range of the Flux Meter Altitude slider. This level of granularity is unnecessary.

For the **Photons** screen, let's use these steps sizes instead:
- [x] Default step: 10%
- [x] Smaller steps (shift): 5%
- [x] Larger steps (page up/down): 20%

For the **Layer Model** screen, there is no evenly-sized interval we can specify that would avoid collision with the layers. The probe will bump above/below the layer on collision, so this will create problematic situations for description. In the 8/5/23 design meeting, we discussed steps that would look something more like this:
![image](https://github.com/phetsims/greenhouse-effect/assets/8419308/04d2a91d-a23b-42de-b0b2-f3cb5545b015)

I used Studio to find the approximate altitudes for these magenta lines, using the "snap-to" values just above/below the layers used for mouse interaction.
- [x] Default step: [750, 5525, 10300, 14700, 18750, 22800, 27200, 31250, 35300, 39700, 44500, 49300] m
- [x] Smaller steps: N/A (same as default)
- [x] Larger steps: traverse every-other value in array 
- [x] Default value: 4625m

Regardless of how many layers are currently in the atmosphere, we would use these same steps. The benefit of these values is that we avoid collisions with the layers when present. 

Assigning to @jbphet but deferring until development resumes.

**Comment by jbphet** [comment]
@arouinfar - This is implemented on main.  Please check out the behavior and close if it seems good to you.

**Comment by arouinfar** [comment]
@jbphet something's not right on main. I pulled all and cleared my cache before testing.

On the Photons screen, everything seems off by a factor of 2. The standard step is 5% when it should be 10%, the page up/down steps are 10% when they should be 20%. I didn't count the total number of shift steps, but it's obviously smaller than 5%. I can see in https://github.com/phetsims/greenhouse-effect/commit/77582d10da9b93e1f981fc14359204813d9b6414 that you are dividing the total range by 5, 10, or 20, so I'm not sure what's going on.

On the Layer Model screen, I'm experiencing a lot of collisions with the layers and it seems like the step size is an even 5% all the way up.

**Comment by jessegreenberg** [comment]
I just confirmed this. It behaves OK in 1.3.0-dev.2 which was pretty recent so Ill see if I can find how this changed.

**Comment by jessegreenberg** [comment]
OK, it was a bit of turbulence in common code from progress for the description prototype. Main is behaving correctly again @arouinfar.

**Comment by arouinfar** [comment]
Thanks for the quick fix @jessegreenberg! Everything looks good on main now, closing.
