### ISSUE TITLE
Add description for the Photons screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#368]
Adding description for the Photons and Waves screens has now become a priority.

See spec at https://docs.google.com/document/d/1fwQevMR-qYZ08a0y2B0FmFEjUgZfNAUBrrY6KKPWLSo/edit for the details of how this should behave.

**Comment by jessegreenberg** [comment]
Making a list of things to remaining for the photons screen from going through the spec:

- [ ] Move the "flux meter" content below the observation window list in the PDOM order.
- [ ] Add "Energy Legend" list content back (and fix in the waves screen)
- [ ] Update the context responses when concentration changes (both slider and radio buttons) to refer to photons (See Greenhouse Gas Concentration, Slider in design doc).
- [ ] Move "Energy Balance" state descriptions into the observation window.
- [ ] Finish the flux meter slider descriptions.
- [ ] Context response for the "More Photons" checkbox.

(This completes state description, more to check for context responses)

**Comment by jbphet** [comment]
@jessegreenberg, @jonathanolson, and I have gone through the spec and we think the initial implementation of this is now complete.  @arouinfar - over to you for review.

**Comment by arouinfar** [comment]
During review, I identified two issues which were addressed in https://github.com/phetsims/greenhouse-effect/commit/09a1d69bf0938315ca62d72144600c406a4b0286 and #367. There's nothing else left to do for this issue, closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by arouinfar** [comment]
Reassigning to @jbphet to address the TODO that caused this issue to be automatically reopened.

**Comment by jbphet** [comment]
I've addressed the TODO, and it actually did improve the code, which is a bit of a testament to the automatic reopening system.  Closing.
