### ISSUE TITLE
CT: accessed value outside of dependency tracking

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#370]
A CT error has popped up for this sim.  I duplicated the problem locally, looked through the (wildly complicated) stack trace and found that the problem was occurring while the sim was starting up and trying to position a Scenery Node instance.  Since I don't think I'd changed anything related to layout a while I thought I'd investigate common code.  It looks like the error message itself was added recently in https://github.com/phetsims/axon/commit/96122725e6c20ec990f4407ea9bcc495b19f7b48.  This commit was added by @samreid, assigning to him to investigate.

**Comment by samreid** [comment]
Fixed in https://github.com/phetsims/sun/commit/f7584619392461ed2ed30f35fe60be75d759eb62. Closing.
