### ISSUE TITLE
Update phrases that describe IR interaction with ground and atmosphere for the Photons screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#371]
As of this writing the Photons screen is describing the IR behavior using the terminology that was used for the Waves screen.  This needs to be updated for the Photons screen.  [The spec](https://docs.google.com/document/d/1fwQevMR-qYZ08a0y2B0FmFEjUgZfNAUBrrY6KKPWLSo/edit#heading=h.nhqxjbby3dgu) describes the needed changes.

Parent issue for this is #368.

**Comment by jbphet** [comment]
This has been implemented.  @arouinfar - please review the behavior on master.

**Comment by arouinfar** [comment]
@jbphet I'm not 100% sure what aspect of the description you would like me to verify. I believe it's the couplet related to infrared radiation/photons that's triggered when the greenhouse gas concentration changes. The behavior on main looks correct to me.

Waves Screen:
{{More/Less}} infrared {{radiation}} redirecting back to surface.
{{More/Less}} infrared {{radiation}} emitting from surface.

Photons Screen:
{{More/Fewer}} infrared {{photons}} redirecting back to surface.
{{More/Fewer}} infrared {{photons}} emitting from surface.

Is there anything else that needs to be reviewed for this issue @jbphet?

**Comment by jbphet** [comment]
Sounds good, closing.
