### ISSUE TITLE
Remove date argument from getQualitativeTemperatureDescriptionString

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#372]
This function is used in lots of places but the date argument isn't used. Lets remove it and update usages.

**Comment by jbphet** [comment]
This is an older issue, and I just checked and can see that there is no longer a `date` argument in `getQualitativeTemperatureDescriptionString`, and all of the current parameters are being used.  I think this must've gotten fixed along the way.  Closing.
