### ISSUE TITLE
Consider restructuring a11y strings

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#373]
Consider moving some of the nested "waves" strings out. Particularly from the "screenSummary" key. They are now shared by the "photons" screen and so the nesting doesn't reflect the usage which is confusing. This doesn't impact functionality but would improve maintainability, so consider this if there is time.

**Comment by jbphet** [comment]
For the record, I did some restructuring of these strings while working on https://github.com/phetsims/greenhouse-effect/issues/374 to move shared strings out from under the "waves" key to the general "a11y" key.

**Comment by jbphet** [comment]
I've moved the string keys that are now command and were subkeys of `a11y.waves.screenSummary` to be under the more general `a11y` key.  I did a bit more generalization as well, and I think I'm ready to close this issue.  We don't really have any standards for how to structure the a11y strings, and it seems like the structure isn't used much anyway - we mostly just search through the file.  So...closing.
