### ISSUE TITLE
Add description for the Layer Model screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#374]
Description for the Photons screen is nearing completion, and the spec is ready for the developers to start implementation of description in the Layer Model screen.

See spec at https://docs.google.com/document/d/1lkpnGpLhbvjRphW5bITHLGyKsj-OGq4WWO98ZM2wKVM/edit?usp=sharing for the details of how this should behave.

**Comment by jbphet** [comment]
@arouinfar, @jessegreenberg, and I had a review meeting today where we went through a set of questions that @jessegreenberg and I had written up in the spec.  The resulting list of to-do items can be found in https://github.com/phetsims/greenhouse-effect/issues/375.

**Comment by jbphet** [comment]
@arouinfar - @jessegreenberg and I have worked through the spec and believe we have covered most everything.  I'm assigning this issue to you to start the review.  There is one known issue, listed in #375, about the surface and the layers reporting that they've reached equilibrium several times in rapid succession.  Please ignore that problem for now, and we will work on it in parallel with your review.

I've published a dev version for you to use for the review so that you're not working with a moving target.  Please see https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.0-dev.2/phet/.

**Comment by jbphet** [comment]
Unassigning myself since I've now resolved the problems related to equilibrium.  I'll address issues resulting from the review of the Layer Model screen description as they arise.

**Comment by arouinfar** [comment]
Layer Model review is complete. I identified a few issues, all tagged above, so closing this issue.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by arouinfar** [comment]
@jbphet this issue was automatically reopened due to a TODO, so back to you.

**Comment by jbphet** [comment]
The TODO said, in part, "Next add the context response for the value change", and it was referring to the sunlight intensity.  That was definitely added when the alerter for the Layer Model was created, so it is now safe to simply remove this TODO.  Done, re-closing.
