### ISSUE TITLE
console.log in LayerModelModelAlerter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#377]
LayerModelModelAlerter has a console.log:

```ts
    model.atmosphereLayers[ 0 ].atEquilibriumProperty.link( atEquilibrium => {
      console.log( `layer 1 atEquilibrium = ${atEquilibrium}` );
    } );
```

If you want to keep this code, it would be more appropriate to use `phet.log && phet.log( '...' );`

**Comment by jbphet** [comment]
This was some debug code that I was using to improve the behavior of the equilibrium state, but I'm happy to get rid of it if it's troubling people.  It's gone.  Closing.
