### ISSUE TITLE
Omit starting "A" in the description of amount of IR emitted in Observation Window

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#380]
Related to #374 

The list in the Observation WIndow contains a bullet that states:
> A {{very high, low}} amount of infrared photons emit from surface and travel to space. 

This can sound very awkward when the value is preceded by "extremely" or "exceptionally".

@jbphet can we delete the "A" from the start of the sentence? This would apply to all screens since I believe they use the same string.

**Comment by jbphet** [comment]
Done.  @arouinfar - please check it out on main and close if it looks good.

**Comment by arouinfar** [comment]
Looks good on main, thanks!
