### ISSUE TITLE
Add context response for changing temperature units when Surface Thermometer is unchecked

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#382]
Related to #374 

When changing the temperature units, there is a context response that reads out the current surface temperature in the selected units. This works very well for the Waves/Photons screens where it is only possible to change the units when the thermometer is visible. However, the Layer Model Screen has separate checkboxes for the surface and atmospheric layers, so there is a global temperature units control that is always visible.

On main, changing the temperature units on the Layer Model will read out the surface temperature, even if the surface thermometer is unchecked. This seems buggy.
![image](https://github.com/phetsims/greenhouse-effect/assets/8419308/19c4a959-c284-4776-a29f-c5b77d0aee0f)

We need an alternative context response for when Surface Thermometer is unchecked. Discussed with @jbphet and we'd like to go with: Temperature units {{value}}. For example, "Temperature units degrees Celsius."

Over to you @jbphet.

**Comment by jbphet** [comment]
Good catch @arouinfar!  I've added a new description for the situation you've described.  Please check it over on main and close if it fits the bill.

**Comment by arouinfar** [comment]
Looks good, thanks @jbphet! Closing.
