### ISSUE TITLE
Create a dev version suitable for interviews focused on the description feature

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#384]
For the current development iteration @arouinfar and I have been tasked with getting a version of this sim ready for interviews that are focused on the description feature.  This feature was recently implemented for the Layer Model screen (see #374), and we have done some internal review and revision, and our plan is to now do a cycle of dev-lite tests and fixes of issues that arise from these tests.  Once that cycle is complete we will have something that is usable for these interviews.

**Comment by arouinfar** [comment]
Thanks @jbphet. I did some sanity testing and didn't find any issues. We'll use `screens=2,3` during the interviews, so QA can focus their testing on those screens using our supported screen readers/platforms.

**Comment by jbphet** [comment]
A dev-lite test has been created for QA, see https://github.com/phetsims/qa/issues/1033.  Depending on the results of this testing, the version being tested may or may not be adequate for interviews.

**Comment by jbphet** [comment]
A 2nd round of dev testing has been done after addressing the issues that came from the first round.  The QA issue was https://github.com/phetsims/qa/issues/1043.

**Comment by jbphet** [comment]
A few issues came out of the last dev test, and as of this moment I've addressed two of them.  Over Slack, @arouinfar just said that she would be okay using dev version with these updates for interviews and leaving https://github.com/phetsims/greenhouse-effect/issues/390 and https://github.com/phetsims/greenhouse-effect/issues/385 unaddressed for now since they aren't likely to cause much trouble.  She also said that she'd be good with doing a spot check of a dev version so that we don't need to run it through QA.  With this in mind, I'll go ahead and build a dev version and hand it over to her for review.

**Comment by jbphet** [comment]
The dev version has been built and can be found at https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.0-dev.5/phet/greenhouse-effect_en_phet.html.  Turning over to @arouinfar for review.

**Comment by jbphet** [comment]
Wait, stop the presses (does that phrase date me?)!!! @arouinfar messaged me moments ago and said that a workaround was just committed for https://github.com/phetsims/greenhouse-effect/issues/385, and we should roll that into the dev version.  I just pulled the latest code from all common code repos and rebuilt.  The new dev version can be found at  https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.0-dev.6/phet/greenhouse-effect_all_phet.html.

**Comment by arouinfar** [comment]
Thanks @jbphet! I spot-checked dev.6 and everything looks good. I've shared the link with our partners who are scheduling the testing.

**Comment by arouinfar** [comment]
Now that #394 has wrapped up, we're ready for a new dev version for interviews. Over to you, @jbphet.

**Comment by jbphet** [comment]
I've built a dev version with the latest changes: https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.0-dev.8/phet/greenhouse-effect_all_phet.html.

**Comment by arouinfar** [comment]
Thanks @jbphet. I tested dev.8 with Safari/VoiceOver and everything looks good. I'll proceed with scheduling interviews using this dev link.

**Comment by arouinfar** [comment]
Interviews have wrapped up, so we can close this issue. Thanks @jbphet!
