### ISSUE TITLE
Issues with PDOM-related code comments

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#39]
- [x] I see `// pdom` in some places, `// PDOM` in other places.  My understanding is that the former is the convention.  And I missed some important examples until I turned off case-sensitive search.

- [x] This example in WaveScreenView doesn't use either convention:

```js
    // tab order (a11y)
    this.pdomControlAreaNode.pdomOrder = [
```

- [x] This comment is MicroScreenView.js is incorrect. This code is setting accessible order for play area AND control area.

```js
    // PDOM - the accessible order for the control area contents
    this.pdomPlayAreaNode.pdomOrder = [ this.observationWindow, clipRectangle, windowFrameNode, photonEmissionControlPanel, moleculeControlPanel ];
    this.pdomControlAreaNode.pdomOrder = [ timeControlNode, showLightSpectrumButton, resetAllButton ];
```

Assigning to responsible developer.

**Comment by pixelzoom** [comment]
> I see // pdom in some places, // PDOM in other places. 

This is apparently a wide-spread issue.  I see `// PDOM` GFL, GFL:B, and many common code repos. @jessegreenberg @zepumph FYI.

**Comment by jessegreenberg** [comment]
These were mostly mine (came from molecules-and-light). I also made https://github.com/phetsims/tasks/issues/1087 for common code.

**Comment by jessegreenberg** [comment]
These three checkboxes and https://github.com/phetsims/tasks/issues/1087 are done, closing.
