### ISSUE TITLE
Update Energy Flux Range Zoom button responsive descriptions

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#393]
Discussed with JB, JG, and MM at 3/11/24 design meeting.

During compatibility testing, a screenreader user made this observation about the zoom buttons on the Flux Meter:
> The Adjust visual range controls when zooming in and out provides the same feedback no matter whether it's zoomed in or out. If this is a visual adjustment for the simulation rather than for changing effects, the feedback should provide a more detailed spacial visual description of what is visible on screen.

Currently, the help text of the zoom buttons states, "Adjust visual range." When pressing the button, the responsive description states, "Visual scale zoomed {{in/out}}. {{Current value of energy flux.}}" For example:

> Visual scale zoomed out. At very low altitude, somewhat high incoming sunlight and low outgoing sunlight. exceptionally high outgoing infrared and exceptionally high incoming infrared.

We include the energy flux value in the context response because we thought users who interact with the zoom buttons might be trying to collect data. However, based on this feedback, we would like to instead let users know that changing the zoom level does not change the data itself.

@jbphet please change the responsive description for Energy Flux Range Zoom buttons to:
Visual Scale zoomed {{in/out}}. No change in energy flux.

**Comment by jbphet** [comment]
I've modified the description as described above.  @arouinfar - please try it out and let me know if this is what we're after.

**Comment by arouinfar** [comment]
Looks good, thanks @jbphet! Closing.
