### ISSUE TITLE
Create "Temperature Units" heading on Waves and Photons screens

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#394]
Discussed with JB, JG, MM in 3/11/24 design meeting.

Based on feedback from user testing, we would like to add an H4 header for the Temperature Units ComboBox on the Waves and Photons screens. This will make it easier for users to find/navigate to the temperature units control and will be more consistent with the Layer Model screen, which uses a header for the control name.

Waves & Photons Screens:
![image](https://github.com/phetsims/greenhouse-effect/assets/8419308/ece2a764-75e2-4e31-98f3-51bcb1bc573b)

Layer Model Screen:
![image](https://github.com/phetsims/greenhouse-effect/assets/8419308/f41869fb-e1d2-4588-9025-561bd6c31120)

@jbphet please create an H4 called "Temperature Units" for the temperature units ComboBox on the Waves and Photons Screens.

**Comment by jbphet** [comment]
I've added the h4.  Note that it ends up under the Play Area H2 in the first two screens but under the Control Area H2 in the Layer Model screen.  This is consistent with the layout, since the control is inside the observation window on the first two screens but under it in the 3rd, but I'd like @arouinfar to confirm that this is reasonable.

@arouinfar - please take this for a test drive and let me know if it is what we're after.

**Comment by arouinfar** [comment]
Thanks @jbphet, the overall heading structure looks good, but I see that "Temperature Units" is now repeated.
![image](https://github.com/phetsims/greenhouse-effect/assets/8419308/d2efbf33-140e-489b-b683-6ed3fd09112b)

On the Layer Model Screen, the accessible name of the RadioButtonGroup is the heading itself. Can we do the same thing here too?

**Comment by jbphet** [comment]
Sure.  I've taken the accessible name off of the combo box, and that seems to have done the trick.  It looks like this:

![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/b654499a-8e90-40bc-923c-e16a4b9f0e7f)

Back to you @arouinfar for review.

**Comment by jbphet** [comment]
Okay, I removed the `H4` and `div` for `TemperatureAndReadout` as a whole, added back the `accessibleName` to the `ComboBox` inside `TemperatureAndReadout`, and then set the `tagName` on that `ComboBox` to be an `H4`.  This prevents the duplication of the "Temperature Units" string and makes the screen reader produce a string similar to what was described as desirable in the previous comment, but in the a11y view it makes the "Select temperature units" bold.  I'm not sure whether this matters.  It looks like this:

![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/73314b4d-d32d-4cb9-a9ec-ad2d8e1ac5f3)

It feels a little odd to me to make something that it a subcomponent of a larger component into an H4, but if it gives us the behavior we need, I guess that's what we need to do.

@arouinfar - please check this behavior out and let me know if it's what we're after.  I'm a bit out of my element here, so if this doesn't do the trick I'll need to bring in someone with more PDOM expertise.

**Comment by jbphet** [comment]
@arouinfar and I discussed this in standup, and the behavior is still not quite what we're after, so I will assign back to me and contact @jessegreenberg to see if he can help.  @arouinfar said she would add some additional information as well.

**Comment by arouinfar** [comment]
Here's what the approach in https://github.com/phetsims/greenhouse-effect/issues/394#issuecomment-2013713293 looks like in VoiceOver when navigating by heading. I find this output to be really confusing.
![Screenshot 2024-03-26 at 9 56 37 AM](https://github.com/phetsims/greenhouse-effect/assets/8419308/d11c8747-dd98-4336-b973-5b7be6bdb420)

Compare to the heading readout on the Layer Model Screen:
![Screenshot 2024-03-26 at 10 00 04 AM](https://github.com/phetsims/greenhouse-effect/assets/8419308/ea7bb901-1ec1-4882-89de-84dce4222c7d)

The behavior in https://github.com/phetsims/greenhouse-effect/issues/394#issuecomment-1994562971 was reasonable, even with the repeated "Temperature Units". If it's not possible to make the Photons Screen behavior mirror the Layer Model screen, my preference would be to revert back to https://github.com/phetsims/greenhouse-effect/commit/8158aa17b6cafe9a2f9e93ec71bec68cdaeaf1d2.

**Comment by jessegreenberg** [comment]
Here is a potential patch. ComboBox makes this difficult because it uses a pattern we tried out called "AccessibleNameBehavior".  It hides some implementation details but it is more complicated to customize. @jbphet and I will meet soon to make sure this is OK.

<details>

```patch
Subject: [PATCH] Indicate that items have been sorted, see https://github.com/phetsims/scenery-phet/issues/815
---
Index: sun/js/ComboBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/sun/js/ComboBox.ts b/sun/js/ComboBox.ts
--- a/sun/js/ComboBox.ts	(revision 15ab334602a4c59be58d30ef434a2e7287fea20e)
+++ b/sun/js/ComboBox.ts	(date 1711494369933)
@@ -294,6 +294,7 @@
       comboBoxVoicingNameResponsePattern: options.comboBoxVoicingNameResponsePattern,
 
       // pdom - accessibleName and helpText are set via behavior functions on the ComboBox
+      labelTagName: options.buttonLabelTagName,
 
       // phet-io
       tandem: options.tandem.createTandem( 'button' )
Index: greenhouse-effect/js/common/view/ThermometerAndReadout.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/greenhouse-effect/js/common/view/ThermometerAndReadout.ts b/greenhouse-effect/js/common/view/ThermometerAndReadout.ts
--- a/greenhouse-effect/js/common/view/ThermometerAndReadout.ts	(revision 0f48717e8dd1679385a7c52b28ac077f6eb49d94)
+++ b/greenhouse-effect/js/common/view/ThermometerAndReadout.ts	(date 1711493761075)
@@ -151,8 +151,10 @@
 
         // pdom
         helpText: GreenhouseEffectStrings.a11y.temperatureUnitsHelpTextStringProperty,
+
         accessibleName: GreenhouseEffectStrings.a11y.temperatureUnitsLabelStringProperty,
-        tagName: 'h4',
+        buttonLabelTagName: 'h4',
 
         // phet-io
         tandem: options.tandem.createTandem( 'comboBox' )
Index: sun/js/ComboBoxButton.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/sun/js/ComboBoxButton.ts b/sun/js/ComboBoxButton.ts
--- a/sun/js/ComboBoxButton.ts	(revision 15ab334602a4c59be58d30ef434a2e7287fea20e)
+++ b/sun/js/ComboBoxButton.ts	(date 1711494063492)
@@ -37,7 +37,6 @@
 // The definition for how ComboBoxButton sets its accessibleName in the PDOM. See ComboBox.md for further style guide
 // and documentation on the pattern.
 const ACCESSIBLE_NAME_BEHAVIOR: PDOMBehaviorFunction = ( node, options, accessibleName ) => {
-  options.labelTagName = 'p'; // NOTE: A `span` causes duplicate name-speaking with VO+safari in https://github.com/phetsims/ratio-and-proportion/issues/532
   options.labelContent = accessibleName;
   return options;
 };
@@ -105,6 +104,7 @@
 
       // pdom
       containerTagName: 'div',
+      labelTagName: 'p', // NOTE: A `span` causes duplicate name-speaking with VO+safari in https://github.com/phetsims/ratio-and-proportion/issues/532
       accessibleNameBehavior: ACCESSIBLE_NAME_BEHAVIOR
     }, providedOptions );
 
```
</details>

**Comment by jessegreenberg** [comment]
@jbphet and I met to discuss and review the changes to ComboBox. We tested it with NVDA and it sounded OK to us and the markup looked corrrect. Back to @jbphet to verify or reassign for review.

**Comment by jbphet** [comment]
The behavior seems reasonable to me, as do the code changes.  Over to @arouinfar to see if this is now what we're after.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg @jbphet! I tested in Safari/VoiceOver and the updated behavior is perfect.

**Comment by arouinfar** [comment]
We're ready to proceed with a new dev version for #384, so I'll go ahead and close this issue.
