### ISSUE TITLE
Add context response to Infrared Absorbance slider when there are no layers in the atmosphere

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#396]
The Infrared Absorbance of the layers can be adjusted even when no layers are in the atmosphere. This supports prediction-making and generally makes it easier to set up experiments. However, it can be a bit confusing to screen reader users.

![image](https://github.com/phetsims/greenhouse-effect/assets/8419308/6b0247e3-5712-4db1-a9eb-155ffae5d998)

When there are layers in the atmosphere, there is a context response that states:
All layers now absorbing {{70%}} of infrared photons{{, {{30%}} passing through layers}}.

However, nothing is stated if there are no layers currently in the atmosphere. Based on interview feedback, we would like to add this context response:

No absorbing layers. Added layers will absorb {{80%}} of infrared photons.

**Comment by jbphet** [comment]
This has been added.  Below is a screenshot from the a11y view when playing with it.  Keep in mind that this, like the other IR absorbance alerts, requires the sun to be shining.

![image](https://github.com/phetsims/greenhouse-effect/assets/3082831/c3e69243-7ed6-4aaf-b6ad-b8a8fc5aeb15)

Assigning to @arouinfar for review.

**Comment by arouinfar** [comment]
Looks good on main, thanks @jbphet. Closing.
