### ISSUE TITLE
Updates to focus order and heading structure for temperature-related controls

### ISSUE THREAD

**Issue by arouinfar** [phetsims/greenhouse-effect#398]
In #394 we added a "Temperature Units" heading to the first two screens to make it more consistent with the Layer Model Screen. However, while discussing the changes for #397 the design team realized that there was still some work to be done. 

On the Layer Model Screen, the Temperature Units is housed under the Control Area, but for the Waves and Photons Screens, it's under the Play Area. 

- [x] Change focus order of Temperature Units ComboBox so that it is the first item under the Control Area, between the Cloud checkbox (last item in Play Area) and the Surface Thermometer checkbox.
- [x] For the Waves and Photons Screens, create a new heading "Temperature Options", level H3 under the Control Area to collect all temperature-related controls:
* H2: Control Area
  * H3: Temperature Options
    *   H4: Temperature Units (ComboBox)
    * Surface Thermometer Checkbox (not under Temperature Units!)
    * Show Surace Temperature (Waves Screen only)
 - [x] On the Layer Model Screen, group the thermometers under new heading "Thermometers", level H3 under the Play Area.
 * H2: Play Area
   * H3: Thermometers
      * Surface Thermometer Checkbox
      * Layer 1 Thermometer Checkbox (when visible)  
      * Layer 2 Thermometer Checkbox (when visible)  
      * Layer 3Thermometer Checkbox (when visible)

**Comment by jbphet** [comment]
@arouinfar and I just reviewed my attempts to implement the requests above, and the behavior is looking good.  I'm not sure that my implementation was the way it should be, so I'll review with @jessegreenberg before finalizing.

For the record, @arouinfar said that if it's hard to do the "Thermometers" section in a reasonable way, she'd be okay to drop it.

**Comment by jbphet** [comment]
@jessegreenberg just reviewed this with me over Zoom and we decided to group the thermometer controls together into a `div` for improved maintainability.  The overall behavior and appearance should be unchanged, but I'd like @arouinfar to take one last look at it and make sure it looks good before closing.

**Comment by arouinfar** [comment]
>  Change focus order of Temperature Units ComboBox so that it is the first item under the Control Area, between the Cloud checkbox (last item in Play Area) and the Surface Thermometer checkbox.

@jbphet looks like you did this for the Waves Screen, but not the Photons screen. Can you please apply these changes to the Photons screen as well?

The structure on the Waves Screen looks perfect
![image](https://github.com/phetsims/greenhouse-effect/assets/8419308/f7eafdad-48c7-4d17-8a7a-4f6da6a091ec)

**Comment by jbphet** [comment]
Oops, my bad.  Glad you caught that @arouinfar.  Please have a look now.

**Comment by arouinfar** [comment]
Looks good, closing!
