### ISSUE TITLE
Reduce height of slider thumbs

### ISSUE THREAD

**Issue by samreid** [phetsims/greenhouse-effect#4]
From https://github.com/phetsims/greenhouse-effect/issues/3#issuecomment-600985079.  @arouinfar said:

> ComboBoxes are too tall and get hidden by the navbar unless the window aspect ratio is made narrower. Could probably prevent this if slider thumbs are all made ~50% smaller.

**Comment by samreid** [comment]
Fixed and ready for review.

**Comment by arouinfar** [comment]
Looks great, thanks!
