### ISSUE TITLE
Going to screen for the first time, NVDA may briefly start in middle of page

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#403]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox + NVDA
**Problem description**
For https://github.com/phetsims/qa/issues/1080, seen with NVDA + Firefox.
On NVDA, when you first select a screen from the main menu NVDA starts reading from the middle of the screen rather than the start. After a second it corrects itself and starts from the beginning and this doesn't seem to happen when you switch screens after that.

**Visuals**

https://github.com/phetsims/greenhouse-effect/assets/41024075/a4c336d8-a0f6-4fed-a0a3-f27a4504c373

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.0-dev.11/phet/greenhouse-effect_all_phet.html
Version: 1.3.0-dev.11 2024-04-26 19:11:48 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0), or similar)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
This seems to be if you read through to get the options, rather than use tab to get to them.

**Comment by jessegreenberg** [comment]
I wasn not able to get this to happen with NVDA 2024.1 with FireFox 125.0.3 (64-bit). It is possible that NVDA struggles to catch up on slower laptops. Otherwise, where the virtual cursor reads is largely out of our control. 

For this one, I would recommend closing as wontfix.

**Comment by jbphet** [comment]
I'm not able to duplicate this either on my Win 11 machine with Firefox 125.0.2 (64-bit) - it works just fine for me.  @jessegreenberg's theory that NVDA is just getting a bit behind seems reasonable, and I second his suggestion of closing as `wontfix`.
