### ISSUE TITLE
Should the "more photons" checkbox correspond to a faster paced sound?

### ISSUE THREAD

**Issue by Luisav1** [phetsims/greenhouse-effect#406]
For https://github.com/phetsims/qa/issues/1080.
When I clicked the "more photons" checkbox on the Photons screen, the photons sound remains the same. I'm not sure if this was an intentional sound design choice. Although, I expected the photons sound to be either faster paced or another change in sound to signify that there are more visible photons on the screen.

**Comment by jbphet** [comment]
Assigning to @arouinfar, since this is more of a design question.
