### ISSUE TITLE
The concentration slider and concentration graphic in the concentration control panel should match

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#41]
Slider is currently a different size from the graphic. They should be the same so that the displayed concentration on the graphic matches where the thumb would be on the slider while they are the same height. @jbphet already changed it so that the box and line on the concentration graphic is placed by the model.

**Comment by jessegreenberg** [comment]
Also, remove the tick marks in the slider and remove the tick mark in the middle of the box on the graphic.

**Comment by jessegreenberg** [comment]
Done in the above commits. In addition, the track and line width for the meter lines are also the same so that the graphic and slider look like nearly the same component.

@arouinfar can you please review, any other changes to the look of these components?

**Comment by arouinfar** [comment]
We reviewed this in the 6/9/21 design meeting, and it looks good. Thanks @jessegreenberg!
