### ISSUE TITLE
Focus order of Zoom Buttons has changed

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#410]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1086, on the Layer Model screen, the focus order for the zoom buttons now goes right (zoom in) to left (zoom out) instead of left to right as seen in published. Looking at issues this doesn't seem like an intentional change and it feels backwards to me. 

**Steps to reproduce**
1. On the Layer Model screen, tab to and check the flux meter 
2. Continue to tab through the zoom buttons

**Visuals**

The first part of the video shows the tab order in 1.3.0-rc.1 and the second part shows the tab order in published:

https://github.com/phetsims/greenhouse-effect/assets/87318828/67a5fb69-888e-41ff-96ca-e07b6027c673

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.3.0-rc.1 2024-05-13 19:29:11 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language: en-US
Window: 1415x700
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment]
Good catch @Nancy-Salpepi, it feels backwards to me too. I didn't ask for this change, but I wonder if there was recent work done to ZoomButtonGroup that could have affected things. @jbphet preferably, the focus should first go to the zoom out button.

**Comment by jbphet** [comment]
Adjusted.  I'll have this verified in the next round of QA testing.

**Comment by jbphet** [comment]
@arouinfar - Can you test this out and make sure we're good, then (assuming we are) leave it open and unassigned so we can have it double checked in the next QA cycle?

**Comment by jbphet** [comment]
QA - feel free to close this after verifying.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2. Closing
