### ISSUE TITLE
On Layer Model screen, Temperature display and font sizes are inconsistent 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#411]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
all

**Problem description**

For https://github.com/phetsims/qa/issues/1086, I noticed some minor inconsistencies with the temperature displays on the Layer Model screen:

-  the font size is smaller for the surface temperature than the layer temperatures. 
<img width="189" alt="Screenshot 2024-05-21 at 1 15 13 PM" src="https://github.com/phetsims/greenhouse-effect/assets/87318828/124b8ce1-1fce-42c6-8c45-fd2b421460aa">

--

- when changing between temperature units, the display window changes size for the surface temperature, while the layer displays remain the same. Can we prevent the window size from changing?
<img width="112" alt="Screenshot 2024-05-21 at 1 21 41 PM" src="https://github.com/phetsims/greenhouse-effect/assets/87318828/2f031ee1-5fd5-4319-84b2-34e7faaa3d04">

**Steps to reproduce**
1. On the Layer Model Screen, start sunlight
2.  Increase the Layers to 3
3. Switch between temperature units

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.3.0-rc.1 2024-05-13 19:29:11 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language: en-US
Window: 1415x687
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment]
Good observation @Nancy-Salpepi. 

Ideally, the font size and NumberDisplay size should be the same for all layers and units. @jbphet can you look into it?

**Comment by jbphet** [comment]
This should now be fixed on main and on the 1.3 branch.  @arouinfar - please review the behavior and make sure you're good with it.  Please leave it open so that I can have QA double check it in the next round of testing.

**Comment by arouinfar** [comment]
Looks great, thanks @jbphet!

**Comment by jbphet** [comment]
QA - feel free to close this after verifying.

**Comment by Nancy-Salpepi** [comment]
With some locales (e.g. Hebrew, Hausa) the display size changes when switching between temperature units. Is this OK?

https://github.com/phetsims/greenhouse-effect/assets/87318828/c3d048bd-1ea6-4f94-ab8e-0b25d29623db

**Comment by arouinfar** [comment]
> With some locales (e.g. Hebrew, Hausa) the display size changes when switching between temperature units. Is this OK?

This seems like a normal consequence of dynamic locale. I verified that the NumberDisplays all have an appropriate `maxWidth`, so this issue is probably fine to close, but I'll leave it up to @jbphet.
<img width="283" alt="image" src="https://github.com/phetsims/greenhouse-effect/assets/8419308/b543ddcf-735b-4186-a1b4-2666b46e8ff8">

**Comment by jbphet** [comment]
Yes, I think this is reasonable behavior.  There is a minimum width that is set based on English and other languages, but it wouldn't look good to make the readout wide enough to handle every possible language, so having it change size to accommodate cases where the strings are particularly long seem like the right thing to do.  Closing.
