### ISSUE TITLE
Possible to still move slider after switching to Date Mode

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#412]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 17.4.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1086, on the Waves Screen if I am moving the slider with one finger and switch to date mode with another, I can still hear the slider sounds as I move my finger up and down. The drag listener needs to be interrupted when switching between modes (I think that is the correct lingo). 

**Steps to reproduce**
1. On the Waves Screen, with one finger continually move the thumb node on the Concentration Slider up and down.
2. With another finger, switch to Date Mode

**Visuals**

https://github.com/phetsims/greenhouse-effect/assets/87318828/78bd5007-8c78-4916-b353-34cf867b72c3

**Comment by jbphet** [comment]
QA - feel free to close this after verifying.
