### ISSUE TITLE
Why are Intensity and Absorbance slider volumes inverse of one another?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#413]
**Test device**
MacBook Air M1 chip and iPad

**Operating System**
14.5

**Browser**
all

**Problem description**

For https://github.com/phetsims/qa/issues/1086 On the Layer Model screen:
I have been trying to figure out why the volume changes are opposite for the Solar Intensity and IR Absorbance sliders. @arouinfar didn't know the reason and I see that @terracoda also mentioned it [here](https://github.com/phetsims/greenhouse-effect/issues/222#issuecomment-1322368743).

Was it intentional for the volume changes to be opposite one another? 

https://github.com/phetsims/greenhouse-effect/assets/87318828/2c3766cc-ffad-4a2a-8213-75b53509c127

**Comment by jbphet** [comment]
Adding @arouinfar as an assignee in case she wants to take a crack at answering this before I get to it.

**Comment by arouinfar** [comment]
@jbphet looks like the relevant notes are all in #131. I didn't find any contemporaneous documentation in the sound design doc.

I'll take a look through the issue to see if I can find a reason for the current mapping.

**Comment by arouinfar** [comment]
In https://github.com/phetsims/greenhouse-effect/issues/131#issuecomment-1129323250 @jbphet said: 

> I made the sound generator for IR absorbance act basically like the inverse of the solar intensity generator, but it felt a little off to me since one has to to with the visible light and the other IR light. I tried lowering the base sound by one musical step, and thought it sounded better. We should review this in our next sound design meeting.

This change came in after design review and later comments in the issue do not refer to the inverse behavior. I think this is something we could change, if @jbphet agrees.

It seems strange that the solar intensity and IR absorbance sliders have inverse mappings. I recommend we reverse the IR absorbance behavior to match the solar intensity slider.

**Comment by jbphet** [comment]
Sorry I wasn't able to look at this sooner, but now that I have, I remember what the intent was.  In a nutshell, it's that actions that lead to fewer photons being visible in the sim cause more muted sounds, and actions that lead to more photons cause brighter, less muted sounds.

To some degree, this makes sense, but since the behavior seemed odd to @Nancy-Salpepi, and @arouinfar wasn't too keen on it once it was pointed out, let's reverse the IR slider.  We can now think of it like this: Actions that lead to more energy being present *in the layers* lead to brighter, more energetic sounds.

**Comment by jbphet** [comment]
This is done on the main and 1.3 branches.  @arouinfar - please check it out, but I'm going to move ahead with the RC in the meantime because I think this is a pretty safe change.

**Comment by arouinfar** [comment]
> We can now think of it like this: Actions that lead to more energy being present in the layers lead to brighter, more energetic sounds.

This is a more intuitive pattern. Thanks for making this change @jbphet. Looks good in main and in the new RC.
