### ISSUE TITLE
Update Credits for GHE

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/greenhouse-effect#414]
I was reviewing the credits for GHE, and have some suggested additions. I'm checking with our Mark for input though. Current from phettest: 
![image](https://github.com/phetsims/greenhouse-effect/assets/5096804/f38bd22e-65bb-4d65-a6b6-32e2ca9acc22)

**Within Sim Credits:** 

Additions to "Team": Mark Nielsen (all a11y aspects)

Addition to "Thanks":
HHMI BioInteractive Team for their partnership on the inclusive design and accessibility of this simulation. 
This simulation is dedicated to the memory of Ron LeMaster.

On the website: 
Add Mark Nielsen to team 
Add Thanks To section with above.

**Comment by arouinfar** [comment]
Good catch @kathy-phet! These changes all look good to me. Would you like to confirm the "Thanks" language with HHMI before we make the commits?

**Comment by jbphet** [comment]
In an email response to @kathy-phet's questions, Mark said:

> Thanks for the heads up. Feel free to add me to the credits (I didn’t get a screenshot). 
> 
> I think you could just strike the word “team” from the Thanks section:
> 
> Thanks:
> HHMI BioInteractive for their partnership on the inclusive design and accessibility of this simulation.
> 
> Best,
> 
> Mark

**Comment by jbphet** [comment]
Update complete.  @kathy-phet and @arouinfar - please review and close if you're good with the credits or let me know what further changes you'd like.

**Comment by arouinfar** [comment]
Thanks @jbphet looks good on main & 1.3, closing.

**Comment by kathy-phet** [comment]
Let's keep this open until the website is also updated with Mark and HHMI. Thanks!

**Comment by KatieWoe** [comment]
No new QA credits

**Comment by arouinfar** [comment]
Sim page credits have been updated, closing.
