### ISSUE TITLE
Description inconsistency

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#415]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox + NVDA and Others
**Problem description**
For https://github.com/phetsims/qa/issues/1092. Rather minor nitpick. The scene description for the first and second screens changes slightly depending on if you are on the concentration or year scene. However, one thing that does not change is saying you can add or take away a cloud. This option is removed in the year scene.

**Visuals**
![addcloud](https://github.com/phetsims/greenhouse-effect/assets/41024075/db858fc2-33c7-4fc5-b3e0-7b6e2ffa5532)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.0-rc.2/phet/greenhouse-effect_all_phet.html
Version: 1.3.0-rc.2 2024-05-30 20:43:16 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0), or similar)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks for the suggestion @KatieWoe, but I'm inclined to leave it as-is.

In general, there is only one block of dynamic content in the Scene Summary (paragraph starting with "Currently") and the rest is meant to be general. I hesitate to introduce more complexity and alter the general formula for Scene Summaries. IIn this case I think the cost outweighs the benefit, so I'm going to close as wont-fix.
