### ISSUE TITLE
Energy in/out bars in Energy Balance plot should match Energy Flux graphic

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#44]
During 6/9/21 design meeting @arouinfar mentioned it was strange that the "In" bar grew upwards while the energy "in" grows downwards. We should switch it so that the "In" grows down like the flux meter. We would also like to add arrow heads to the bars in the "Energy Balance" plot.

Bamboo's BarPlot doesn't  support arrow heads so we will need to decide whether to add it to Bamboo, decorate the BarPlot with arrow heads (unlikely to be easy since bars are internal), or redraw this graphic with our own type.

**Comment by jessegreenberg** [comment]
I asked slack for some advice and there was a recommendation to create a new plot in bamboo for this to support arrow heads. Excel has a thing called "up down arrow" charts so the recommendation was to call it "UpDownArrowPlot" to match bamboo plots.

The new plot should have the same API as other plots in bamboo.

**Comment by jessegreenberg** [comment]
It wasn't documented here, but over slack @arouinfar sumarized the moviviation for this change with:
> ...the arrows would help emphasize the inflow/outflow of energy. The Energy Balance and Energy Flux are related. The “In” bar/arrow would be the sum of the two down arrows in the Energy Flux. Similarly, the “Out” bar corresponds to the two up arrows in the flux.

**Comment by jessegreenberg** [comment]
I made the new UpDownArrowPlot and flipped the direction of the arrows. @arouinfar can you please review, is there anything else to change?

**Comment by arouinfar** [comment]
Looks good, thanks @jessegreenberg!
