### ISSUE TITLE
Need artwork for observation window and icons

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#49]
We're getting to the point where it would be good to start integrating the artwork that will be used on the first screen.  We'll need backgrounds for the ice age, 1750, 1950, and 2019 selections as well as for the generic view (where the gas concentration is controlled by a slider).  We should also have icons for the cloud and the surface temperature checkboxes.

We haven't yet decided whether to use artwork for clouds or go with the code-generated version that is currently in place, so I'll leave it up to @arouinfar to decide whether to procure anything for the clouds that appear in the observation window.

**Comment by jbphet** [comment]
This was discussed in today's weekly design meeting, and @arouinfar is going to contact Cheryl (sp?) and find out if she has the bandwidth to work on this.

**Comment by arouinfar** [comment]
I emailed Cheryl to ask about her upcoming availability. I'll report back when I have more info.

**Comment by jbphet** [comment]
In today's design meeting @arouinfar reported that Cheryl has taken a full time position elsewhere and can't do the artwork for this sim.  Bummer.

**Comment by jbphet** [comment]
In today's design meeting it was decided that @arouinfar will get @jbphet something to integrate by 9/12/2021 so that we can get an early RC out.  This will be something that improves the situation, but will almost certainly not be the final artwork.

**Comment by arouinfar** [comment]
@jbphet I created a glacier for the ice age and a small scene for 1750. For the ice age, we should fill the ground with gray/brown `#9b9185`.

The assets were exported at twice the resolution used in the mockups below.
[1750.png](https://user-images.githubusercontent.com/8419308/133009171-884cee0a-6cf1-4078-ac57-6464bae1bc80.png)
[ice-age.png](https://user-images.githubusercontent.com/8419308/133009172-7554bc4f-a22f-4919-8277-0bd10ad04173.png)


Here's the artwork in context:
<img width="607" alt="Screen Shot 2021-09-12 at 6 43 08 PM" src="https://user-images.githubusercontent.com/8419308/133008739-a6519cc9-a61c-4827-b65e-42cb17c27f4c.png">
<img width="608" alt="Screen Shot 2021-09-12 at 6 43 32 PM" src="https://user-images.githubusercontent.com/8419308/133008779-80e710b5-5fe4-4806-af3f-e32961773105.png">

I'm still working on 1950 and 2020. The wave representation itself is very busy, so a very developed landscape will be overwhelming. It is hard to illustrate something minimal that makes the two years distinguishable, but it's my top priority to wrap up on Monday.

**Comment by arouinfar** [comment]
Here are the mockups for 1950 and 2020, respectively. The artwork is essentially the same, but the number of buildings is used to indicate the increase in population and industrial development. I played with added cars on the roads, but it ends up looking really busy so I got rid of them.

@jbphet here's the full set of assets:  [greenhouse-effect-scenes.zip](https://github.com/phetsims/greenhouse-effect/files/7156952/greenhouse-effect-scenes.zip)

<img width="607" alt="Screen Shot 2021-09-13 at 1 29 31 PM" src="https://user-images.githubusercontent.com/8419308/133145465-2d6ba488-1d7d-426d-8dd7-48fac1b0ee71.png">
<img width="605" alt="Screen Shot 2021-09-13 at 1 29 17 PM" src="https://user-images.githubusercontent.com/8419308/133145455-f9c74c30-96fe-418c-a32f-5c6c8be50bdc.png">

**Comment by jbphet** [comment]
I asked @arouinfar about artwork for the icons over Slack, and she said:

> Can you draw the cloud in code like you do in the observation window?
>
> Show surface temp would likely be similar to what you have now, but the glow on the top edge only

Based on this, I'll attempt to render them in code.

**Comment by arouinfar** [comment]
@jbphet I think the rolling hills look great! The icons and integrated artwork also look good to me. Since the artwork was more of a stop-gap, I'll leave this open until we figure out the next steps.

**Comment by mariahmaephet** [comment]
![1750  Recovered](https://user-images.githubusercontent.com/11527557/189734654-d6ff7b85-0f34-4fcf-a54f-5c3571fab5da.png)

**Comment by mariahmaephet** [comment]
![1750](https://user-images.githubusercontent.com/11527557/189735258-f5aff549-f6a2-4583-b2e9-c97c013da673.png)

**Comment by mariahmaephet** [comment]
![1950](https://user-images.githubusercontent.com/11527557/189740200-04f65ec2-16a6-437f-a173-9abaafbc8692.png)

**Comment by mariahmaephet** [comment]
![1750  Recovered](https://user-images.githubusercontent.com/11527557/193684681-04a3dd6b-978d-4e46-b92f-16440a8164b0.png)

**Comment by mariahmaephet** [comment]
![1950b](https://user-images.githubusercontent.com/11527557/193692747-bf695f32-abbe-42a2-b5fa-56da50f1de8b.png)

**Comment by mariahmaephet** [comment]
![noroad](https://user-images.githubusercontent.com/11527557/194129961-48444f89-148d-4bc5-b38f-1cdca671649a.png)

**Comment by jbphet** [comment]
I've integrated the artwork above and shared some of it with the design team.  For the most part, it's starting to look really good.  Here are a few requests that came out of the integration and review:

1. The background landscape (the shape of the foreground hills and the background mountains) changes between the agricultural and early industrial images.  We'd like this to remain the same.  In fact, the best thing may be to provide a background of just the hill and the mountains, and then layer the other imagery in with overlay images.  Can we get artwork like this?
2. Can we get sketches for 2020 and Ice Age too?  It would be nice to put together the complete set and go from there.
3. We need icons for the three screens.  I'll set up a meeting with @mariahmaephet to start on these.

Assigning to @mariahmaephet for the next steps.

**Comment by jbphet** [comment]
@RVieyra - The design team for this sim was looking over the preliminary artwork above, and @kathy-phet suggested that we run it by you to see if you think it may be in need of localization.  This is in the early stages, but we'd like your input: Do you think the artwork shown above, and any landscape artwork that is done for this sim, should be localized?

**Comment by RVieyra** [comment]
Let me take this back to the #Global team and see what they say. I think the answer would always be "yes," but let me identify some potential options for you.

**Comment by RVieyra** [comment]
This is not yet all-inclusive of potential options, but here are a few for your consideration:

**Africa**
Zach shares these possible landscapes:
<img width="581" alt="Screen Shot 2022-10-12 at 9 05 41 AM" src="https://user-images.githubusercontent.com/89751562/195350497-c7ea139a-5357-4d63-a799-57c95fd956d1.png">
<img width="352" alt="Screen Shot 2022-10-12 at 9 05 50 AM" src="https://user-images.githubusercontent.com/89751562/195350525-cf6889fa-4c4b-410a-896f-f5171dde9617.png">


**Europe**
Jacqui says: "From a European perspective, the landscape can be similar (rolling green hills and pine trees fits approximately to a landscape found in most countries in Europe) but **more than 50% of residents live in apartments or multigenerational houses**. It would be an exception for a student to live in an American-style, single-family home like those represented in this image (though they do exist)."

**Comment by mariahmaephet** [comment]
![iceage  Recovered](https://user-images.githubusercontent.com/11527557/195400737-e2906563-1b3e-4c54-a39c-7e8c0e4aaf59.png)

**Comment by RVieyra** [comment]
And an additional comment from Diana about Latin America:

- Houses in Latin America are very rarely A-style roof. Rather, most are flat (square/rectangle). 
- And farms are like this. no roofed barns, windmills, tall grain stores.
![image](https://user-images.githubusercontent.com/89751562/195403843-572884a3-4b22-436a-8ecf-3542ed8c9589.png)

**Comment by jbphet** [comment]
better contrast with waves and photons against the background colors
less cluttered 1950 and 2020
road path shifted so not so parallel with intersection point
keep intersection path relatively clear
lower corners where controls are (particularly the right side) less stuff
fairly flat colors and low detail are good

**Comment by mariahmaephet** [comment]
![2020back](https://user-images.githubusercontent.com/11527557/196772192-4d110445-5a49-4298-a51b-70f36bc902c1.png)
![2020objects](https://user-images.githubusercontent.com/11527557/196772196-592ea1d9-80a3-4a37-b5cb-5a3319e3a329.png)

**Comment by jbphet** [comment]
Thoughts from the design team on the icons:

- Waves screen: One sunlight wave, one radiated IR wave from ground and splitting in atmosphere, background of hill and sky
- Photons screen: Same background for sky and ground, a handful of photons, visible and IR, scattered about, more IR at the lower portion
- Layer screen: A single layer, sky gradient behind it, a couple IR photons below and fewer (maybe just one) above, and a couple of visible photons

**Comment by jbphet** [comment]
For the artwork, the design team feels like there are a few too many buildings, trees and such, and the complexity could be reduced.  There could probably be about 1/3 as many objects as there currently are (i.e. reduce it by about 2/3).  The city could look like how the city of Denver looks from Boulder, where it is a cluster in the distance and fairly faint.

**Comment by arouinfar** [comment]
Tagging for #220

**Comment by mariahmaephet** [comment]
![g17hill](https://user-images.githubusercontent.com/11527557/201742723-6b207c6f-1383-481a-a6ec-f0e27594c927.png)
![g17obj](https://user-images.githubusercontent.com/11527557/201742725-67bf3250-723c-4555-997b-a73e72ad4352.png)
![g19hilll](https://user-images.githubusercontent.com/11527557/201742728-e33ee973-b75e-4b86-835b-4740576bc76e.png)
![g19obj](https://user-images.githubusercontent.com/11527557/201742729-1d24adcb-6cd7-446d-a419-e89be7e2c205.png)
![g20hilll](https://user-images.githubusercontent.com/11527557/201742732-3d81214b-68bf-4e1e-a4da-58511f691e6d.png)
![g2020obj](https://user-images.githubusercontent.com/11527557/201742733-c632f991-8eb4-42fd-a34b-4e904501e2d5.png)
![a17hill](https://user-images.githubusercontent.com/11527557/201742753-834c47d2-a65f-41a2-a4b2-c707c87685c6.png)
![a17objects](https://user-images.githubusercontent.com/11527557/201742755-2c075ef5-1cdd-4c0b-8693-96aab804339f.png)
![a20hill](https://user-images.githubusercontent.com/11527557/201742756-25069579-e145-455c-85d9-7fc96f89cfe8.png)
![a20obj](https://user-images.githubusercontent.com/11527557/201742757-2a96ee3f-6e57-44fb-9f70-9695018c6cf4.png)

**Comment by jbphet** [comment]
Notes from review with the design team of the home screen and nav bar icons:
- Use regular red, and not color blind red, for the IR wave color
- Use bigger photons.  The size when the scale was set to 2 looked about right.  The number of photons should be reduced to look reasonable with ones that are this big.
- For the Layer Model icons, use just one bigger layer so that it is more visible in the nav bar.

**Comment by jbphet** [comment]
Notes from review of the landscape artwork with the design team:

- For the 2020 artwork, let's just have two windmills off to the left of the factory and a 2nd factory of some kind where the windmills are
- We'd like an indication of more traffic.  How about making the road a divided highway, which would help to imply more traffic.
- In general, we'd like more of a clear contrast from 1950 to 2020
- The 1750 windmill looks too modern
- Sheep!

**Comment by mariahmaephet** [comment]
Hey! So for the 2020 one, I think we decided not to put objects on the far left because of the graphics that go on top of it? So I just made that power plant larger and widened the road, but if you do want to switch to another separate plant I can do that too.

(1750 replacement, con ovejas, below)
![2020power](https://user-images.githubusercontent.com/11527557/204593102-5aaaf8c8-cee0-438f-b9f4-acaa9768fcb5.png)
![2020hill](https://user-images.githubusercontent.com/11527557/204593140-af2b5291-261d-4bfe-a48e-135081de8ad8.png)

![1750sheep](https://user-images.githubusercontent.com/11527557/204593167-19dfce65-2144-4b5c-9a76-bcf5fe226934.png)

**Comment by jbphet** [comment]
Thanks for the update @mariahmaephet.  The ovejas look awesome in context!  I think we need a few updates for the other elements.  Specifically:

- The road looks great in the 2020 background image, but the buildings disappeared, so we will need those added back.
- The idea of expanding the factory from the 50's to 2020 sounds great, but we'd still like to remove most of the windmills and put just two on the left side of the factory.  I pasted a screenshot below with the waves in place, and I think they would be fine there as long as they are not so low that they overlap with the origin of the red waves.  I'd suggest leaving the suburban homes from the 50's version in the 2020 version and either making them a little bigger or adding one or two more.
- We still need artwork for the "Ice Age" time period that aligns with the other time periods.

![image](https://user-images.githubusercontent.com/3082831/204659749-25e0d77b-e89a-4e81-851f-7a56f5576fb5.png)

**Comment by mariahmaephet** [comment]
Oh right, how do these look?


![2020city](https://user-images.githubusercontent.com/11527557/204670837-e2942059-2b02-4019-9b78-a223ab5348f4.png)
![2020edit](https://user-images.githubusercontent.com/11527557/204670839-f97105e6-5bb6-43e4-816c-5849f222352e.png)
![iceage](https://user-images.githubusercontent.com/11527557/204668640-b48efcbe-059b-4b94-b26f-cbb8d1605206.png)

**Comment by jbphet** [comment]
These look very good in context, and I think we're almost there.  Here are a few more tweaks that I think we need:

- When the background and foreground for the 2020 scene are put together, there is a lot of overlap between the apartment building in the foreground and the city buildings in the background.  The desired effect of the buildings is being a bit lost, and some of them almost look like chimneys on the apartment building.  Can the buildings be shifted left a bit to make the city more apparent?  Here is a screenshot of this portion:

![image](https://user-images.githubusercontent.com/3082831/204935866-0ecbf5ac-3396-4f31-92d0-30828747f9fb.png)

- The road perspective in the 2020 image isn't quite as good as in the others.  Can we make it narrow a bit more towards the horizon for slightly better perspective?
- The snow caps on the ice age mountains look great, but the mountains themselves are a bit too much higher than the ones in the other scenes.  It's a bit unrealistic that there would have been quite this much erosion.  Also, the tallest mountain gets a little too close to the cloud, almost making it look like a volcano.  Screenshot below.  Can we make the profile of the mountains a bit closer to those in the other landscapes?  Let's continue to have them be a bit taller, just not quite as much as they are now.

![image](https://user-images.githubusercontent.com/3082831/204936382-185d9ff0-c8c7-4195-902a-7d653e632842.png)

- The perspective on the glacier looks great.  Can we move the lower portion of the glacier edge just a teeny bit right so that it doesn't overlap with the returning IR wave?  Here is a screenshot of the overlap that I'd like to avoid.  If the visible light gets too close to the edge in the revised version, I will move it a little to the right.

![image](https://user-images.githubusercontent.com/3082831/204936874-b4d30286-00b2-4541-be21-d637dca01d8f.png)

That's it for now.  Thanks!

**Comment by mariahmaephet** [comment]
@jbphet 
2020 apartment change
![2020houseupdate](https://user-images.githubusercontent.com/11527557/205708189-5d28d541-cf81-456d-a2c6-bd6db1cd18b4.png)

2020 new road perspective--I think the dashed lines were warping the perspective
![2020roadfix](https://user-images.githubusercontent.com/11527557/205708391-5938d87e-81e6-46b9-ac81-051bdcd94929.png)

Ice age--is that far right enough? and I minimized the mountains
![iceageresize](https://user-images.githubusercontent.com/11527557/205708467-9f171009-fd3d-474a-b934-a1f09892115e.png)

**Comment by jbphet** [comment]
I've put in the latest revisions, and they look good.  I'll run them by the design team at our next meeting, which is tomorrow, and we will go from there.

**Comment by jbphet** [comment]
@mariahmaephet - I was just doing some testing and realized that we need to separate out the glacier from the background like we do for the other dates.  The screenshot below should illustrate.  Can I get split up version from you?

![image](https://user-images.githubusercontent.com/3082831/206028481-a9e36b43-8a38-46b0-9465-76a108a644bd.png)

**Comment by mariahmaephet** [comment]
![iceageback](https://user-images.githubusercontent.com/11527557/206262704-b12b2645-e3cd-4ca4-900e-53c87be858a0.png)
![iceglacier](https://user-images.githubusercontent.com/11527557/206262706-e4efc668-78db-4e7e-998d-170566924c38.png)

**Comment by jbphet** [comment]
We're almost there - the rocks for the ice age image look good.  Unfortunately, this image seems to have some transparent parts that shift it up and right a bit.  Here is what it looks like in the sim:

![image](https://user-images.githubusercontent.com/3082831/206328146-1ad09e0e-f266-4da6-ba7c-7f18b0729120.png)

I looked at it in MS Paint and could see the extended boundaries there too.

Also, and apologies for not thinking to mention this earlier, but we should position the rocks so that they aren't where the visible and IR light are coming in and going out on the "Waves" screen.  Here is a screenshot of the current situation, and it would be great if the the big rock was between the two IR waves in the center, and the others just generally out of the way of the other waves.

![image](https://user-images.githubusercontent.com/3082831/206329049-9d427c12-083e-4245-9b41-989a020c0fdf.png)

**Comment by arouinfar** [comment]
Love the rocks!

**Comment by mariahmaephet** [comment]
@jbphet hmmm, it looks like it just wasn't situated far enough down (we can see the boundary dash in the bottom center), but I made some adjustments so hopefully it lines up right this time.

and is that where you wanted the rock?
![iceback](https://user-images.githubusercontent.com/11527557/207098589-4616b3d1-9717-4d19-8cf6-1c393f681d47.png)
![icerocks](https://user-images.githubusercontent.com/11527557/207098592-fcc0d1c5-63ab-4a04-a2b3-58cf7f801b2c.png)

**Comment by jbphet** [comment]
Looking pretty good!  One last tweak from me, then I'll turn it over to the design team for review.  Can we move the closest rock to the right a little so that it is between the two nearby IR waves, and can we move the leftmost of the two more distant rocks to the left a little so that the visible wave isn't over it?  Here's an edited screenshot to illustrate:

![image](https://user-images.githubusercontent.com/3082831/207467202-f6d32936-edb4-487a-8cb5-a9ad053c714b.png)

**Comment by jbphet** [comment]
Actually, one other thought: The highlighting on the thermometer shows the light source to be up and left, and the shading on the rocks is from a light source that is up and to the right.  Can we flip the rocks horizontally to make this more consistent?

**Comment by kathy-phet** [comment]
Can you also move the snow cap peak in the back to the left similar to the rock, so the yellow sunlight is against brown. It’s lost in the white of the mountain peak. Sent from my iPhoneOn Dec 13, 2022, at 4:29 PM, John B ***@***.***> wrote:﻿
Looking pretty good!  One last tweak from me, then I'll turn it over to the design team for review.  Can we move the closest rock to the right a little so that it is between the two nearby IR waves, and can we move the leftmost of the two more distant rocks to the left a little so that the visible wave isn't over it?  Here's an edited screenshot to illustrate:

**Comment by mariahmaephet** [comment]
So if I was following--no snow on that peak and move that rock to the right more? 

![mtnnopeak](https://user-images.githubusercontent.com/11527557/207666229-30b0534c-6ee8-4942-93b8-424b542d14cb.png)
![mtnrock](https://user-images.githubusercontent.com/11527557/207666233-c37069d5-795b-4ecb-8207-0ca36c4bb6c1.png)

**Comment by kathy-phet** [comment]
I was suggesting moving the snowy peak left. I liked the snowy peak, just shift so the yellow beam doesn't hit it.

**Comment by mariahmaephet** [comment]
@kathy-phet as in onto the peak on the far left?

**Comment by kathy-phet** [comment]
I meant this ...
![image](https://user-images.githubusercontent.com/5096804/207699224-c279ef09-0e9d-4ab0-98fd-8e935debc8fa.png)

**Comment by kathy-phet** [comment]
So the peak is the same but between the yellow and red waves.

**Comment by kathy-phet** [comment]
Pedagogically, having the peak where it was was problematic, because it was a white thing, and should have also reflected, just like the cloud.

**Comment by mariahmaephet** [comment]
oh, okay. We have the peaks lined up so they all match in the different eras, so we can move the mountain but would need to do it to all of them (which I can do)

**Comment by kathy-phet** [comment]
They were basically looking pretty unique on the ice-age. I see how they line up in the other periods. Basically, snow and the yellow beam doesn't work due to contrast and due to pedagogy, so whatever makes that not happen works for me.

**Comment by jbphet** [comment]
We've addressed this by moving the snow to the rightmost peak.  @kathy-phet - Can you look at the latest phet-test version and let us know if you're cool with it?

**Comment by jbphet** [comment]
The design team discussed whether to use the image in https://github.com/phetsims/greenhouse-effect/issues/49#issuecomment-1352045023 (with two snow capped mountains) and opted not to.  We like the one with a single snow cap on the right side.

**Comment by jbphet** [comment]
We've got all the updated artwork in place, and it has been approved by the design team.  I'm going to close this issue, and we can follow up with any changes or revisions in separate, unique issues.  Nice work @mariahmaephet!
