### ISSUE TITLE
Reduce the number of waves to 3 visible & 4 IR.

### ISSUE THREAD

**Issue by samreid** [phetsims/greenhouse-effect#5]
From https://github.com/phetsims/greenhouse-effect/issues/3#issuecomment-600985079.  @arouinfar said:

> Reduce the number of waves to 3 visible & 4 IR.

**Comment by samreid** [comment]
Can you please be more specific about this?  For the yellow rays, do you want me to remove a triplet (incoming + transmitted + reflected) or one that doesn't hit a cloud?  Same question for the reds, do you want me to remove the single (2nd from the left) or one of the triplets?

**Comment by kathy-phet** [comment]
@arouinfar - what do you think?

**Comment by arouinfar** [comment]
Visible: remove one of the beams that doesn't hit a cloud
IR: remove the beam that doesn't split

How does that sound @kathy-phet?

**Comment by kathy-phet** [comment]
Sounds good to me.

**Comment by samreid** [comment]
I removed the waves that don't split (one red and one yellow).  This leaves an empty space where they used to be.  Please open a new issue if you would like the other wave positions to be adjusted.  This issue is ready for review.

**Comment by arouinfar** [comment]
Thanks @samreid. I think it would be nice to equally space the waves, so I've opened #12.
