### ISSUE TITLE
Depict the time-based propagation of the waves

### ISSUE THREAD

**Issue by samreid** [phetsims/greenhouse-effect#6]
From https://github.com/phetsims/greenhouse-effect/issues/3#issuecomment-600985079.  @arouinfar said:

> Return the propagation of the waves. Visible enters from the top of the screen. Once it hits the ground, the IR propagates up.

**Comment by samreid** [comment]
Can you be more specific?  Do you mean the yellow waves that strike the ground, emits a red wave from the same point?  Is this from the "transmitted" part that goes through clouds as well as the yellow waves that don't strike clouds at all?  Do these need to be in phase (as part of #10)?  Does the ground emit any IR from places where yellow waves don't strike?

**Comment by arouinfar** [comment]
@samreid does @kathy-phet's description clarify things for you? If not, let me know. I'd be happy to hop on a quick zoom chat with you.

**Comment by samreid** [comment]
This prototype was developed with the simplifying assumption that we would not need to depict the propagation of the waves and that everything would be in a steady state.  It sounds like that requirement is changing.  I would estimate 2-6 hours for this part and will plan to work on it unless I hear it's not worth that amount of time.

**Comment by samreid** [comment]
Implemented in the commits.  I also added a "reset time" button which restarts propagation.  Please review.

**Comment by arouinfar** [comment]
Thanks @samreid. I think this should be good enough to get the idea across. 

If this code ends up being used in the sim, there is some odd behavior we'd want to clean up. A few things I've noticed:
* The right-most visible wave lags a bit behind the other two.
* The IR waves can emerge before the visible reach the ground if visible is set to any of the non-wave options before switching to Wave.

**Comment by samreid** [comment]
I eliminated the lag from the rightmost wave.
