### ISSUE TITLE
Initial review of the phet-io Studio tree for the Waves screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#65]
@arouinfar and @kathy-phet said that we should to an initial review of the studio tree before going into dev testing.  I've published a dev version with an early version of the tree for the Waves screen.  @arouinfar - please review and give me your feedback.  See https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.0-dev.14/phet-io/wrappers/studio/.

**Comment by jbphet** [comment]
@arouinfar and I met over Zoom, here are her suggestions:

- [ ] remove emEnergyPacketGroup from the tree
- [ ] remove sunEnergySource and groundEnergySource from the tree
- [ ] change 2019 to 2020
- [ ] have a dedicated property for controlling the cloud instead of the current count that is used in the base class
- [ ] everything about the atmosphere layers should be read-only
- [ ] make the wave archetype read only
- [ ] add the ability to hide all of the waves in studio
- [ ] visibilityControls - what exactly are these, and can the name be improved?

**Comment by jbphet** [comment]
There were two items in the list above that were not done during this round of changes.  Explanations below.

> remove sunEnergySource and groundEnergySource from the tree

According to @zepumph, there is currently no option to prevent instrumented items from appearing in the tree, so this should be handled using 'featured'.

> make the wave archetype read only

There doesn't seem to be an option to do this, and `phetioReadOnly` doesn't work.  I looked at the bunnies in natural selection, and the archetype there is not set to read-only, so I think this will need to remain as is.

Also, for the item on the list that says:

> visibilityControls - what exactly are these, and can the name be improved?

I changed the name to `instrumentVisibilityControls`.  Let me know if that will suffice.

**Comment by jbphet** [comment]
@arouinfar - These changes are now on master, please check them over and let me know if you think more changes are needed.

**Comment by arouinfar** [comment]
I reviewed the changes described in https://github.com/phetsims/greenhouse-effect/issues/65#issuecomment-894536655, and things are looking good, with two exceptions.
> change 2019 to 2020

I caught one instance of 2019 still in the tree:
`greenhouseEffect.wavesScreen.view.concentrationControlPanel.dateControl.dateRadioButtonGroup.twentyNineteenRadioButton`

> `visibilityControls` - what exactly are these, and can the name be improved?
>> I changed the name to `instrumentVisibilityControls`. Let me know if that will suffice.

I think this is an improvement, but I wonder if we could instead generalize it to something simple like `observationWindow.controlPanel`. This would also give us some flexibility in regards to the contents. 

@jbphet here are the remaining review comments for the Waves Screen:

- [ ] `greenhouseEffect.wavesScreen.model.groundLayer.albedoProperty` - needs phetioDocumentation and should be phetioReadOnly: true (not user-controlled on this screen).
- [ ] All instances of `temperatureProperty` falling under `model.atmosphereLayers` or `model.groundLayer` should have units and should be phetioHighFrequency: true
- [ ] `greenhouseEffect.wavesScreen.model.surfaceTemperatureKelvinProperty` - phetioHighFrequency: true
- [ ] Both instances of `energyRateProperty` should have phetioDocumentation and units.
- [ ] `​​model.concentrationProperty` and `model.manuallyControlledConcentrationProperty` seem similar and would benefit from phetioDocumentation.
- [ ] There doesn't seem to be any use of dynamic layout. For example, the concentrationControlPanel doesn't move up when the energyLegend is hidden. Similarly, hiding contents within the concnetrationControlPanel doesn't shrink the panel size.
- [ ] Setting `view.concentrationSlider.slider.visibleProperty` to false leaves the min/max labels behind, so let's add a top-level `visibleProperty` to `greenhouseEffect.wavesScreen.view.concentrationControlPanel.concentrationSlider` so the entire control can be hidden at once. 
- [ ] The client usually wants the ability to change the strings within the sim. Please add `textProperty` to all checkboxes, the "Greenhouse Gas Concentration" panel title, and all text within the `energyLegend`.

**Comment by jbphet** [comment]
@arouinfar - I believe I've added everything requested in the previous comment, please review.

As for the dynamic layout, I've addressed the two specific items you mentioned but stopped there, since there are lots of other things that could be done but there was nothing obvious to me that I thought users were likely to need.  Let me know if you think addition dynamic layout needs to be supported and, if so, what.

**Comment by arouinfar** [comment]
Thanks @jbphet! Everything looks good in master. Remaining PhET-iO design work (phetioFeatured, client guides) can be tracked in separate issues, so closing this one.

**Comment by arouinfar** [comment]
@jbphet one quick (and hopefully last) request for you...

- [ ] `startSunlightButton.visibleProperty` should be read-only since it's controlled by the `isShiningProperty` in the model.

**Comment by jbphet** [comment]
I've made the change requested in the previous comment.  Closing.
