### ISSUE TITLE
Change the IR ground angle to 30 degrees

### ISSUE THREAD

**Issue by samreid** [phetsims/greenhouse-effect#7]
From https://github.com/phetsims/greenhouse-effect/issues/3#issuecomment-600985079.  @arouinfar said:

Change angle of IR coming out of the ground to something like this 
<img src="https://user-images.githubusercontent.com/8419308/77031392-1dc1a780-6967-11ea-813b-b7bd5bb75e28.png" width=100>

**Comment by samreid** [comment]
I turned the IR from the ground to be 30 degrees.  I could use some help rearranging them so they don't overlap too much, perhaps after we finish #5?  What do you think?

**Comment by arouinfar** [comment]
This is looking pretty good @samreid. I'll review again once #5 has been completed.

**Comment by arouinfar** [comment]
Final review pending the changes in #12.

**Comment by arouinfar** [comment]
This angle has been working fine for us during brainstorming meeting, so closing.
