### ISSUE TITLE
Should we add arrows (or something) to the waves when sim is paused?

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#71]
I've noticed during development that it is sometimes hard to interpret what's being portrayed on the "Waves" screen when the sim is paused.  During today's design meeting, @kathy-phet had the same experience, noting that it looked like something "really weird" was going on with the screen when it was just that it had been paused at a time that created some odd-looking wave depictions.  Below is a screenshot:

![image](https://user-images.githubusercontent.com/3082831/132580822-6e6b01eb-9ab3-4763-9aee-ebc17b6a1cc0.png)

Should we consider putting arrows on the waves when the sim is paused to make it clearer which way the waves are moving?  Are there other things that might help with this?

**Comment by arouinfar** [comment]
I think the solution here may be to just use `waveGapsEnabled=false` as the default state. Let's discuss at next week's meeting.

**Comment by arouinfar** [comment]
The wave gaps no longer exist, so we can go ahead and close this issue.
