### ISSUE TITLE
Add a query parameter to turn off wave spacing

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#72]
In the current master version and all recent dev versions of this sim there are spaces placed between the waves on the "Waves" screen.  This is done to convey the idea that the waves are actually everywhere, and we are just showing some of them.  However, this can be a bit confusing, and the design team has requested that a query parameter be added that can turn off this spacing.

For clarity, here's a screen shot with some markup of the spaces (I didn't mark them all):

![image](https://user-images.githubusercontent.com/3082831/132581748-46079ab7-dee0-4cb8-9d76-300afd93666b.png)

**Comment by jbphet** [comment]
I've added this feature.  The query parameter is called `waveGapsEnabled`, and it is `true` by default, so adding `waveGapsEnabled=false` can be used to turn them off.

@arouinfar - Please try this out on master and make sure that it works as discussed.  Also, it would probably be good to say whether you think the spacing should be off by default.  Personally, I find it less chaotic looking without the gaps.

**Comment by arouinfar** [comment]
Thanks @jbphet the query parameter is working as intended.

I quite like `waveGapsEnabled=false` and I may even prefer it as the default option. I was a bit worried that it would be harder to notice the wave directionality, but I don't find that to be the case. It would also avoid issues like #71.

We can discuss more at next week's meeting to see what the team prefers.

**Comment by arouinfar** [comment]
@jbphet I had a brief chat with @kathy-phet, and we decided to make `waveGapsEnabled=false` the default behavior. Please make this change before the rc.

**Comment by jbphet** [comment]
The query parameter has been updated and the default has been changed.  I think we're done here.  Closing.
