### ISSUE TITLE
Add support for visible light being reflected from the Earth

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#73]
In the 9/8/2021 design meeting, it came up that we need the glaciers in the "Ice Age" screen to reflect some of the sunlight.  We decided that we will make the glacier appear on the right side in the artwork and will make the sunlight waves on this side of the observation window reflect upward at a pretty acute angle.

I will take a shot at implementing this and will have the design team review it.  Note that it will probably work before we have corresponding artwork to go with it, so we will have to use our imaginations a bit.

**Comment by jbphet** [comment]
I've added support for reflecting light off of the ground and have implemented an initial, rather crude version of the feature as it relates to reflecting off of a glacier.  To make it easier to understand, and also added a simple shape in the view that is meant as a placeholder for the glacier.  This is all available on master, and the reflection looks like this:

![image](https://user-images.githubusercontent.com/3082831/132776839-558669c1-d620-4337-b312-51a54745d1ab.png)

The glacier is turned on by selecting "Ice Age" as the date that is being represented.

The process of implementing this has created several questions for which I'd like to get input from the design team.  They are:
- Should the glacier turn on as soon as the Ice Age is selected, or should it only appear at certain temperatures?
- Should the glacier only appear in the date selection view, or should it also appear at lower temperatures when the user is setting the gas concentration via the slider?
- Should IR waves and energy be reflected?  At the moment, the model is only reflecting visible light.
- Where would we like the reflected light to go?  At the design meeting we said it should be reflected at "an acute angle", so I took a guess, but it does tend to overlap with other waves and look a bit confusing.

Assigning to @arouinfar and @kathy-phet to get their input.

**Comment by arouinfar** [comment]
>Should the glacier turn on as soon as the Ice Age is selected, or should it only appear at certain temperatures?

The glacier is a part of the Ice Age artwork, and that is the only time it should appear on the Waves and Photons screens.

> Should the glacier only appear in the date selection view, or should it also appear at lower temperatures when the user is setting the gas concentration via the slider?

Only when Ice Age is selected.

> Should IR waves and energy be reflected? At the moment, the model is only reflecting visible light.

I don't think glaciers should reflect IR, and [this source from NASA](https://earthobservatory.nasa.gov/Features/Glaciers/glaciers_4.php#:~:text=Like%20most%20white%20objects%2C%20the,red%20on%20the%20color%20spectrum) seems to corroborate, but let's check with @kathy-phet .

>Like most white objects, the glacier reflects nearly all the colors of the visible spectrum, including the yellow-green sunlight. Yet, a glacier absorbs near-infrared wavelengths of solar energy (light to the right of red on the color spectrum).


> Where would we like the reflected light to go? At the design meeting we said it should be reflected at "an acute angle", so I took a guess, but it does tend to overlap with other waves and look a bit confusing.

Things look pretty good to me with `waveGapsEnabled=false`, but they can get pretty messy when the reflected sunlight starts overlapping the 2nd sunlight wave.

![image](https://user-images.githubusercontent.com/8419308/132930013-f143988e-b41f-4b1e-9efe-6e4f2475e695.png)

![image](https://user-images.githubusercontent.com/8419308/132930048-683d6b99-83f6-46d7-833b-2125d56ad5e9.png)

**Comment by arouinfar** [comment]
The glacier behavior has been looking good for awhile now, so I think we can go ahead and close this issue.
