### ISSUE TITLE
Visible light radiates from ground in Studio Wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#78]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.5.2

**Browser**
chrome

**Problem description**
https://github.com/phetsims/qa/issues/707

Visible light radiates from the ground in all scenes if Studio is launched while in the Ice Age scene. 

**Steps to reproduce**
1. In the Studio Wrapper: Press the start sunlight button
2. Press the calendar button and select "Ice Age"
3. Once the visible light begins to radiate from the glacier, press the "preview sim" button
4. In the Launched Sim: change the year or select the Slider Icon Button. The visible light rays will continue to radiate from the ground even though no ice is present. 

**Visuals**
![sunlight](https://user-images.githubusercontent.com/87318828/133436459-e0d26aa4-8b78-4240-8baa-083c47958426.gif)

**Comment by jbphet** [comment]
Some of the information about the reflected waves were not being serialized.  I've fixed this.

**Comment by jessegreenberg** [comment]
I didn't see it referenced here but I confirmed that 302b6b5fddcc215bb91104b3827260dfe36e27e8 was cherry picked into 1.0 and I wasn't able to reproduce this issue with 1.0 SHAs.

**Comment by Nancy-Salpepi** [comment]
I was not able to reproduce this issue.
