### ISSUE TITLE
Energy balance reading incorrect when sim is first launched in Studio and State wrappers

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#80]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.5.2

**Browser**
chrome

**Problem description**
https://github.com/phetsims/qa/issues/707

When a sim is launched in Studio, the energy balance arrows initially show only an inflow of energy--similar to when the sim is first launched--rather than the current state. 

**Steps to reproduce**
1. Press "Start Sunlight" button
2. Check "Energy Balance" Checkbox
3. Wait for Energy in/out arrows to equalize 
4. Press "Preview Sim" button

This is also seen in the State Wrapper as well. 

**Visuals**

![energybalance](https://user-images.githubusercontent.com/87318828/133462275-4d1e7ea9-64b8-43d3-9f2b-2ffb43d1b28c.gif)

In State:
<img width="513" alt="Screen Shot 2021-09-15 at 11 28 14 AM" src="https://user-images.githubusercontent.com/87318828/133463137-a27faf38-b20b-4414-9316-a38c40fec653.png">

**Comment by Nancy-Salpepi** [comment]
In the State wrapper, with default settings, the energy balance didn't change at all. The "in" and "net" arrows were both pointing down with no movement (see picture above). 

Steps to reproduce:
Press "Start Sunlight" button
Check "Energy Balance" Checkbox

However, when the "set state rate" value is zero and the "set state now" button is used, the arrows will match the upstream sim after a delay (similar to what I saw in studio).

Steps to reproduce:
1. Move the "set state rate" slider to a value =0
2. In the upstream sim: Press "Start Sunlight" button and check "Energy Balance" Checkbox
3. Press the "set state now" button

**Comment by zepumph** [comment]
Looks like my fixes on the branch weren't totally complete. I'll keep testing.

**Comment by zepumph** [comment]
Ok. Quite a bit has happened since @jbphet started working on this this morning. He got very far, in part while working with me, but we couldn't quite solve every single bug, so he committed to a branch (https://github.com/phetsims/greenhouse-effect/commit/0e4526da6f92268d9681b9c8e2006fa87bf5b895). It was almost entirely correct, but needed fixes I added in https://github.com/phetsims/greenhouse-effect/commit/0d633e5cf2af1fe80c75e87c0901bd0dd8235b0d.

There was one more issue, identified and fixed in https://github.com/phetsims/greenhouse-effect/issues/86, that kept @jbphet from merging that branch into master. 

After that fix, I cannot reproduce the bug, so I am going to merge this code into master.

**Comment by zepumph** [comment]
@Nancy-Salpepi, will you please review this on master, can you reproduce? I cannot.

**Comment by zepumph** [comment]
If cherry-picking, please do all commits in this repo, and the commit in https://github.com/phetsims/greenhouse-effect/issues/86.

**Comment by Nancy-Salpepi** [comment]
Hey @zepumph!
I cannot reproduce any of the scenarios I reported.

**Comment by zepumph** [comment]
Wahoo! Over to @jessegreenberg for cherry-picking.

**Comment by jessegreenberg** [comment]
> Wahoo! Over to @jessegreenberg for cherry-picking.

OK thanks! These are the commits to cherry pick for this issue and #86, after confirming with @zepumph:
- https://github.com/phetsims/greenhouse-effect/commit/0e4526da6f92268d9681b9c8e2006fa87bf5b895
- https://github.com/phetsims/greenhouse-effect/commit/0d633e5cf2af1fe80c75e87c0901bd0dd8235b0d
- https://github.com/phetsims/greenhouse-effect/commit/d8564f8cdcc27c8ffbfbb38e5a80ce28f00e7c19
- https://github.com/phetsims/greenhouse-effect/commit/503e4ff654e965cf5a07255d3cc097001d93cca8

**Comment by Nancy-Salpepi** [comment]
I was unable to reproduce the energy balance issue in studio/state wrappers.
