### ISSUE TITLE
The energy balance meter seems delayed - can this be improved?

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#84]
@kathy-phet brought this up in today's design meeting.

**Comment by KatieWoe** [comment]
Noticed this in https://github.com/phetsims/qa/issues/707

**Comment by arouinfar** [comment]
@jessegreenberg this does not block the prototype.

**Comment by jbphet** [comment]
I'm deferring this issue and #94 until we have an initial implementation of the "Photons" screen that we can experiment with.  This was recommended by @kathy-phet during yesterday's design meeting.

**Comment by KatieWoe** [comment]
Noting this again in https://github.com/phetsims/qa/issues/811

**Comment by jbphet** [comment]
Let's discuss this with @kathy-phet the next time she is in the weekly design meeting.

**Comment by jbphet** [comment]
Discussed with @kathy-phet in the 6/29/2022 design meeting, and there are two possibilities that we thought of to make this better:
1. Make the model run faster for a short period right after changes are made to the greenhouse gas concentration so that the energy change reaches the top of the atmosphere more quickly
2. Go back to where the waves have changes in thickness that they carry as they propagate in order to better portray where the energy change occurs

We'll discuss with @arouinfar at the next design meeting and make a call on what to try.

**Comment by jbphet** [comment]
Discussed at today's design meeting, and we decided to resurrect the varying thickness feature.

**Comment by jbphet** [comment]
The varying thickness feature, which I kept around because I thought it might come back, was being tracked in https://github.com/phetsims/greenhouse-effect/issues/84.

**Comment by jbphet** [comment]
I've implemented the behavior where the thickness of the lines representing the waves include variations in thickness to indicate their intensity at various locations along the wave.  I've done this on a branch in case we end up not using it.  We reviewed an early version in a design meeting a few weeks back, and @kathy-phet and @arouinfar felt it was worth continuing to refine it.

I have it working reasonably well at this point, but because each segment where the thickness changes has to be rendered as a separate `context.stroke` operation, there ends up being some overlap at the ends of the segments, and this results in visible artifacts when opacity is used as part of the wave intensity depiction.  I described this in the most recent design meeting, but was unable to demo it due to changes of the common code that were incompatible with the branch.

To give the designers a chance to try this out and determine whether the overlaps in the rendering are problematic, I've published a on-off version that includes a query parameter to turn on or off the use of opacity in the wave rendering.

@kathy-phet and @arouinfar - Please compare the versions at the following two links and let me know your thoughts on how each looks.

[Greenhouse Effect, waves vary in thickness, opacity used in rendering](https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-betterEnergyBalanceBehavior.1/phet/greenhouse-effect_en_phet.html?screens=1)
[Greenhouse Effect, waves vary in thickness, opacity *not* used in rendering](https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-betterEnergyBalanceBehavior.1/phet/greenhouse-effect_en_phet.html?screens=1&useOpacityForWaveRendering=false)

**Comment by arouinfar** [comment]
Thanks @jbphet. I prefer the version with the opacity, and I think the artifacts at the stroke boundaries are generally small. Here are some examples of the extreme cases:

<img width="224" alt="image" src="https://user-images.githubusercontent.com/8419308/191300362-5aa1cdf9-6671-4db9-8a6d-7b119b028fe0.png"> <img width="227" alt="image" src="https://user-images.githubusercontent.com/8419308/191300673-386c2c82-3b9a-4a61-98ab-15377333a7a2.png">

We have more dynamic range when using the opacity, so it's easier to pick up on subtle differences. Here are some comparisons of high, middle, and low greenhouse gas concentration:
| With opacity | Without opacity | 
| --- | --- |
| <img width="969" alt="image" src="https://user-images.githubusercontent.com/8419308/191304041-e2b1bd72-68c9-45c7-b58b-fba31459da3d.png"> | <img width="966" alt="image" src="https://user-images.githubusercontent.com/8419308/191304104-96482682-73a1-4cdc-bbb1-2f6b7209e8ae.png"> |
| <img width="969" alt="image" src="https://user-images.githubusercontent.com/8419308/191302525-ba184cec-106e-4490-8ccd-102ca198bdbb.png"> |  <img width="969" alt="image" src="https://user-images.githubusercontent.com/8419308/191302848-b6bbf07f-0935-440d-a9f3-8a0c1d8794ff.png"> |
|  <img width="965" alt="image" src="https://user-images.githubusercontent.com/8419308/191304381-71ebba06-68c8-47dc-95e9-147d326c7fe0.png"> | <img width="966" alt="image" src="https://user-images.githubusercontent.com/8419308/191304669-c35b5d12-fbe4-4f75-bc2b-3442563f143b.png"> |

I'll tag this for design meeting to get feedback from the rest of the team.

**Comment by jbphet** [comment]
In the review meeting, the design team said that they are fine with the way the waves look when rendered with opacity, and the points where sections of the waves overlap didn't bother them.  I'll remove the query parameter and make it always render the waves using opacity as part of the intensity indication.

**Comment by jbphet** [comment]
The changes where the waves change in thickness according the the amount of energy at a given level in the atmosphere is now fully integrated into master.  @arouinfar - I'm assigning this to you for the final call on whether this fully addresses the original issue where the balance meter behavior seemed delayed.

**Comment by arouinfar** [comment]
We reviewed this at last week's design meeting, and it looks good. Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by jbphet** [comment]
I've removed the TODO that caused this to be reopened and did some updating of the docs.  Re-closing.
