### ISSUE TITLE
Direction of reflected visible light changes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#87]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.5.2

**Browser**
seen in both chrome and safari

**Problem description**
https://github.com/phetsims/qa/issues/707

The direction of the reflected visible light changes depending on when the cloud is first introduced into the sim. If introduced when the sim is in Date Mode, the reflected light veers to the right. It will always move in that direction  regardless of the setting until the sim is reset. If the cloud is introduced when the sim is in Slider Mode, the reflected light veers to the left and is partially obstructed by the Energy Balance Panel. 

**Steps to reproduce**
1. Press the "Start Sunlight" button
2. Check the Cloud checkbox (reflected light moves to upper left)
3. Select Date mode
4. Uncheck the Cloud checkbox
5. Wait for the reflected wave to disappear and then recheck the Cloud checkbox
6. Reset sim
7. Repeat above steps starting in Date mode and moving to Slider mode (reflected light moves to upper right)

**Visuals**
Cloud first introduced in Slider Mode:

<img width="1037" alt="Screen Shot 2021-09-17 at 8 00 53 AM" src="https://user-images.githubusercontent.com/87318828/133783402-7f650064-0d28-48b0-8fa3-f02e10f6e154.png">

Cloud first introduced in Date Mode:

<img width="1037" alt="Screen Shot 2021-09-17 at 8 00 21 AM" src="https://user-images.githubusercontent.com/87318828/133783409-d2db1cb4-4ce4-4135-9594-011f2ac8f108.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.0.0-rc.1 2021-09-14 17:56:28 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
Language: en-us
Window: 1199x683
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by arouinfar** [comment]
Thanks for reporting @Nancy-Salpepi. 

I think what's happening is that there are two possible sets of waves. With `waveGapsEnabled=true` you will see the sim cycle between each set. The default sim behavior is now `waveGapsEnabled=false`, but I think the default set of waves is randomly chosen. If the incoming sunlight is on the left side of the cloud, the reflected wave will go to the left. However, if the incoming sunlight is more towards the right side of the cloud, the reflected wave will go to the right.

I'll let @jbphet confirm if my suspicion is correct. If so, I'll make a note in the Teacher Tips and we can close.

@jessegreenberg this does not block the prototype version.

**Comment by jessegreenberg** [comment]
I just took a look at the code and what you described matches what I see @arouinfar. This code specifically changes the direction of the wave depending on whether it is to the left or the right of the position of the cloud

https://github.com/phetsims/greenhouse-effect/blob/a72675dbf2092a20631d9097db9a4dec0012bfec/js/waves/model/WavesModel.js#L246-L248

**Comment by jbphet** [comment]
The two comments above are correct.  @arouinfar - This can easily be changed such that we use a consistent set of initial waves at the outset.  I just didn't think about it when adding the ability to turn off wave gaps.  Would it be an improvement to do so?  If so, please assign back to me and I'll take care of it, otherwise please close.

**Comment by jbphet** [comment]
We discussed this in today's design meeting, and decided to leave the current behavior as is, at least for now.  Closing.
