### ISSUE TITLE
Energy arrow and Thermometer scale changes are hard to see

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#89]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.5.2

**Browser**
Chrome and Safari

**Problem description**
https://github.com/phetsims/qa/issues/707

When changing from one benchmark date to another, the changes in the energy balance panel are very minor. The Net arrow is usually just a small blip on the screen. @stemilymill and I only know its an arrow based on context. 

Similarly, the changes in the thermometer scale are also minor. The largest difference we can see is between 2 tick marks when the slider is moved from Lots of Greenhouse Gas to None (with a cloud). In date mode, the difference is very minute when changing from one benchmark to another. 

From a teacher standpoint, I'm not sure that students would look at this and think it is a major change. Let me know your thoughts. 

Here is an example with the energy arrows:

![19501750](https://user-images.githubusercontent.com/87318828/133823894-57ffdf6c-d7da-46b3-b105-7259f7895a9b.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Greenhouse Effect‬
URL: https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.0-rc.1/phet/greenhouse-effect_all_phet.html
Version: 1.0.0-rc.1 2021-09-14 17:56:28 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
Language: en-US
Window: 1440x693
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by arouinfar** [comment]
Excellent catch @Nancy-Salpepi!!

At the minimum temperature, the thermometer is already at the halfway point. At the max temperature, the thermometer has only risen by one tick mark.

![image](https://user-images.githubusercontent.com/8419308/133863748-6ba84428-6e7d-47b7-aa2c-61e809fce7fc.png) ![image](https://user-images.githubusercontent.com/8419308/133863797-de9acf23-cc30-4427-a58d-bc73f57dcb5d.png)

I think the range of a ThermometerNode is adjustable. Let's use the first minor tick mark as the min temp and the last minor tick mark as the max temp. I do think this would be a nice change to make before delivering to the client (if it's relatively straightforward), so I'll assign to @jessegreenberg.

**Comment by arouinfar** [comment]
> When changing from one benchmark date to another, the changes in the energy balance panel are very minor. The Net arrow is usually just a small blip on the screen. 

I think this likely comes down to how close the surface temperature is at these different benchmarks. I'll look at this a bit more, but I don't think there's anything we need to do about this for the prototype version.

**Comment by jessegreenberg** [comment]
> Let's use the first minor tick mark as the min temp and the last minor tick mark as the max temp.

@arouinfar and I discussed over slack. The range of `surfaceTemperatureKelvinProperty` is 0K-500K but when the sun is shining the minimum is actually 245K.  The maximum expected surface temperature is actually 295K (as described in GroundWaveSource.js). @arouinfar requested a bit of padding to make the thermometer look nice and so we went with 240kK-300K.

@arouinfar reviewed the look and said it was good to cherry pick into 1.0.

**Comment by jessegreenberg** [comment]
That much is done cherry-picked into 1.0, but there are still other design considerations in https://github.com/phetsims/greenhouse-effect/issues/89#issuecomment-922135738.

**Comment by Nancy-Salpepi** [comment]
Changes to the thermometer are great! Now there is definitely a more visible change for students to see. Thanks for considering my feedback @arouinfar. 
I know that the energy arrows are something that you are going to look into more for the future (not the prototype version), so I am going to keep this open. Feel free to close this if that is not correct.

**Comment by jbphet** [comment]
I've broken the issue about the magnitude of the arrows into it's own issue, see #94, and will close this one.
