### ISSUE TITLE
Add checkbox to hide clouds (could go in the grass)

### ISSUE THREAD

**Issue by samreid** [phetsims/greenhouse-effect#9]
From https://github.com/phetsims/greenhouse-effect/issues/3#issuecomment-600985079.  @arouinfar said:

> Add checkbox to hide clouds (could go in the grass)

**Comment by samreid** [comment]
Will hiding the clouds change the yellow beam "transmission" and "reflection"?  Or will that remain the same and this will just hide/show the cloud ellipses?

**Comment by kathy-phet** [comment]
For now just hiding the cloud themselves is fine.

**Comment by samreid** [comment]
The commit adds a checkbox that hides and shows the clouds without changing any of the other physics.  Ready for review.

**Comment by arouinfar** [comment]
Looks good in master. Thanks @samreid!
