### ISSUE TITLE
Blank spot in background

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#90]
I noticed a white line in the background located in the dip between the two hills.

<img width="312" alt="Screen Shot 2021-09-17 at 11 28 50 AM" src="https://user-images.githubusercontent.com/87318828/133825224-c062d563-b169-443e-8732-700945f44c95.png">

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi. We noticed this in a recent design meeting, and I think @jbphet fixed it locally, but the change didn't get pushed. 

@jbphet @jessegreenberg I don't think this is blocking for the prototype version.

**Comment by jbphet** [comment]
Yes indeed, the change made during design meeting got reverted during some subsequent work.  This is fixed on master now.  I addressed it by making the sky node extend a bit below the surface of the ground.  Closing.
