### ISSUE TITLE
Sound preference not maintained when sim is launched in Studio/State wrappers

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/greenhouse-effect#91]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.5.2

**Browser**
Chrome

**Problem description**
https://github.com/phetsims/qa/issues/707

This issue is related to: https://github.com/phetsims/joist/issues/745

In the Studio wrapper, if the sound is turned off on the nav bar, this preference is not maintained once the sim is launched. This is also seen in the State wrapper. 

**Steps to reproduce**
1. Turn off sound on the nav bar
2. Press "Preview Sim" button

**Comment by arouinfar** [comment]
@jessegreenberg I think this is ready for cherry-picking over in https://github.com/phetsims/joist/issues/745.

**Comment by jessegreenberg** [comment]
Cherry picks from https://github.com/phetsims/joist/issues/745 done and dependencies.json updated above.

**Comment by Nancy-Salpepi** [comment]
In the launched sim, once I turned the sound on, the reset button did not reset the sound preference to off. Shouldn't the sim reset to its original, launched version?

Steps:
1. Turn off sound on the nav bar
2. Press "Preview Sim" button
3. Turn on sound on the nav bar in the launched sim
4. Press the reset button

**Comment by jessegreenberg** [comment]
I don't think so, the navigation bar is not in the scope of things that get reset when pressing the Reset All button. And the behavior you described is what I would expect for a sim outside of studio as well. If audio is disabled I think we would want to keep that preference even after Reset All is pressed.

**Comment by jessegreenberg** [comment]
I may have been wrong about this. In phet-io meeting today @zepumph said that the common code behavior for ResetAllButton is to reset state instead of resetting the sim. @zepumph is the description from @Nancy-Salpepi in https://github.com/phetsims/greenhouse-effect/issues/91#issuecomment-925148561 the behavior that is expected?

**Comment by pixelzoom** [comment]
@jessegreenberg asked @zepumph a question on 9/23/21.  @zepumph unassigned himself without answering the question, or assigning anyone else, on 3/3/2023.   We're trying to wrap up all open issues, so we can publish the sim.  So assigning back to @zepumph again.

**Comment by zepumph** [comment]
Thanks for the ping. The behavior that @Nancy-Salpepi experienced is excellent and just right. @jessegreenberg is spot on, because the inner workings of the reset-button-state-setting is that it only applies to elements within that screen, so navbar/general items aren't touched. Re-closing
