### ISSUE TITLE
Screenshot needed for publication

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/greenhouse-effect#92]
We haven't added a screenshot yet and thankfully the production process caught this. I am not able to deploy the 1.0 prototype until there is a screenshot. Assigning to @arouinfar.

**Comment by arouinfar** [comment]
@jessegreenberg I've committed a screenshot to master and the 1.0 branches.

**Comment by jessegreenberg** [comment]
Great, thanks @arouinfar!
