### ISSUE TITLE
Branch: waves-instrumentation

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#96]
While working on #85 I noticed another branch in this repo that doesn't appear to have a corresponding issue, so I'm creating this one.

**Comment by jbphet** [comment]
@zepumph - This branch is 3 commits ahead of master and several (117 as of this writing) behind.  The commits were done by you and appear to be a11y-related.  Can you please have a look and determine whether this branch be deleted?

See https://github.com/phetsims/greenhouse-effect/commits/waves-instrumentation.

**Comment by zepumph** [comment]
Deleted, closing

**Comment by jbphet** [comment]
Thanks @zepumph!
