### ISSUE TITLE
Calibrate the actual temperatures, decide whether to show decimal values

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#98]
In the current master version, and also in the 1.0 version (see https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.0/phet/greenhouse-effect_en_phet.html), the temperature difference between 1750 and 2020 is about 5 degrees Celsius.  This isn't accurate - the change is actually closer to 1.5 degrees C.

Before we publish we should calibrate and make sure that the sim matches the historical data.

Also, if we want to make sure that the change is more noticeable, we should consider showing a single decimal place.

**Comment by jbphet** [comment]
I've done a round of updates for this.  @arouinfar - Can you please review on master and let me know what you think?  If the behavior is what we're after, you can close.

**Comment by jbphet** [comment]
@arouinfar - I've been asked to to a maintenance release of the 1.0 version with these changes, as you probably heard in our design meeting earlier this week.  I'd like for you to "sign off" on this issue before I do so that I don't have to make any tweaks or corrections later.  To that end, I'm going to raise the priority level.

**Comment by arouinfar** [comment]
@jbphet please proceed with the maintenance release. The temps look good in master.

**Comment by jbphet** [comment]
Cool, thanks.  I'll do the maintenance release under https://github.com/phetsims/greenhouse-effect/issues/112 and will close this one.
